////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#include "System\all.h"

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_PortChangeList_Dialog[7] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP_AR2,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN_AR2,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_SchemeButton[26] =
{
	{
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_KEYSTONE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_INFO, 0x00 },
		OEK_KEY_LOGICAL_DISPLAY,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_TTX_CC, 0x00 },
		OEK_KEY_LOGICAL_TTX_ON,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_AUTO, 0x00 },
		OEK_KEY_LOGICAL_AUTO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_POSITION, 0x00 },
		OEK_KEY_LOGICAL_PIP_POSTION,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ASPECT, 0x00 },
		OEK_KEY_LOGICAL_ASPECT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_ASPECTRATIO, 0x00 },
		OEK_KEY_LOGICAL_ASPECTRATIOPIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_UP, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_MpegNrSlider[21] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_KEYSTONE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_POSITION, 0x00 },
		OEK_KEY_LOGICAL_PIP_POSTION,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_SIZE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SIZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ASPECT, 0x00 },
		OEK_KEY_LOGICAL_ASPECT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_ASPECTRATIO, 0x00 },
		OEK_KEY_LOGICAL_ASPECTRATIOPIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_SharpnessControlSlider[21] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_KEYSTONE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT_AR2,
		20,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT_AR2,
		20,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_POSITION, 0x00 },
		OEK_KEY_LOGICAL_PIP_POSTION,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_SIZE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SIZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ASPECT, 0x00 },
		OEK_KEY_LOGICAL_ASPECT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_ASPECTRATIO, 0x00 },
		OEK_KEY_LOGICAL_ASPECTRATIOPIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_ImagePositionCeD5053751[11] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_KEYSTONE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_DisplayConditions[37] =
{
	{
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_KEYSTONE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_INFO, 0x00 },
		OEK_KEY_LOGICAL_DISPLAY,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_TTX_CC, 0x00 },
		OEK_KEY_LOGICAL_TTX_ON,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_ADC_1_AUTO, 0x00 },
		OEK_KEY_LOGICAL_AUTO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SCAN, 0x00 },
		OEK_KEY_LOGICAL_SCAN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_ZOOM_IN,
		17,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_ZOOM_OUT,
		17,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SLEEP, 0x00 },
		OEK_KEY_LOGICAL_SLEEP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x64 },
		OEK_KEY_LOGICAL_FACTORY_ENTRY,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_TTX_RED, 0x00 },
		OEK_KEY_LOGICAL_TTX_RED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_POSITION, 0x00 },
		OEK_KEY_LOGICAL_PIP_POSTION,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_SIZE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SIZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ASPECT, 0x00 },
		OEK_KEY_LOGICAL_ASPECT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_ASPECTRATIO, 0x00 },
		OEK_KEY_LOGICAL_ASPECTRATIOPIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN,
		12,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SUB, 0x00 },
		OEK_KEY_LOGICAL_SUB,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ENTER_JUMP, 0x00 },
		OEK_KEY_LOGICAL_RECALL,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ONE, 0x00 },
		OEK_KEY_LOGICAL_ONE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_TWO, 0x00 },
		OEK_KEY_LOGICAL_TWO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_THREE, 0x00 },
		OEK_KEY_LOGICAL_THREE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_UP, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_ADC_Offset1LV1[7] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

////////////////////////////////////////////////////////////////////////////////
//    Translation tables
////////////////////////////////////////////////////////////////////////////////

ST_TRANSLATION_TABLE_ENTRY ROM * ROM GlobalTranslTableSet[7] =
{
	TrTable_PortChangeList_Dialog,
	TrTable_SchemeButton,
	TrTable_MpegNrSlider,
	TrTable_SharpnessControlSlider,
	TrTable_ImagePositionCeD5053751,
	TrTable_DisplayConditions,
	TrTable_ADC_Offset1LV1
};

BYTE ROM TrtblMaxEntries[7] =
{
	0x07,
	0x1a,
	0x15,
	0x15,
	0x0b,
	0x25,
	0x07
};

WORD ROM KEYPAD_DEBOUNCE_PERIOD = 20;

BYTE ROM IR_Values[64] =
{
	WBK_EXTRACT_CODE_BYTE(28), Key_KEY_PHYSICAL_ASPECT,
	WBK_EXTRACT_CODE_BYTE(33), Key_KEY_PHYSICAL_CHANNEL_DOWN,
	WBK_EXTRACT_CODE_BYTE(32), Key_KEY_PHYSICAL_CHANNEL_UP,
	WBK_EXTRACT_CODE_BYTE(29), Key_KEY_PHYSICAL_DOWN,
	WBK_EXTRACT_CODE_BYTE(21), Key_KEY_PHYSICAL_ENTER_JUMP,
	WBK_EXTRACT_CODE_BYTE(24), Key_KEY_PHYSICAL_EXIT,
	WBK_EXTRACT_CODE_BYTE(20), Key_KEY_PHYSICAL_FREEZE,
	WBK_EXTRACT_CODE_BYTE(15), Key_KEY_PHYSICAL_INFO,
	WBK_EXTRACT_CODE_BYTE(25), Key_KEY_PHYSICAL_LEFT,
	WBK_EXTRACT_CODE_BYTE(22), Key_KEY_PHYSICAL_MENU,
	WBK_EXTRACT_CODE_BYTE(13), Key_KEY_PHYSICAL_MUTE,
	WBK_EXTRACT_CODE_BYTE(26), Key_KEY_PHYSICAL_OK,
	WBK_EXTRACT_CODE_BYTE(1), Key_KEY_PHYSICAL_ONE,
	WBK_EXTRACT_CODE_BYTE(11), Key_KEY_PHYSICAL_PIP,
	WBK_EXTRACT_CODE_BYTE(58), Key_KEY_PHYSICAL_PIP_ASPECTRATIO,
	WBK_EXTRACT_CODE_BYTE(18), Key_KEY_PHYSICAL_PIP_POSITION,
	WBK_EXTRACT_CODE_BYTE(19), Key_KEY_PHYSICAL_PIP_SIZE,
	WBK_EXTRACT_CODE_BYTE(12), Key_KEY_PHYSICAL_POWER,
	WBK_EXTRACT_CODE_BYTE(27), Key_KEY_PHYSICAL_RIGHT,
	WBK_EXTRACT_CODE_BYTE(31), Key_KEY_PHYSICAL_SCAN,
	WBK_EXTRACT_CODE_BYTE(38), Key_KEY_PHYSICAL_SLEEP,
	WBK_EXTRACT_CODE_BYTE(56), Key_KEY_PHYSICAL_SOURCE,
	WBK_EXTRACT_CODE_BYTE(36), Key_KEY_PHYSICAL_SPLIT,
	WBK_EXTRACT_CODE_BYTE(60), Key_KEY_PHYSICAL_SUB,
	WBK_EXTRACT_CODE_BYTE(14), Key_KEY_PHYSICAL_SWAP,
	WBK_EXTRACT_CODE_BYTE(3), Key_KEY_PHYSICAL_THREE,
	WBK_EXTRACT_CODE_BYTE(46), Key_KEY_PHYSICAL_TTX_CC,
	WBK_EXTRACT_CODE_BYTE(40), Key_KEY_PHYSICAL_TTX_RED,
	WBK_EXTRACT_CODE_BYTE(2), Key_KEY_PHYSICAL_TWO,
	WBK_EXTRACT_CODE_BYTE(23), Key_KEY_PHYSICAL_UP,
	WBK_EXTRACT_CODE_BYTE(17), Key_KEY_PHYSICAL_VOLUME_DOWN,
	WBK_EXTRACT_CODE_BYTE(16), Key_KEY_PHYSICAL_VOLUME_UP
};

WBK_KEYPAD_DEFINITION ROM Keypad_IR =
{
	0x00,
	IR_Values,
	0x20,
	GetIRValue,
	InitIRDriver,
	0x01,
	0x00
};

BYTE ROM ADC_1_Values[16] =
{
	WBK_EXTRACT_CODE_BYTE(75), Key_ADC_1_AUTO,
	WBK_EXTRACT_CODE_BYTE(111), Key_ADC_1_KEYSTONE,
	WBK_EXTRACT_CODE_BYTE(143), Key_KEY_PHYSICAL_CHANNEL_UP,
	WBK_EXTRACT_CODE_BYTE(206), Key_KEY_PHYSICAL_PIP,
	WBK_EXTRACT_CODE_BYTE(38), Key_KEY_PHYSICAL_POWER,
	WBK_EXTRACT_CODE_BYTE(175), Key_KEY_PHYSICAL_SOURCE,
	WBK_EXTRACT_CODE_BYTE(234), Key_KEY_PHYSICAL_SWAP,
	WBK_EXTRACT_CODE_BYTE(255), Key_KEY_PHYSICAL_VOLUME_UP
};

WBK_KEYPAD_DEFINITION ROM Keypad_ADC_1 =
{
	0x00,
	ADC_1_Values,
	0x08,
	GetADCValue,
	InitADCDriver,
	0x01,
	0x08
};

BYTE ROM ADC_2_Values[16] =
{
	WBK_EXTRACT_CODE_BYTE(39), Key_KEY_PHYSICAL_CHANNEL_DOWN,
	WBK_EXTRACT_CODE_BYTE(235), Key_KEY_PHYSICAL_DOWN,
	WBK_EXTRACT_CODE_BYTE(144), Key_KEY_PHYSICAL_LEFT,
	WBK_EXTRACT_CODE_BYTE(255), Key_KEY_PHYSICAL_MENU,
	WBK_EXTRACT_CODE_BYTE(175), Key_KEY_PHYSICAL_OK,
	WBK_EXTRACT_CODE_BYTE(75), Key_KEY_PHYSICAL_RIGHT,
	WBK_EXTRACT_CODE_BYTE(111), Key_KEY_PHYSICAL_UP,
	WBK_EXTRACT_CODE_BYTE(205), Key_KEY_PHYSICAL_VOLUME_DOWN
};

WBK_KEYPAD_DEFINITION ROM Keypad_ADC_2 =
{
	0x01,
	ADC_2_Values,
	0x08,
	GetADCValue,
	InitADCDriver,
	0x01,
	0x08
};

WBK_KEYPAD_DEFINITION ROM* ROM WBK_Keypads[3] =
{
	&Keypad_IR,
	&Keypad_ADC_1,
	&Keypad_ADC_2
};

BYTE ROM WBK_NumberOfKeypads = WB_NUMBER_OF_INPUT_SOURCE;

BYTE ROM WBK_MultiplePortsValuesTranslation[1] =
{
	0
};

BYTE ROM WBK_NumberMultiplePortsValues = WBK_NUMBER_OF_MULTIPLE_PORTS_VALUES;

