////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#include "System\all.h"

ModeIndependentUserPrefType  ModeIndependentUserPreferences;

ModeIndependentUserPrefType ROM FactoryDefaultInROM =
{
	TNR_LOW,	// TNR
 	MADI_STANDARD,	// MADI
 	CCS_OFF,	// CCS
 	SHARPNOISE_LOW,	// SharpNoise
 	0,	// SplitScreen
 	ENABLE,	// DCDiMain
 	ENABLE,	// DCDiPip
 	MPEG_NR_MOSQ_GAUSS,	// MPEGNRMode
 	MPEG_NR_THRESHOLD_0_DEF,	// MPEGNRThresh0
 	MPEG_NR_THRESHOLD_1_DEF,	// MPEGNRThresh1
 	MPEG_NR_THRESHOLD_2_DEF,	// MPEGNRThresh2
 	OD_NOISE_CORING_ADAPTIVE,	// LCDOverdriveNoiseCoring
 	NORMAL_32_DISPLAY_MODE,	// ThreeTwoFilmDisplayMode
 	VBI_SERVICE_CC,	// VBI_ServicePreferred
 	12,	// SharpnessPip
 	BLUE_STRETCH_OFF,	// BlueStretch
 	12,	// SharpnessRGB
 	12,	// SharpnessRGBpip
 	0,	// AVSDelay
 	DEFAULT_VOLUME_VALUE,	// AudioVolume
 	INTERNAL_DAC_COMP,	// ADCCalibrationMethod_Comp
 	INTERNAL_DAC_VGA,	// ADCCalibrationMethod_VGA
 	0,	// AspectRatioMain
 	0,	// AspectRatioPip
 	ALL_BOARDS_DP1,	// CurrentInputMain
 	ALL_BOARDS_DIP1,	// CurrentInputPip
 	0,	// DynamicContrast
 	FM_VIDEO_32,	// FilmMode
 	FT_OFF,	// FleshToneComp 'Desc' :Flesh tone compensation level
 	USER,	// ImageScheme
 	0,	// LCDOverdrive
 	DISABLE,	// LetterboxEnable
 	5,	// MPEGNR
 	127,	// OsdHPosition
 	0,	// OsdLanguage
 	OSD_NON_ROTATED,	// OsdRotation
 	0,	// OsdTimeout 'Desc' :Osd hide timeout
 	127,	// OsdVPosition
 	ENABLE,	// OverscanEnable
 	0,	// PanelSelect
 	0,	// PipMode
 	0,	// PipPosition
 	1,	// PowerState
 	12,	// Sharpness
 	0,	// SleepAMPM
 	0,	// SleepDay
 	0,	// SleepHour
 	0,	// SleepMin
 	0,	// SleepMinsLeft
 	0,	// ThreeDNR
 	7,	// TVRating
 	0,	// TVUnrated
 	WB_NVRAM_STRUCTURE_VERSION,	// Version
 	0,	// WakeAMPM
 	0,	// WakeDay
 	0,	// WakeHour
 	0,	// WakeMin
 	7,	// MPRating
 	0,	// AVSDelayTime
 	0,	// CC_On
 	0,	// AudioMute
 	POP7,	// MPipConfig
 	1,	// OSDSplashScreen 'Desc' :Enable/Disable Splash Screen
 	1111,	// ParentalPassword
 	LARGE_PIP,	// PipSize
 	ALL_BOARDS_DP1,	// PreviousInputMain
 	0,	// ScrollMenuItem
 	0,	// SplitLcdOverdrive
 	TTX_LANGUAGE_GROUP_WESTERN_EUROPE,	// TTXLanguageGroup 'Desc' :Language group set in TTX decoder
 	0,	// MainRouteModeComponent
 	0,	// MainRouteModeScartRGB
 	0,	// PipRouteModeComponent
 	0,	// PipRouteModeScartRGB
 	32,	// Reg_MVF_SHARPNESS_LUMA
 	16,	// Reg_MVF_SHARPNESS_CHROMA
 	16,	// Reg_MVF_NOISE_CORING_THRESH
 	48,	// Reg_MVF_NONLINEAR_THRESH1
 	4,	// Reg_MVF_NONLINEAR_GAIN1
 	170,	// Reg_MVF_NONLINEAR_THRESH2
 	4,	// Reg_MVF_NONLINEAR_GAIN2
 	32,	// Reg_MHF_SHARPNESS_LUMA
 	16,	// Reg_MHF_SHARPNESS_CHROMA
 	8,	// Reg_MHF_NOISE_CORING_THRESH
 	48,	// Reg_MHF_NONLINEAR_THRESH1
 	4,	// Reg_MHF_NONLINEAR_GAIN1
 	170,	// Reg_MHF_NONLINEAR_THRESH2
 	4,	// Reg_MHF_NONLINEAR_GAIN2
 	127,	// Reg_PVF_SHARPNESS_LUMA
 	127,	// Reg_PVF_SHARPNESS_CHROMA
 	0,	// Reg_PVF_NOISE_CORING_THRESH
 	255,	// Reg_PVF_NONLINEAR_THRESH1
 	0,	// Reg_PVF_NONLINEAR_GAIN1
 	255,	// Reg_PVF_NONLINEAR_THRESH2
 	0,	// Reg_PVF_NONLINEAR_GAIN2
 	127,	// Reg_PHF_SHARPNESS_LUMA
 	127,	// Reg_PHF_SHARPNESS_CHROMA
 	0,	// Reg_PHF_NOISE_CORING_THRESH
 	255,	// Reg_PHF_NONLINEAR_THRESH1
 	0,	// Reg_PHF_NONLINEAR_GAIN1
 	255,	// Reg_PHF_NONLINEAR_THRESH2
 	0,	// Reg_PHF_NONLINEAR_GAIN2
 	10,	// Reg_HEM_HLE_THR
 	180,	// Reg_HEM_HLE_GAIN
 	21,	// Reg_HEM_HDP_THR
 	71,	// Reg_HEM_HDP_GAIN
 	15,	// Reg_HEM_CE_THR
 	16,	// Reg_HEM_CE_GAIN
 	27,	// Reg_VDP_THRESHOLD
 	3,	// Reg_VDP_GAIN
 	NATIVE_MODE_OFF,	// NativeMode
 	YUV2RGB_EXPANSION_LINEAR,	// YUV2RGBExpansionMode
 	DISABLE,	// NonACMFleshtoneCorrection
 	0,	// NonACMFleshtoneBalance
 	0,	// NonACMFleshtoneCorrectionLevel
 	US_TV_RATING_SUBCODE_FV,	// UserPrefTVYouth7Subcode
 	(US_TV_RATING_SUBCODE_V | US_TV_RATING_SUBCODE_S | US_TV_RATING_SUBCODE_L | US_TV_RATING_SUBCODE_D),	// UserPrefTVPGSubcode
 	(US_TV_RATING_SUBCODE_V | US_TV_RATING_SUBCODE_S | US_TV_RATING_SUBCODE_L | US_TV_RATING_SUBCODE_D),	// UserPrefTV14Subcode
 	(US_TV_RATING_SUBCODE_V | US_TV_RATING_SUBCODE_S | US_TV_RATING_SUBCODE_L),	// UserPrefTVMASubcode
 	SWAGC,	// DecoderAGCMethod 'Desc' :DecoderAGCMethod
 	Off,	// CCSforHD
 	0,	// TwoStageProcessing
 	0,	// ManualTVMHzFreq
 	0,	// ManualTVkHzFreq
 	0,	// TVFreqFineTune
 	1,	// TVManualScanRequired 'Desc' :A new system should display a warning message that autoscan is required (1=required, 0=not required)
 	1,	// UserPrefScartRgbViaOverlay
 	INTERNAL_DAC_CVBS,	// ADCCalibrationMethod_CVBS
 	BAND_GAP,	// ADCCalibrationMethod_InternalDac
 	FALSE,	// AutoAspectRatio
 	INTERNAL_DAC_SCART,	// ADCCalibrationMethod_SCART
 	32,	// Reg_MHF_ENH_Y_LSHOOT_TOL 'Desc' :Horizontal Luma Large Edge Overshooting
 	32,	// Reg_MHF_ENH_Y_SSHOOT_TOL
 	32,	// Reg_MHF_ENH_Y_LGAIN
 	32,	// Reg_MHF_ENH_Y_SGAIN
 	32,	// Reg_MHF_ENH_Y_FINALSGAIN
 	32,	// Reg_MHF_ENH_Y_FINALLGAIN
 	32,	// Reg_MHF_ENH_Y_FINALGAIN
 	32,	// Reg_MHF_ENH_Y_DELTA
 	1,	// Reg_MHF_ENH_Y_SLOPE
 	32,	// Reg_MHF_ENH_Y_THRESH
 	1,	// Reg_MHF_ENH_Y_HIGH_SLOPE_AGC
 	1,	// Reg_MHF_ENH_Y_LOW_SLOPE_AGC
 	128,	// Reg_MHF_ENH_Y_HIGH_THRESH_AGC
 	32,	// Reg_MHF_ENH_Y_LOW_THRESH_AGC
 	12,	// Reg_MHF_ENH_UV_LSHOOT_TOL 'Desc' :Horizontal Chroma Large Edge Overshooting
 	12,	// Reg_MHF_ENH_UV_SSHOOT_TOL
 	128,	// Reg_MHF_ENH_UV_LGAIN
 	128,	// Reg_MHF_ENH_UV_SGAIN
 	64,	// Reg_MHF_ENH_UV_FINALSGAIN
 	64,	// Reg_MHF_ENH_UV_FINALLGAIN
 	64,	// Reg_MHF_ENH_UV_FINALGAIN
 	32,	// Reg_MHF_ENH_UV_DELTA
 	1,	// Reg_MHF_ENH_UV_SLOPE
 	32,	// Reg_MHF_ENH_UV_THRESH
 	1,	// Reg_MHF_ENH_UV_HIGH_SLOPE_AGC
 	1,	// Reg_MHF_ENH_UV_LOW_SLOPE_AGC
 	128,	// Reg_MHF_ENH_UV_HIGH_THRESH_AGC
 	32,	// Reg_MHF_ENH_UV_LOW_THRESH_AGC
 	32,	// Reg_MVF_ENH_Y_LSHOOT_TOL 'Desc' :Vertical Luma Large Edge Overshooting
 	32,	// Reg_MVF_ENH_Y_SSHOOT_TOL
 	32,	// Reg_MVF_ENH_Y_LGAIN
 	32,	// Reg_MVF_ENH_Y_SGAIN
 	32,	// Reg_MVF_ENH_Y_FINALSGAIN
 	32,	// Reg_MVF_ENH_Y_FINALLGAIN
 	32,	// Reg_MVF_ENH_Y_FINALGAIN
 	32,	// Reg_MVF_ENH_Y_DELTA
 	1,	// Reg_MVF_ENH_Y_SLOPE
 	32,	// Reg_MVF_ENH_Y_THRESH
 	1,	// Reg_MVF_ENH_Y_HIGH_SLOPE_AGC
 	1,	// Reg_MVF_ENH_Y_LOW_SLOPE_AGC
 	128,	// Reg_MVF_ENH_Y_HIGH_THRESH_AGC
 	32,	// Reg_MVF_ENH_Y_LOW_THRESH_AGC
 	12,	// Reg_MVF_ENH_UV_LSHOOT_TOL 'Desc' :Vertical Chroma Large Edge Overshooting
 	12,	// Reg_MVF_ENH_UV_SSHOOT_TOL
 	128,	// Reg_MVF_ENH_UV_LGAIN
 	128,	// Reg_MVF_ENH_UV_SGAIN
 	64,	// Reg_MVF_ENH_UV_FINALSGAIN
 	64,	// Reg_MVF_ENH_UV_FINALLGAIN
 	64,	// Reg_MVF_ENH_UV_FINALGAIN
 	32,	// Reg_MVF_ENH_UV_DELTA
 	1,	// Reg_MVF_ENH_UV_SLOPE
 	32,	// Reg_MVF_ENH_UV_THRESH
 	1,	// Reg_MVF_ENH_UV_HIGH_SLOPE_AGC
 	1,	// Reg_MVF_ENH_UV_LOW_SLOPE_AGC
 	128,	// Reg_MVF_ENH_UV_HIGH_THRESH_AGC
 	32,	// Reg_MVF_ENH_UV_LOW_THRESH_AGC
 	1,	// EnhancerEnable
 	0,	// OldEnhancerEnable 'Desc' :echeung:
	// Old Enhancer Menu On/Off
 	0,	// OldEnhancerRouting
 	0,	// ColorResourceRouting
 	INTERNAL_DAC_SIF_CALIB_OFF,	// ADCCalibrationMethod_SIF
 	0,	// ImpVlut
 	0,	// LineoutVariable 'Desc' :adjust Variable Volume
 	0,	// UserPrefGameFlag
 	0,	// UserPrefXvYcc
 	0,	// UserPrefDCRFlag
 	1,	// XNumber
 	1,	// YNumber
 	1,	// PublicDisplayNumber
 	0,	// AudioDownMix
 	ColorSpace_sRGB,	// ColorSpace
 	0,	// VwdFlag
 	0,	// VwdDemo
 	0,	// AudioMainInput
 	gmd_AUDIO_TAR_LINE_OUT,	// AudioMainOutput
 	0,	// OSD_G1_Blend
 	0,	// OSD_G2_Blend
 	0,	// OSD_G3_Blend
 	0,	// CaptureM
 	0,	// ImageRotation
 	0,	// OSD_4Kx2K_Port
 	1,	// DPSWitch
 	UART_TO_ATHENA_R,	// UARTSwitch
 	0,	// PBPMode
 	0	// OutputAspectRatio
 };

GlobalUserPrefType  GlobalUserPreferences =
{
	0,	// ParentalBlockStateFlagMain
 	0,	// ParentalBlockStateFlagPip
 	0,	// ChannelBlockStateFlag 'Desc' :Main TV Block  Status
 	0,	// ChannelBlockStateFlagPip 'Desc' :Pip TV Block  Status
 	{
		{ 32 },
		{ 32 },
		{ 32 },
		{ 32 },
		{ 32 },
		{ 32 },
		{ 32 },
		{ 32 }
	},
	0,	// Freeze
 	0,	// MultiPipStateFlag
 	0,	// OsdMPipHPos
 	0,	// OsdMPipVPos
 	0,	// OsdMPipChannel
 	0,	// SideBySideFocus
 	2,	// OSDBottomRightPos
 	255,	// OSDBottomPos
 	25,	// OSDCenterPos
 	0,	// OSDTopPos
 	0,	// ParentalMenuAccess
 	0,	// VChipPassword 'Desc' :used to store the vchip passwprd user has entered
 	1,	// Month
 	1,	// Date
 	0,	// Year
 	1,	// Hour
 	0,	// Min
 	0,	// AMPM
 	0,	// InfoDisplayOn 'Desc' :Flag to indicate if user pressed Info key
 	0,	// PrevPipSource
 	MINCHANNELFREQSLIDER,	// ChannelFreqSlider
 	MINCHANNELFREQVALUE,	// ChannelFreqValue
 	0,	// FactoryState
 	0,	// TempVar 'Desc' :This is a temporary variable that can be used by anyone
 	0,	// RegAddr
 	0,	// RegVal
 	0,	// PreviousPipMode
 	32,	// ChannelNameEntry1
 	32,	// ChannelNameEntry2
 	32,	// ChannelNameEntry3
 	32,	// ChannelNameEntry4
 	32,	// ChannelNameEntry5
 	0,	// PtrSegment
 	0,	// PtrOffset
 	{
		{ 1 },
		{ 2 },
		{ 3 },
		{ 4 },
		{ 5 },
		{ 6 },
		{ 7 },
		{ 8 },
		{ 9 },
		{ 10 }
	},
	{
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 }
	},
	0,	// ChannelNumDisplayFlag 'Desc' :Flag to indicate if the tv number should be displayed in the InfoDisplay_Dialog
 	0,	// ChannelNumAppendDisplayFlag 'Desc' :Flag to indicate if the tv number should be displayed in the InfoDisplay_Dialog
 	100,	// OsdScale100Percent
 	0,	// OsdFullScreenXPercent
 	0,	// OsdFullScreenYPercent
 	0,	// OsdState 'Desc' :0=default state
 	0,	// OsdBitFlags
 	0,	// CurrentBlockedTVRatingSubcodeMain
 	0,	// CurrentBlockedTVRatingSubcodePip
 	Column_One,	// MPipTileSet
 	0,	// ChipIDdigit1
 	0,	// ChipIDdigit2
 	0,	// ChipIDdigit3
 	0,	// ChipIDdigit4
 	0,	// ColorSystem
 	0,	// TtxNoSignalFlag
 	{
		{ 99 },
		{ 99 },
		{ 99 },
		{ 99 },
		{ 99 }
	},
	0,	// InputPortCount
 	0,	// DisplayPortName 'Desc' :Flag to indicate if to display port name only
 	0,	// OldOrNewPortChange
 	0,	// Str1_seg
 	0,	// Str2_seg
 	0,	// Str3_seg
 	0,	// Str4_seg
 	0,	// Str1_ofs
 	0,	// Str2_ofs
 	0,	// Str3_ofs
 	0,	// Str4_ofs
 	0,	// CecDeviceName_seg
 	0,	// CecDeviceName_ofs
 	0,	// CecDeviceType 'Desc' :Logical address of CEC device under control
 	0,	// DontRemoveOSD
 	0,	// CecRecordOnExtPlugNumber
 	0,	// CecDevicePowerStatus
 	0,	// CecStatusText1_seg
 	0,	// CecStatusText1_ofs
 	0,	// CecStatusText2_seg
 	0,	// CecStatusText2_ofs
 	0,	// CecStatusText3_seg
 	0,	// CecStatusText3_ofs
 	0,	// CecStatusLineCounter 'Desc' :line counter for CEC status strings
 	0,	// CecRecordDateDay 'Desc' :Day of month for CEC timer control feature
 	0,	// CecRecordDateMonth 'Desc' :Month of year for CEC timer control feature
 	0,	// CecRecordTimeHours 'Desc' :CEC timer control feature: time of record, hours
 	0,	// CecRecordTimeMinutes 'Desc' :CEC timer control feature: time of record, minutes
 	0,	// CecRecordDurationHours 'Desc' :CEC timer control feature: duration of record, hours
 	0,	// CecRecordDurationMinutes 'Desc' :CEC timer control feature: duration of record, minutes
 	0,	// CecHDMITreeMode 'Desc' :This variable serves as a label where to return after close HDMI tree dialog
 	0,	// CecDeviceSelectedFromHDMITree 'Desc' :result of selection from hdmi tree dialog
 	0,	// CecSystemAudioStatus 'Desc' :if 0 then sound outputs via TV speakers
	// if 1 then sound outputs via audio-receiver
 	0,	// IspWrPercent
 	0,	// InFwMajor
 	0,	// InFwMinor
 	0	// InFwRc
 };

ModeDependentUserPrefType  ModeDependentUserPreferences;

PortSchemeDependentUserPrefType  PortSchemeDependentUserPreferences;

gmt_OSD_ADJUSTERS_GROUP ROM gmv_OsdAdjustersGroupList[] =
{
	{ (void*) &ModeIndependentUserPreferences },
	{ (void*) &GlobalUserPreferences },
	{ (void*) &ModeDependentUserPreferences },
	{ (void*) &PortSchemeDependentUserPreferences }
};

BYTE ChannelNameDigit;
BYTE BlockedChannelList;
BYTE ADCOffsetGainList;
BYTE InputPortList;

gmt_OSD_ADJUSTERS_MODE_SWITCHERS ROM gmv_OsdAdjusterModeSwitchers[] =
{
	{ &ChannelNameDigit, 8 },
	{ &BlockedChannelList, 10 },
	{ &ADCOffsetGainList, 9 },
	{ &InputPortList, 5 }
};


