////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_UADJ_H_DEFINED
#define OSD_UADJ_H_DEFINED

#ifndef WB_NVRAM_STRUCTURE_VERSION
#define WB_NVRAM_STRUCTURE_VERSION		0x98bb
#endif //WB_NVRAM_STRUCTURE_VERSION

// gmv_OsdAdjusterFuncSet definition
#define Action_Adjust3DNR_WB_Used 
#define Action_AdjustAVSDelayOnOff_WB_Used 
#define Action_AdjustAcmBlackHue_WB_Used 
#define Action_AdjustAcmBlackLuma_WB_Used 
#define Action_AdjustAcmBlackSat_WB_Used 
#define Action_AdjustAcmBlueHue_WB_Used 
#define Action_AdjustAcmBlueLuma_WB_Used 
#define Action_AdjustAcmBlueSat_WB_Used 
#define Action_AdjustAcmCyanHue_WB_Used 
#define Action_AdjustAcmCyanLuma_WB_Used 
#define Action_AdjustAcmCyanSat_WB_Used 
#define Action_AdjustAcmGreenHue_WB_Used 
#define Action_AdjustAcmGreenLuma_WB_Used 
#define Action_AdjustAcmGreenSat_WB_Used 
#define Action_AdjustAcmMagentaHue_WB_Used 
#define Action_AdjustAcmMagentaLuma_WB_Used 
#define Action_AdjustAcmMagentaSat_WB_Used 
#define Action_AdjustAcmRedHue_WB_Used 
#define Action_AdjustAcmRedLuma_WB_Used 
#define Action_AdjustAcmRedSat_WB_Used 
#define Action_AdjustAcmWhiteHue_WB_Used 
#define Action_AdjustAcmWhiteLuma_WB_Used 
#define Action_AdjustAcmWhiteSat_WB_Used 
#define Action_AdjustAcmYellowHue_WB_Used 
#define Action_AdjustAcmYellowLuma_WB_Used 
#define Action_AdjustAcmYellowSat_WB_Used 
#define Action_AdjustAspectRatioMain_WB_Used 
#define Action_AdjustAspectRatioPip_WB_Used 
#define Action_AdjustAudio_WB_Used 
#define Action_AdjustAudioVolume_WB_Used 
#define Action_AdjustAutoAspectRatio_WB_Used 
#define Action_AdjustBackLight_WB_Used 
#define Action_AdjustBlueGain_WB_Used 
#define Action_AdjustBlueOff_WB_Used 
#define Action_AdjustBlueStretch_WB_Used 
#define Action_AdjustBrightness_WB_Used 
#define Action_AdjustCCS_WB_Used 
#define Action_AdjustCCSforHD_WB_Used 
#define Action_AdjustCaptureMain_WB_Used 
#define Action_AdjustColorDomain_WB_Used 
#define Action_AdjustColorResourceRouting_WB_Used 
#define Action_AdjustColorSpace_WB_Used 
#define Action_AdjustColorTemp_WB_Used 
#define Action_AdjustContrast_WB_Used 
#define Action_AdjustCurrentInputMain_WB_Used 
#define Action_AdjustCurrentInputPip_WB_Used 
#define Action_AdjustDCDiMain_WB_Used 
#define Action_AdjustDCDiPip_WB_Used 
#define Action_AdjustDPSwitch_WB_Used 
#define Action_AdjustDUMSwitch_WB_Used 
#define Action_AdjustDecoderAGCMethod_WB_Used 
#define Action_AdjustDynamicContrast_WB_Used 
#define Action_AdjustEnhancerEnable_WB_Used 
#define Action_AdjustFilmMode_WB_Used 
#define Action_AdjustFleshToneLevel_WB_Used 
#define Action_AdjustGammaCorrection_WB_Used 
#define Action_AdjustGreenGain_WB_Used 
#define Action_AdjustGreenOff_WB_Used 
#define Action_AdjustHEM_CE_GAIN_WB_Used 
#define Action_AdjustHEM_CE_THR_WB_Used 
#define Action_AdjustHEM_HDP_GAIN_WB_Used 
#define Action_AdjustHEM_HDP_THR_WB_Used 
#define Action_AdjustHEM_HLE_GAIN_WB_Used 
#define Action_AdjustHEM_HLE_THR_WB_Used 
#define Action_AdjustHStart_WB_Used 
#define Action_AdjustHSyncPhase_WB_Used 
#define Action_AdjustHTotal_WB_Used 
#define Action_AdjustHue_WB_Used 
#define Action_AdjustImageRotation_WB_Used 
#define Action_AdjustImageScheme_WB_Used 
#define Action_AdjustImpVlut_WB_Used 
#define Action_AdjustLCDOverdrive_WB_Used 
#define Action_AdjustLCDOverdriveNoiseCoring_WB_Used 
#define Action_AdjustLcdOverdriveSplit_WB_Used 
#define Action_AdjustMADI_WB_Used 
#define Action_AdjustMHF_NOISE_CORING_THRESH_WB_Used 
#define Action_AdjustMHF_NONLINEAR_GAIN1_WB_Used 
#define Action_AdjustMHF_NONLINEAR_GAIN2_WB_Used 
#define Action_AdjustMHF_NONLINEAR_THRESH1_WB_Used 
#define Action_AdjustMHF_NONLINEAR_THRESH2_WB_Used 
#define Action_AdjustMHF_SHARPNESS_CHROMA_WB_Used 
#define Action_AdjustMHF_SHARPNESS_LUMA_WB_Used 
#define Action_AdjustMPEGNR_WB_Used 
#define Action_AdjustMPEGNRMode_WB_Used 
#define Action_AdjustMPEGNRThresh_WB_Used 
#define Action_AdjustMVF_NOISE_CORING_THRESH_WB_Used 
#define Action_AdjustMVF_NONLINEAR_GAIN1_WB_Used 
#define Action_AdjustMVF_NONLINEAR_GAIN2_WB_Used 
#define Action_AdjustMVF_NONLINEAR_THRESH1_WB_Used 
#define Action_AdjustMVF_NONLINEAR_THRESH2_WB_Used 
#define Action_AdjustMVF_SHARPNESS_CHROMA_WB_Used 
#define Action_AdjustMVF_SHARPNESS_LUMA_WB_Used 
#define Action_AdjustNativeMode_WB_Used 
#define Action_AdjustNonACMFleshtoneBalance_WB_Used 
#define Action_AdjustNonACMFleshtoneCorrection_WB_Used 
#define Action_AdjustNonACMFleshtoneCorrectionLevel_WB_Used 
#define Action_AdjustOSDBlending_WB_Used 
#define Action_AdjustOSDBlending1_WB_Used 
#define Action_AdjustOSDBlending2_WB_Used 
#define Action_AdjustOldEnhancerEnable_WB_Used 
#define Action_AdjustOldEnhancerRouting_WB_Used 
#define Action_AdjustOsdHPosition_WB_Used 
#define Action_AdjustOsdLanguage_WB_Used 
#define Action_AdjustOsdVPosition_WB_Used 
#define Action_AdjustPHF_NOISE_CORING_THRESH_WB_Used 
#define Action_AdjustPHF_NONLINEAR_GAIN1_WB_Used 
#define Action_AdjustPHF_NONLINEAR_GAIN2_WB_Used 
#define Action_AdjustPHF_NONLINEAR_THRESH1_WB_Used 
#define Action_AdjustPHF_NONLINEAR_THRESH2_WB_Used 
#define Action_AdjustPHF_SHARPNESS_CHROMA_WB_Used 
#define Action_AdjustPHF_SHARPNESS_LUMA_WB_Used 
#define Action_AdjustPVF_NOISE_CORING_THRESH_WB_Used 
#define Action_AdjustPVF_NONLINEAR_GAIN1_WB_Used 
#define Action_AdjustPVF_NONLINEAR_GAIN2_WB_Used 
#define Action_AdjustPVF_NONLINEAR_THRESH1_WB_Used 
#define Action_AdjustPVF_NONLINEAR_THRESH2_WB_Used 
#define Action_AdjustPVF_SHARPNESS_CHROMA_WB_Used 
#define Action_AdjustPVF_SHARPNESS_LUMA_WB_Used 
#define Action_AdjustPipMode_WB_Used 
#define Action_AdjustPipPosition_WB_Used 
#define Action_AdjustRedGain_WB_Used 
#define Action_AdjustRedOff_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_DELTA_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_FINALGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_FINALLGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_FINALSGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_HIGH_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_HIGH_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_LGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_LOW_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_LOW_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_LSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_SGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_SLOPE_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_SSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MHF_ENH_UV_THRESH_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_DELTA_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_FINALGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_FINALLGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_FINALSGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_HIGH_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_HIGH_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_LGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_LOW_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_LOW_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_LSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_SGAIN_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_SLOPE_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_SSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MHF_ENH_Y_THRESH_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_DELTA_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_FINALGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_FINALLGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_FINALSGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_HIGH_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_HIGH_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_LGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_LOW_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_LOW_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_LSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_SGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_SLOPE_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_SSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MVF_ENH_UV_THRESH_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_DELTA_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_FINALGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_FINALLGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_FINALSGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_HIGH_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_HIGH_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_LGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_LOW_SLOPE_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_LOW_THRESH_AGC_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_LSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_SGAIN_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_SLOPE_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_SSHOOT_TOL_WB_Used 
#define Action_AdjustReg_MVF_ENH_Y_THRESH_WB_Used 
#define Action_AdjustSaturation_WB_Used 
#define Action_AdjustScartRGBViaOverlay_WB_Used 
#define Action_AdjustSharpNoise_WB_Used 
#define Action_AdjustSharpness_WB_Used 
#define Action_AdjustSharpnessRGB_WB_Used 
#define Action_AdjustSplitScreen_WB_Used 
#define Action_AdjustTNR_WB_Used 
#define Action_AdjustTTXLanguageGroup_WB_Used 
#define Action_AdjustThreeTwoFilmDisplayMode_WB_Used 
#define Action_AdjustTwoStageProcessing_WB_Used 
#define Action_AdjustVBIService_WB_Used 
#define Action_AdjustVDP_GAIN_WB_Used 
#define Action_AdjustVDP_THRESHOLD_WB_Used 
#define Action_AdjustVStart_WB_Used 
#define Action_AdjustYUV2RGBExpansionMode_WB_Used 
#define Action_FactoryAdjustADCValues_WB_Used 
#define Action_OsdBlend_WB_Used 
#define Action_SetOsdTimeout_WB_Used 
#define Action_VWD_ApplyHighLightWindow_WB_Used 
#define Action_VWD_Switch_WB_Used 


typedef enum 
{
	ADJID_NULL = 0,
	ADJID_Adjust3DNR,
	ADJID_AdjustAVSDelayOnOff,
	ADJID_AdjustAcmBlackHue,
	ADJID_AdjustAcmBlackLuma,
	ADJID_AdjustAcmBlackSat,
	ADJID_AdjustAcmBlueHue,
	ADJID_AdjustAcmBlueLuma,
	ADJID_AdjustAcmBlueSat,
	ADJID_AdjustAcmCyanHue,
	ADJID_AdjustAcmCyanLuma,
	ADJID_AdjustAcmCyanSat,
	ADJID_AdjustAcmGreenHue,
	ADJID_AdjustAcmGreenLuma,
	ADJID_AdjustAcmGreenSat,
	ADJID_AdjustAcmMagentaHue,
	ADJID_AdjustAcmMagentaLuma,
	ADJID_AdjustAcmMagentaSat,
	ADJID_AdjustAcmRedHue,
	ADJID_AdjustAcmRedLuma,
	ADJID_AdjustAcmRedSat,
	ADJID_AdjustAcmWhiteHue,
	ADJID_AdjustAcmWhiteLuma,
	ADJID_AdjustAcmWhiteSat,
	ADJID_AdjustAcmYellowHue,
	ADJID_AdjustAcmYellowLuma,
	ADJID_AdjustAcmYellowSat,
	ADJID_AdjustAspectRatioMain,
	ADJID_AdjustAspectRatioPip,
	ADJID_AdjustAudio,
	ADJID_AdjustAudioVolume,
	ADJID_AdjustAutoAspectRatio,
	ADJID_AdjustBackLight,
	ADJID_AdjustBlueGain,
	ADJID_AdjustBlueOff,
	ADJID_AdjustBlueStretch,
	ADJID_AdjustBrightness,
	ADJID_AdjustCCS,
	ADJID_AdjustCCSforHD,
	ADJID_AdjustCaptureMain,
	ADJID_AdjustColorDomain,
	ADJID_AdjustColorResourceRouting,
	ADJID_AdjustColorSpace,
	ADJID_AdjustColorTemp,
	ADJID_AdjustContrast,
	ADJID_AdjustCurrentInputMain,
	ADJID_AdjustCurrentInputPip,
	ADJID_AdjustDCDiMain,
	ADJID_AdjustDCDiPip,
	ADJID_AdjustDPSwitch,
	ADJID_AdjustDUMSwitch,
	ADJID_AdjustDecoderAGCMethod,
	ADJID_AdjustDynamicContrast,
	ADJID_AdjustEnhancerEnable,
	ADJID_AdjustFilmMode,
	ADJID_AdjustFleshToneLevel,
	ADJID_AdjustGammaCorrection,
	ADJID_AdjustGreenGain,
	ADJID_AdjustGreenOff,
	ADJID_AdjustHEM_CE_GAIN,
	ADJID_AdjustHEM_CE_THR,
	ADJID_AdjustHEM_HDP_GAIN,
	ADJID_AdjustHEM_HDP_THR,
	ADJID_AdjustHEM_HLE_GAIN,
	ADJID_AdjustHEM_HLE_THR,
	ADJID_AdjustHStart,
	ADJID_AdjustHSyncPhase,
	ADJID_AdjustHTotal,
	ADJID_AdjustHue,
	ADJID_AdjustImageRotation,
	ADJID_AdjustImageScheme,
	ADJID_AdjustImpVlut,
	ADJID_AdjustLCDOverdrive,
	ADJID_AdjustLCDOverdriveNoiseCoring,
	ADJID_AdjustLcdOverdriveSplit,
	ADJID_AdjustMADI,
	ADJID_AdjustMHF_NOISE_CORING_THRESH,
	ADJID_AdjustMHF_NONLINEAR_GAIN1,
	ADJID_AdjustMHF_NONLINEAR_GAIN2,
	ADJID_AdjustMHF_NONLINEAR_THRESH1,
	ADJID_AdjustMHF_NONLINEAR_THRESH2,
	ADJID_AdjustMHF_SHARPNESS_CHROMA,
	ADJID_AdjustMHF_SHARPNESS_LUMA,
	ADJID_AdjustMPEGNR,
	ADJID_AdjustMPEGNRMode,
	ADJID_AdjustMPEGNRThresh,
	ADJID_AdjustMVF_NOISE_CORING_THRESH,
	ADJID_AdjustMVF_NONLINEAR_GAIN1,
	ADJID_AdjustMVF_NONLINEAR_GAIN2,
	ADJID_AdjustMVF_NONLINEAR_THRESH1,
	ADJID_AdjustMVF_NONLINEAR_THRESH2,
	ADJID_AdjustMVF_SHARPNESS_CHROMA,
	ADJID_AdjustMVF_SHARPNESS_LUMA,
	ADJID_AdjustNativeMode,
	ADJID_AdjustNonACMFleshtoneBalance,
	ADJID_AdjustNonACMFleshtoneCorrection,
	ADJID_AdjustNonACMFleshtoneCorrectionLevel,
	ADJID_AdjustOSDBlending,
	ADJID_AdjustOSDBlending1,
	ADJID_AdjustOSDBlending2,
	ADJID_AdjustOldEnhancerEnable,
	ADJID_AdjustOldEnhancerRouting,
	ADJID_AdjustOsdHPosition,
	ADJID_AdjustOsdLanguage,
	ADJID_AdjustOsdVPosition,
	ADJID_AdjustPHF_NOISE_CORING_THRESH,
	ADJID_AdjustPHF_NONLINEAR_GAIN1,
	ADJID_AdjustPHF_NONLINEAR_GAIN2,
	ADJID_AdjustPHF_NONLINEAR_THRESH1,
	ADJID_AdjustPHF_NONLINEAR_THRESH2,
	ADJID_AdjustPHF_SHARPNESS_CHROMA,
	ADJID_AdjustPHF_SHARPNESS_LUMA,
	ADJID_AdjustPVF_NOISE_CORING_THRESH,
	ADJID_AdjustPVF_NONLINEAR_GAIN1,
	ADJID_AdjustPVF_NONLINEAR_GAIN2,
	ADJID_AdjustPVF_NONLINEAR_THRESH1,
	ADJID_AdjustPVF_NONLINEAR_THRESH2,
	ADJID_AdjustPVF_SHARPNESS_CHROMA,
	ADJID_AdjustPVF_SHARPNESS_LUMA,
	ADJID_AdjustPipMode,
	ADJID_AdjustPipPosition,
	ADJID_AdjustRedGain,
	ADJID_AdjustRedOff,
	ADJID_AdjustReg_MHF_ENH_UV_DELTA,
	ADJID_AdjustReg_MHF_ENH_UV_FINALGAIN,
	ADJID_AdjustReg_MHF_ENH_UV_FINALLGAIN,
	ADJID_AdjustReg_MHF_ENH_UV_FINALSGAIN,
	ADJID_AdjustReg_MHF_ENH_UV_HIGH_SLOPE_AGC,
	ADJID_AdjustReg_MHF_ENH_UV_HIGH_THRESH_AGC,
	ADJID_AdjustReg_MHF_ENH_UV_LGAIN,
	ADJID_AdjustReg_MHF_ENH_UV_LOW_SLOPE_AGC,
	ADJID_AdjustReg_MHF_ENH_UV_LOW_THRESH_AGC,
	ADJID_AdjustReg_MHF_ENH_UV_LSHOOT_TOL,
	ADJID_AdjustReg_MHF_ENH_UV_SGAIN,
	ADJID_AdjustReg_MHF_ENH_UV_SLOPE,
	ADJID_AdjustReg_MHF_ENH_UV_SSHOOT_TOL,
	ADJID_AdjustReg_MHF_ENH_UV_THRESH,
	ADJID_AdjustReg_MHF_ENH_Y_DELTA,
	ADJID_AdjustReg_MHF_ENH_Y_FINALGAIN,
	ADJID_AdjustReg_MHF_ENH_Y_FINALLGAIN,
	ADJID_AdjustReg_MHF_ENH_Y_FINALSGAIN,
	ADJID_AdjustReg_MHF_ENH_Y_HIGH_SLOPE_AGC,
	ADJID_AdjustReg_MHF_ENH_Y_HIGH_THRESH_AGC,
	ADJID_AdjustReg_MHF_ENH_Y_LGAIN,
	ADJID_AdjustReg_MHF_ENH_Y_LOW_SLOPE_AGC,
	ADJID_AdjustReg_MHF_ENH_Y_LOW_THRESH_AGC,
	ADJID_AdjustReg_MHF_ENH_Y_LSHOOT_TOL,
	ADJID_AdjustReg_MHF_ENH_Y_SGAIN,
	ADJID_AdjustReg_MHF_ENH_Y_SLOPE,
	ADJID_AdjustReg_MHF_ENH_Y_SSHOOT_TOL,
	ADJID_AdjustReg_MHF_ENH_Y_THRESH,
	ADJID_AdjustReg_MVF_ENH_UV_DELTA,
	ADJID_AdjustReg_MVF_ENH_UV_FINALGAIN,
	ADJID_AdjustReg_MVF_ENH_UV_FINALLGAIN,
	ADJID_AdjustReg_MVF_ENH_UV_FINALSGAIN,
	ADJID_AdjustReg_MVF_ENH_UV_HIGH_SLOPE_AGC,
	ADJID_AdjustReg_MVF_ENH_UV_HIGH_THRESH_AGC,
	ADJID_AdjustReg_MVF_ENH_UV_LGAIN,
	ADJID_AdjustReg_MVF_ENH_UV_LOW_SLOPE_AGC,
	ADJID_AdjustReg_MVF_ENH_UV_LOW_THRESH_AGC,
	ADJID_AdjustReg_MVF_ENH_UV_LSHOOT_TOL,
	ADJID_AdjustReg_MVF_ENH_UV_SGAIN,
	ADJID_AdjustReg_MVF_ENH_UV_SLOPE,
	ADJID_AdjustReg_MVF_ENH_UV_SSHOOT_TOL,
	ADJID_AdjustReg_MVF_ENH_UV_THRESH,
	ADJID_AdjustReg_MVF_ENH_Y_DELTA,
	ADJID_AdjustReg_MVF_ENH_Y_FINALGAIN,
	ADJID_AdjustReg_MVF_ENH_Y_FINALLGAIN,
	ADJID_AdjustReg_MVF_ENH_Y_FINALSGAIN,
	ADJID_AdjustReg_MVF_ENH_Y_HIGH_SLOPE_AGC,
	ADJID_AdjustReg_MVF_ENH_Y_HIGH_THRESH_AGC,
	ADJID_AdjustReg_MVF_ENH_Y_LGAIN,
	ADJID_AdjustReg_MVF_ENH_Y_LOW_SLOPE_AGC,
	ADJID_AdjustReg_MVF_ENH_Y_LOW_THRESH_AGC,
	ADJID_AdjustReg_MVF_ENH_Y_LSHOOT_TOL,
	ADJID_AdjustReg_MVF_ENH_Y_SGAIN,
	ADJID_AdjustReg_MVF_ENH_Y_SLOPE,
	ADJID_AdjustReg_MVF_ENH_Y_SSHOOT_TOL,
	ADJID_AdjustReg_MVF_ENH_Y_THRESH,
	ADJID_AdjustSaturation,
	ADJID_AdjustScartRGBViaOverlay,
	ADJID_AdjustSharpNoise,
	ADJID_AdjustSharpness,
	ADJID_AdjustSharpnessRGB,
	ADJID_AdjustSplitScreen,
	ADJID_AdjustTNR,
	ADJID_AdjustTTXLanguageGroup,
	ADJID_AdjustThreeTwoFilmDisplayMode,
	ADJID_AdjustTwoStageProcessing,
	ADJID_AdjustVBIService,
	ADJID_AdjustVDP_GAIN,
	ADJID_AdjustVDP_THRESHOLD,
	ADJID_AdjustVStart,
	ADJID_AdjustYUV2RGBExpansionMode,
	ADJID_FactoryAdjustADCValues,
	ADJID_OsdBlend,
	ADJID_SetOsdTimeout,
	ADJID_VWD_ApplyHighLightWindow,
	ADJID_VWD_Switch
} AdjFuncEnum;

extern BYTE ROM * ROM gmv_OsdAdjusterFuncSet[199];

// gmv_OsdMinMaxFuncSet definition
typedef enum 
{
	EXTRID_MaxDisplayNumber = 0,
	EXTRID_MaxHStart,
	EXTRID_MaxHTotal,
	EXTRID_MaxVStart,
	EXTRID_MinHStart,
	EXTRID_MinHTotal,
	EXTRID_MinVStart
} ExtrFuncEnum;

extern BYTE ROM * ROM gmv_OsdMinMaxFuncSet[7];

// gmv_OsdStepFuncSet definition
typedef enum 
{
	SFID_BallisticAcceleration = 0
} StepFuncEnum;

extern BYTE ROM * ROM gmv_OsdStepFuncSet[1];

extern WORD ROM gmc_AdjvNullValue;

typedef enum 
{
	ADJV_TNR = 0,
	ADJV_MADI = 10,
	ADJV_CCS = 20,
	ADJV_SharpNoise = 30,
	ADJV_SplitScreen = 40,
	ADJV_DCDiMain = 50,
	ADJV_DCDiPip = 60,
	ADJV_MPEGNRMode = 70,
	ADJV_MPEGNRThresh0 = 80,
	ADJV_MPEGNRThresh1 = 90,
	ADJV_MPEGNRThresh2 = 100,
	ADJV_LCDOverdriveNoiseCoring = 110,
	ADJV_ThreeTwoFilmDisplayMode = 120,
	ADJV_VBI_ServicePreferred = 130,
	ADJV_SharpnessPip = 140,
	ADJV_BlueStretch = 150,
	ADJV_SharpnessRGB = 160,
	ADJV_SharpnessRGBpip = 170,
	ADJV_AVSDelay = 180,
	ADJV_AudioVolume = 190,
	ADJV_ADCCalibrationMethod_Comp = 200,
	ADJV_ADCCalibrationMethod_VGA = 210,
	ADJV_AspectRatioMain = 220,
	ADJV_AspectRatioPip = 230,
	ADJV_CurrentInputMain = 240,
	ADJV_CurrentInputPip = 250,
	ADJV_DynamicContrast = 260,
	ADJV_FilmMode = 270,
	ADJV_FleshToneComp = 280,
	ADJV_ImageScheme = 290,
	ADJV_LCDOverdrive = 300,
	ADJV_LetterboxEnable = 310,
	ADJV_MPEGNR = 320,
	ADJV_OsdHPosition = 330,
	ADJV_OsdLanguage = 340,
	ADJV_OsdRotation = 350,
	ADJV_OsdTimeout = 360,
	ADJV_OsdVPosition = 370,
	ADJV_OverscanEnable = 380,
	ADJV_PanelSelect = 390,
	ADJV_PipMode = 400,
	ADJV_PipPosition = 410,
	ADJV_PowerState = 420,
	ADJV_Sharpness = 430,
	ADJV_SleepAMPM = 440,
	ADJV_SleepDay = 450,
	ADJV_SleepHour = 460,
	ADJV_SleepMin = 470,
	ADJV_SleepMinsLeft = 480,
	ADJV_ThreeDNR = 490,
	ADJV_TVRating = 500,
	ADJV_TVUnrated = 510,
	ADJV_Version = 520,
	ADJV_WakeAMPM = 530,
	ADJV_WakeDay = 540,
	ADJV_WakeHour = 550,
	ADJV_WakeMin = 560,
	ADJV_MPRating = 570,
	ADJV_AVSDelayTime = 580,
	ADJV_CC_On = 590,
	ADJV_AudioMute = 600,
	ADJV_MPipConfig = 610,
	ADJV_OSDSplashScreen = 620,
	ADJV_ParentalPassword = 630,
	ADJV_PipSize = 640,
	ADJV_PreviousInputMain = 650,
	ADJV_ScrollMenuItem = 660,
	ADJV_SplitLcdOverdrive = 670,
	ADJV_TTXLanguageGroup = 680,
	ADJV_MainRouteModeComponent = 690,
	ADJV_MainRouteModeScartRGB = 700,
	ADJV_PipRouteModeComponent = 710,
	ADJV_PipRouteModeScartRGB = 720,
	ADJV_Reg_MVF_SHARPNESS_LUMA = 730,
	ADJV_Reg_MVF_SHARPNESS_CHROMA = 740,
	ADJV_Reg_MVF_NOISE_CORING_THRESH = 750,
	ADJV_Reg_MVF_NONLINEAR_THRESH1 = 760,
	ADJV_Reg_MVF_NONLINEAR_GAIN1 = 770,
	ADJV_Reg_MVF_NONLINEAR_THRESH2 = 780,
	ADJV_Reg_MVF_NONLINEAR_GAIN2 = 790,
	ADJV_Reg_MHF_SHARPNESS_LUMA = 800,
	ADJV_Reg_MHF_SHARPNESS_CHROMA = 810,
	ADJV_Reg_MHF_NOISE_CORING_THRESH = 820,
	ADJV_Reg_MHF_NONLINEAR_THRESH1 = 830,
	ADJV_Reg_MHF_NONLINEAR_GAIN1 = 840,
	ADJV_Reg_MHF_NONLINEAR_THRESH2 = 850,
	ADJV_Reg_MHF_NONLINEAR_GAIN2 = 860,
	ADJV_Reg_PVF_SHARPNESS_LUMA = 870,
	ADJV_Reg_PVF_SHARPNESS_CHROMA = 880,
	ADJV_Reg_PVF_NOISE_CORING_THRESH = 890,
	ADJV_Reg_PVF_NONLINEAR_THRESH1 = 900,
	ADJV_Reg_PVF_NONLINEAR_GAIN1 = 910,
	ADJV_Reg_PVF_NONLINEAR_THRESH2 = 920,
	ADJV_Reg_PVF_NONLINEAR_GAIN2 = 930,
	ADJV_Reg_PHF_SHARPNESS_LUMA = 940,
	ADJV_Reg_PHF_SHARPNESS_CHROMA = 950,
	ADJV_Reg_PHF_NOISE_CORING_THRESH = 960,
	ADJV_Reg_PHF_NONLINEAR_THRESH1 = 970,
	ADJV_Reg_PHF_NONLINEAR_GAIN1 = 980,
	ADJV_Reg_PHF_NONLINEAR_THRESH2 = 990,
	ADJV_Reg_PHF_NONLINEAR_GAIN2 = 1000,
	ADJV_Reg_HEM_HLE_THR = 1010,
	ADJV_Reg_HEM_HLE_GAIN = 1020,
	ADJV_Reg_HEM_HDP_THR = 1030,
	ADJV_Reg_HEM_HDP_GAIN = 1040,
	ADJV_Reg_HEM_CE_THR = 1050,
	ADJV_Reg_HEM_CE_GAIN = 1060,
	ADJV_Reg_VDP_THRESHOLD = 1070,
	ADJV_Reg_VDP_GAIN = 1080,
	ADJV_NativeMode = 1090,
	ADJV_YUV2RGBExpansionMode = 1100,
	ADJV_NonACMFleshtoneCorrection = 1110,
	ADJV_NonACMFleshtoneBalance = 1120,
	ADJV_NonACMFleshtoneCorrectionLevel = 1130,
	ADJV_TVYouth7Subcode = 1140,
	ADJV_TVPGSubcode = 1150,
	ADJV_TV14Subcode = 1160,
	ADJV_TVMASubcode = 1170,
	ADJV_DecoderAGCMethod = 1180,
	ADJV_CCSforHD = 1190,
	ADJV_TwoStageProcessing = 1200,
	ADJV_ManualTVMHzFreq = 1210,
	ADJV_ManualTVkHzFreq = 1220,
	ADJV_TVFreqFineTune = 1230,
	ADJV_TVManualScanRequired = 1240,
	ADJV_ScartRgbViaOverlay = 1250,
	ADJV_ADCCalibrationMethod_CVBS = 1260,
	ADJV_ADCCalibrationMethod_InternalDac = 1270,
	ADJV_AutoAspectRatio = 1280,
	ADJV_ADCCalibrationMethod_SCART = 1290,
	ADJV_Reg_MHF_ENH_Y_LSHOOT_TOL = 1300,
	ADJV_Reg_MHF_ENH_Y_SSHOOT_TOL = 1310,
	ADJV_Reg_MHF_ENH_Y_LGAIN = 1320,
	ADJV_Reg_MHF_ENH_Y_SGAIN = 1330,
	ADJV_Reg_MHF_ENH_Y_FINALSGAIN = 1340,
	ADJV_Reg_MHF_ENH_Y_FINALLGAIN = 1350,
	ADJV_Reg_MHF_ENH_Y_FINALGAIN = 1360,
	ADJV_Reg_MHF_ENH_Y_DELTA = 1370,
	ADJV_Reg_MHF_ENH_Y_SLOPE = 1380,
	ADJV_Reg_MHF_ENH_Y_THRESH = 1390,
	ADJV_Reg_MHF_ENH_Y_HIGH_SLOPE_AGC = 1400,
	ADJV_Reg_MHF_ENH_Y_LOW_SLOPE_AGC = 1410,
	ADJV_Reg_MHF_ENH_Y_HIGH_THRESH_AGC = 1420,
	ADJV_Reg_MHF_ENH_Y_LOW_THRESH_AGC = 1430,
	ADJV_Reg_MHF_ENH_UV_LSHOOT_TOL = 1440,
	ADJV_Reg_MHF_ENH_UV_SSHOOT_TOL = 1450,
	ADJV_Reg_MHF_ENH_UV_LGAIN = 1460,
	ADJV_Reg_MHF_ENH_UV_SGAIN = 1470,
	ADJV_Reg_MHF_ENH_UV_FINALSGAIN = 1480,
	ADJV_Reg_MHF_ENH_UV_FINALLGAIN = 1490,
	ADJV_Reg_MHF_ENH_UV_FINALGAIN = 1500,
	ADJV_Reg_MHF_ENH_UV_DELTA = 1510,
	ADJV_Reg_MHF_ENH_UV_SLOPE = 1520,
	ADJV_Reg_MHF_ENH_UV_THRESH = 1530,
	ADJV_Reg_MHF_ENH_UV_HIGH_SLOPE_AGC = 1540,
	ADJV_Reg_MHF_ENH_UV_LOW_SLOPE_AGC = 1550,
	ADJV_Reg_MHF_ENH_UV_HIGH_THRESH_AGC = 1560,
	ADJV_Reg_MHF_ENH_UV_LOW_THRESH_AGC = 1570,
	ADJV_Reg_MVF_ENH_Y_LSHOOT_TOL = 1580,
	ADJV_Reg_MVF_ENH_Y_SSHOOT_TOL = 1590,
	ADJV_Reg_MVF_ENH_Y_LGAIN = 1600,
	ADJV_Reg_MVF_ENH_Y_SGAIN = 1610,
	ADJV_Reg_MVF_ENH_Y_FINALSGAIN = 1620,
	ADJV_Reg_MVF_ENH_Y_FINALLGAIN = 1630,
	ADJV_Reg_MVF_ENH_Y_FINALGAIN = 1640,
	ADJV_Reg_MVF_ENH_Y_DELTA = 1650,
	ADJV_Reg_MVF_ENH_Y_SLOPE = 1660,
	ADJV_Reg_MVF_ENH_Y_THRESH = 1670,
	ADJV_Reg_MVF_ENH_Y_HIGH_SLOPE_AGC = 1680,
	ADJV_Reg_MVF_ENH_Y_LOW_SLOPE_AGC = 1690,
	ADJV_Reg_MVF_ENH_Y_HIGH_THRESH_AGC = 1700,
	ADJV_Reg_MVF_ENH_Y_LOW_THRESH_AGC = 1710,
	ADJV_Reg_MVF_ENH_UV_LSHOOT_TOL = 1720,
	ADJV_Reg_MVF_ENH_UV_SSHOOT_TOL = 1730,
	ADJV_Reg_MVF_ENH_UV_LGAIN = 1740,
	ADJV_Reg_MVF_ENH_UV_SGAIN = 1750,
	ADJV_Reg_MVF_ENH_UV_FINALSGAIN = 1760,
	ADJV_Reg_MVF_ENH_UV_FINALLGAIN = 1770,
	ADJV_Reg_MVF_ENH_UV_FINALGAIN = 1780,
	ADJV_Reg_MVF_ENH_UV_DELTA = 1790,
	ADJV_Reg_MVF_ENH_UV_SLOPE = 1800,
	ADJV_Reg_MVF_ENH_UV_THRESH = 1810,
	ADJV_Reg_MVF_ENH_UV_HIGH_SLOPE_AGC = 1820,
	ADJV_Reg_MVF_ENH_UV_LOW_SLOPE_AGC = 1830,
	ADJV_Reg_MVF_ENH_UV_HIGH_THRESH_AGC = 1840,
	ADJV_Reg_MVF_ENH_UV_LOW_THRESH_AGC = 1850,
	ADJV_EnhancerEnable = 1860,
	ADJV_OldEnhancerEnable = 1870,
	ADJV_OldEnhancerRouting = 1880,
	ADJV_ColorResourceRouting = 1890,
	ADJV_ADCCalibrationMethod_SIF = 1900,
	ADJV_ImpVlut = 1910,
	ADJV_VariableForLineout = 1920,
	ADJV_GameMode = 1930,
	ADJV_XvYcc = 1940,
	ADJV_DCR = 1950,
	ADJV_XNumber = 1960,
	ADJV_YNumber = 1970,
	ADJV_PublicDisplayNumber = 1980,
	ADJV_AudioDownMix = 1990,
	ADJV_ColorSpace = 2000,
	ADJV_VwdFlag = 2010,
	ADJV_VwdDemo = 2020,
	ADJV_AudioMainInput = 2030,
	ADJV_AudioMainOutput = 2040,
	ADJV_AudioPipInput = 2050,
	ADJV_AudioPipOutput = 2060,
	ADJV_OSDG1Blend = 2070,
	ADJV_OSDG2Blend = 2080,
	ADJV_OSDG3Blend = 2090,
	ADJV_CaptureM = 2100,
	ADJV_ImageRotation = 2110,
	ADJV_OSD_4Kx2K_Port = 2120,
	ADJV_DPSWitch = 2130,
	ADJV_BackLight = 2140,
	ADJV_OsdBlend = 2150,
	ADJV_FanStatus = 2160,
	ADJV_PIPHPos = 2170,
	ADJV_PIPVPos = 2180,
	ADJV_PipModeOnOff = 2190,
	ADJV_ScheduleOnOff = 2200,
	ADJV_OverScan = 2210,
	ADJV_AutoBLState = 2220,
	ADJV_MinBrightness = 2230,
	ADJV_AUTOADJUST = 2240,
	ADJV_DisplayPos = 2250,
	ADJV_ParentalBlockStateFlagMain = 2260,
	ADJV_ParentalBlockStateFlagPip = 2270,
	ADJV_ChannelBlockStateFlag = 2280,
	ADJV_ChannelBlockStateFlagPip = 2290,
	ADJV_ChannelName = 2300,
	ADJV_Digit1ChannelName = 2302,
	ADJV_Digit2ChannelName = 2312,
	ADJV_Digit3ChannelName = 2322,
	ADJV_Digit4ChannelName = 2332,
	ADJV_Digit5ChannelName = 2342,
	ADJV_Digit6ChannelName = 2352,
	ADJV_Digit7ChannelName = 2362,
	ADJV_Digit8ChannelName = 2372,
	ADJV_Freeze = 2382,
	ADJV_MultiPipStateFlag = 2392,
	ADJV_OsdMPipHPos = 2402,
	ADJV_OsdMPipVPos = 2412,
	ADJV_OsdMPipChannel = 2422,
	ADJV_SideBySideFocus = 2432,
	ADJV_OSDBottomPos = 2442,
	ADJV_OSDCenterPos = 2452,
	ADJV_ParentalMenuAccess = 2462,
	ADJV_VChipPassword = 2472,
	ADJV_Month = 2482,
	ADJV_Date = 2492,
	ADJV_Year = 2502,
	ADJV_Hour = 2512,
	ADJV_Min = 2522,
	ADJV_AMPM = 2532,
	ADJV_InfoDisplayOn = 2542,
	ADJV_PrevPipSource = 2552,
	ADJV_ChannelFreqSlider = 2562,
	ADJV_ChannelFreqValue = 2572,
	ADJV_FactoryState = 2582,
	ADJV_TempVar = 2592,
	ADJV_RegAddr = 2602,
	ADJV_RegVal = 2612,
	ADJV_PreviousPipMode = 2622,
	ADJV_ChannelNameEntry1 = 2632,
	ADJV_ChannelNameEntry2 = 2642,
	ADJV_ChannelNameEntry3 = 2652,
	ADJV_ChannelNameEntry4 = 2662,
	ADJV_ChannelNameEntry5 = 2672,
	ADJV_PtrSegment = 2682,
	ADJV_PtrOffset = 2692,
	ADJV_BlockedChannelList = 2702,
	ADJV_BlockedChannel_1BlockedChannelList = 2704,
	ADJV_BlockedChannel_2BlockedChannelList = 2714,
	ADJV_BlockedChannel_3BlockedChannelList = 2724,
	ADJV_BlockedChannel_4BlockedChannelList = 2734,
	ADJV_BlockedChannel_5BlockedChannelList = 2744,
	ADJV_BlockedChannel_6BlockedChannelList = 2754,
	ADJV_BlockedChannel_7BlockedChannelList = 2764,
	ADJV_BlockedChannel_8BlockedChannelList = 2774,
	ADJV_BlockedChannel_9BlockedChannelList = 2784,
	ADJV_BlockedChannel_10BlockedChannelList = 2794,
	ADJV_OffsetGain = 2804,
	ADJV_Offset1_1OffsetGain = 2806,
	ADJV_Offset1_2OffsetGain = 2816,
	ADJV_Offset1_3OffsetGain = 2826,
	ADJV_Offset2_1OffsetGain = 2836,
	ADJV_Offset2_2OffsetGain = 2846,
	ADJV_Offset2_3OffsetGain = 2856,
	ADJV_Gain_1OffsetGain = 2866,
	ADJV_Gain_2OffsetGain = 2876,
	ADJV_Gain_3OffsetGain = 2886,
	ADJV_ChannelNumDisplayFlag = 2896,
	ADJV_ChannelNumAppendDisplayFlag = 2906,
	ADJV_OsdScale100Percent = 2916,
	ADJV_OsdFullScreenXPercent = 2926,
	ADJV_OsdFullScreenYPercent = 2936,
	ADJV_OsdState = 2946,
	ADJV_OsdBitFlags = 2956,
	ADJV_CurrentBlockedTVRatingSubcodeMain = 2966,
	ADJV_CurrentBlockedTVRatingSubcodePip = 2976,
	ADJV_MPipTileSet = 2986,
	ADJV_ChipIDdigit1 = 2996,
	ADJV_ChipIDdigit2 = 3006,
	ADJV_ChipIDdigit3 = 3016,
	ADJV_ChipIDdigit4 = 3026,
	ADJV_ColorSystem = 3036,
	ADJV_TtxNoSignalFlag = 3046,
	ADJV_InputPortList = 3056,
	ADJV_GlobalInputPortListGroupInputPort_1InputPortList = 3058,
	ADJV_GlobalInputPortListGroupInputPort_2InputPortList = 3068,
	ADJV_GlobalInputPortListGroupInputPort_3InputPortList = 3078,
	ADJV_GlobalInputPortListGroupInputPort_4InputPortList = 3088,
	ADJV_GlobalInputPortListGroupInputPort_5InputPortList = 3098,
	ADJV_InputPortCount = 3108,
	ADJV_DisplayPortName = 3118,
	ADJV_OldOrNewPortChange = 3128,
	ADJV_Str1_seg = 3138,
	ADJV_Str2_seg = 3148,
	ADJV_Str3_seg = 3158,
	ADJV_Str4_seg = 3168,
	ADJV_Str1_ofs = 3178,
	ADJV_Str2_ofs = 3188,
	ADJV_Str3_ofs = 3198,
	ADJV_Str4_ofs = 3208,
	ADJV_CecDeviceName_seg = 3218,
	ADJV_CecDeviceName_ofs = 3228,
	ADJV_CecDeviceType = 3238,
	ADJV_DontRemoveOSD = 3248,
	ADJV_CecRecordOnExtPlugNumber = 3258,
	ADJV_CecDevicePowerStatus = 3268,
	ADJV_CecStatusText1_seg = 3278,
	ADJV_CecStatusText1_ofs = 3288,
	ADJV_CecStatusText2_seg = 3298,
	ADJV_CecStatusText2_ofs = 3308,
	ADJV_CecStatusText3_seg = 3318,
	ADJV_CecStatusText3_ofs = 3328,
	ADJV_CecStatusLineCounter = 3338,
	ADJV_CecRecordDateDay = 3348,
	ADJV_CecRecordDateMonth = 3358,
	ADJV_CecRecordTimeHours = 3368,
	ADJV_CecRecordTimeMinutes = 3378,
	ADJV_CecRecordDurationHours = 3388,
	ADJV_CecRecordDurationMinutes = 3398,
	ADJV_CecHDMITreeMode = 3408,
	ADJV_CecDeviceSelectedFromHDMITree = 3418,
	ADJV_CecSystemAudioStatus = 3428,
	ADJV_IspFlashWrPercent = 3438,
	ADJV_InFwMajor = 3448,
	ADJV_InFwMinor = 3458,
	ADJV_InFwRc = 3468,
	ADJV_GlobalOSD_temp = 3478,
	ADJV_OSD_IR = 3488,
	ADJV_test1 = 3498,
	ADJV_test2 = 3508,
	ADJV_VIDEO_D = 3518,
	ADJV_BurnInMode = 3528,
	ADJV_BurnInModeV = 3538,
	ADJV_GlobalTest_Pattern = 3548,
	ADJV_LED_Setting = 3558,
	ADJV_OutputTiming = 3568,
	ADJV_HStart = 3578,
	ADJV_VStart = 3588,
	ADJV_HTotal = 3598,
	ADJV_HSyncPhase = 3608,
	ADJV_HSyncDelay = 3618,
	ADJV_VSyncDelay = 3628,
	ADJV_Acm3BlueLuma = 3638,
	ADJV_Acm3CyanLuma = 3648,
	ADJV_Acm3GreenLuma = 3658,
	ADJV_Acm3MagentaLuma = 3668,
	ADJV_Acm3RedLuma = 3678,
	ADJV_Acm3YellowLuma = 3688,
	ADJV_Acm3BlackLuma = 3698,
	ADJV_Acm3WhiteLuma = 3708,
	ADJV_Acm3BlueHue = 3718,
	ADJV_Acm3CyanHue = 3728,
	ADJV_Acm3GreenHue = 3738,
	ADJV_Acm3MagentaHue = 3748,
	ADJV_Acm3RedHue = 3758,
	ADJV_Acm3YellowHue = 3768,
	ADJV_Acm3BlackHue = 3778,
	ADJV_Acm3WhiteHue = 3788,
	ADJV_Acm3BlueSat = 3798,
	ADJV_Acm3CyanSat = 3808,
	ADJV_Acm3GreenSat = 3818,
	ADJV_Acm3MagentaSat = 3828,
	ADJV_Acm3RedSat = 3838,
	ADJV_Acm3YellowSat = 3848,
	ADJV_Acm3BlackSat = 3858,
	ADJV_Acm3WhiteSat = 3868,
	ADJV_AcmBlueHue = 3878,
	ADJV_AcmCyanHue = 3888,
	ADJV_AcmGreenHue = 3898,
	ADJV_AcmMagentaHue = 3908,
	ADJV_AcmRedHue = 3918,
	ADJV_AcmYellowHue = 3928,
	ADJV_AcmBlueSat = 3938,
	ADJV_AcmCyanSat = 3948,
	ADJV_AcmGreenSat = 3958,
	ADJV_AcmMagentaSat = 3968,
	ADJV_AcmRedSat = 3978,
	ADJV_AcmYellowSat = 3988,
	ADJV_Brightness = 3998,
	ADJV_Contrast = 4008,
	ADJV_Saturation = 4018,
	ADJV_Hue = 4028,
	ADJV_UserRedGain = 4038,
	ADJV_UserGreenGain = 4048,
	ADJV_UserBlueGain = 4058,
	ADJV_UserRedOff = 4068,
	ADJV_UserGreenOff = 4078,
	ADJV_UserBlueOff = 4088,
	ADJV_ColorTemp = 4098,
	ADJV_GammaTable = 4108,
	ADJV_MFMImageScheme = 4118,
	ADJV_InputColorDomain = 4128,
	ADJV_OutputColorType = 4138,
	ADJV_DUMSwitch = 4148,
	ADJV_NULL = 0x7FFF
} AdjValEnum;

extern BYTE ROM gmv_UserDefAdjusterProperty[4158];

#endif  // ifndef OSD_UADJ_H_DEFINED
