////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_USET_H_DEFINED
#define OSD_USET_H_DEFINED

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct ModeIndependentUserPrefTypeStruct
{
	SBYTE	TNR;
	SBYTE	MADI;
	SBYTE	CCS;
	SBYTE	SharpNoise;
	BYTE	SplitScreen;
	SBYTE	DCDiMain;
	SBYTE	DCDiPip;
	BYTE	MPEGNRMode;
	BYTE	MPEGNRThresh0;
	BYTE	MPEGNRThresh1;
	BYTE	MPEGNRThresh2;
	BYTE	LCDOverdriveNoiseCoring;
	BYTE	ThreeTwoFilmDisplayMode;
	BYTE	VBI_ServicePreferred;
	BYTE	SharpnessPip;
	BYTE	BlueStretch;
	BYTE	SharpnessRGB;
	BYTE	SharpnessRGBpip;
	WORD	AVSDelay;
	BYTE	AudioVolume;
	BYTE	ADCCalibrationMethod_Comp;
	BYTE	ADCCalibrationMethod_VGA;
	SBYTE	AspectRatioMain;
	SBYTE	AspectRatioPip;
	BYTE	CurrentInputMain;
	BYTE	CurrentInputPip;
	SBYTE	DynamicContrast;
	SBYTE	FilmMode;
	BYTE	FleshToneComp;
	SBYTE	ImageScheme;
	BYTE	LCDOverdrive;
	SBYTE	LetterboxEnable;
	SBYTE	MPEGNR;
	BYTE	OsdHPosition;
	BYTE	OsdLanguage;
	BYTE	OsdRotation;
	BYTE	OsdTimeout;
	BYTE	OsdVPosition;
	SBYTE	OverscanEnable;
	BYTE	PanelSelect;
	SBYTE	PipMode;
	SBYTE	PipPosition;
	BYTE	PowerState;
	BYTE	Sharpness;
	BYTE	SleepAMPM;
	BYTE	SleepDay;
	BYTE	SleepHour;
	BYTE	SleepMin;
	BYTE	SleepMinsLeft;
	SBYTE	ThreeDNR;
	WORD	TVRating;
	BYTE	TVUnrated;
	WORD	Version;
	BYTE	WakeAMPM;
	BYTE	WakeDay;
	BYTE	WakeHour;
	BYTE	WakeMin;
	WORD	MPRating;
	WORD	AVSDelayTime;
	SBYTE	CC_On;
	BYTE	AudioMute;
	BYTE	MPipConfig;
	SBYTE	OSDSplashScreen;
	WORD	ParentalPassword;
	SWORD	PipSize;
	BYTE	PreviousInputMain;
	BYTE	ScrollMenuItem;
	BYTE	SplitLcdOverdrive;
	BYTE	TTXLanguageGroup;
	BYTE	MainRouteModeComponent;
	BYTE	MainRouteModeScartRGB;
	BYTE	PipRouteModeComponent;
	BYTE	PipRouteModeScartRGB;
	BYTE	Reg_MVF_SHARPNESS_LUMA;
	BYTE	Reg_MVF_SHARPNESS_CHROMA;
	BYTE	Reg_MVF_NOISE_CORING_THRESH;
	BYTE	Reg_MVF_NONLINEAR_THRESH1;
	BYTE	Reg_MVF_NONLINEAR_GAIN1;
	BYTE	Reg_MVF_NONLINEAR_THRESH2;
	BYTE	Reg_MVF_NONLINEAR_GAIN2;
	BYTE	Reg_MHF_SHARPNESS_LUMA;
	BYTE	Reg_MHF_SHARPNESS_CHROMA;
	BYTE	Reg_MHF_NOISE_CORING_THRESH;
	BYTE	Reg_MHF_NONLINEAR_THRESH1;
	BYTE	Reg_MHF_NONLINEAR_GAIN1;
	BYTE	Reg_MHF_NONLINEAR_THRESH2;
	BYTE	Reg_MHF_NONLINEAR_GAIN2;
	BYTE	Reg_PVF_SHARPNESS_LUMA;
	BYTE	Reg_PVF_SHARPNESS_CHROMA;
	BYTE	Reg_PVF_NOISE_CORING_THRESH;
	BYTE	Reg_PVF_NONLINEAR_THRESH1;
	BYTE	Reg_PVF_NONLINEAR_GAIN1;
	BYTE	Reg_PVF_NONLINEAR_THRESH2;
	BYTE	Reg_PVF_NONLINEAR_GAIN2;
	BYTE	Reg_PHF_SHARPNESS_LUMA;
	BYTE	Reg_PHF_SHARPNESS_CHROMA;
	BYTE	Reg_PHF_NOISE_CORING_THRESH;
	BYTE	Reg_PHF_NONLINEAR_THRESH1;
	BYTE	Reg_PHF_NONLINEAR_GAIN1;
	BYTE	Reg_PHF_NONLINEAR_THRESH2;
	BYTE	Reg_PHF_NONLINEAR_GAIN2;
	BYTE	Reg_HEM_HLE_THR;
	BYTE	Reg_HEM_HLE_GAIN;
	BYTE	Reg_HEM_HDP_THR;
	BYTE	Reg_HEM_HDP_GAIN;
	BYTE	Reg_HEM_CE_THR;
	BYTE	Reg_HEM_CE_GAIN;
	BYTE	Reg_VDP_THRESHOLD;
	BYTE	Reg_VDP_GAIN;
	BYTE	NativeMode;
	BYTE	YUV2RGBExpansionMode;
	BYTE	NonACMFleshtoneCorrection;
	BYTE	NonACMFleshtoneBalance;
	BYTE	NonACMFleshtoneCorrectionLevel;
	BYTE	UserPrefTVYouth7Subcode;
	BYTE	UserPrefTVPGSubcode;
	BYTE	UserPrefTV14Subcode;
	BYTE	UserPrefTVMASubcode;
	SBYTE	DecoderAGCMethod;
	SBYTE	CCSforHD;
	BYTE	TwoStageProcessing;
	SWORD	ManualTVMHzFreq;
	SWORD	ManualTVkHzFreq;
	SWORD	TVFreqFineTune;
	BYTE	TVManualScanRequired;
	BYTE	UserPrefScartRgbViaOverlay;
	BYTE	ADCCalibrationMethod_CVBS;
	BYTE	ADCCalibrationMethod_InternalDac;
	BYTE	AutoAspectRatio;
	BYTE	ADCCalibrationMethod_SCART;
	WORD	Reg_MHF_ENH_Y_LSHOOT_TOL;
	WORD	Reg_MHF_ENH_Y_SSHOOT_TOL;
	WORD	Reg_MHF_ENH_Y_LGAIN;
	WORD	Reg_MHF_ENH_Y_SGAIN;
	WORD	Reg_MHF_ENH_Y_FINALSGAIN;
	WORD	Reg_MHF_ENH_Y_FINALLGAIN;
	WORD	Reg_MHF_ENH_Y_FINALGAIN;
	BYTE	Reg_MHF_ENH_Y_DELTA;
	BYTE	Reg_MHF_ENH_Y_SLOPE;
	WORD	Reg_MHF_ENH_Y_THRESH;
	BYTE	Reg_MHF_ENH_Y_HIGH_SLOPE_AGC;
	BYTE	Reg_MHF_ENH_Y_LOW_SLOPE_AGC;
	WORD	Reg_MHF_ENH_Y_HIGH_THRESH_AGC;
	WORD	Reg_MHF_ENH_Y_LOW_THRESH_AGC;
	WORD	Reg_MHF_ENH_UV_LSHOOT_TOL;
	WORD	Reg_MHF_ENH_UV_SSHOOT_TOL;
	WORD	Reg_MHF_ENH_UV_LGAIN;
	WORD	Reg_MHF_ENH_UV_SGAIN;
	WORD	Reg_MHF_ENH_UV_FINALSGAIN;
	WORD	Reg_MHF_ENH_UV_FINALLGAIN;
	WORD	Reg_MHF_ENH_UV_FINALGAIN;
	BYTE	Reg_MHF_ENH_UV_DELTA;
	BYTE	Reg_MHF_ENH_UV_SLOPE;
	WORD	Reg_MHF_ENH_UV_THRESH;
	BYTE	Reg_MHF_ENH_UV_HIGH_SLOPE_AGC;
	BYTE	Reg_MHF_ENH_UV_LOW_SLOPE_AGC;
	WORD	Reg_MHF_ENH_UV_HIGH_THRESH_AGC;
	WORD	Reg_MHF_ENH_UV_LOW_THRESH_AGC;
	WORD	Reg_MVF_ENH_Y_LSHOOT_TOL;
	WORD	Reg_MVF_ENH_Y_SSHOOT_TOL;
	WORD	Reg_MVF_ENH_Y_LGAIN;
	WORD	Reg_MVF_ENH_Y_SGAIN;
	WORD	Reg_MVF_ENH_Y_FINALSGAIN;
	WORD	Reg_MVF_ENH_Y_FINALLGAIN;
	WORD	Reg_MVF_ENH_Y_FINALGAIN;
	BYTE	Reg_MVF_ENH_Y_DELTA;
	BYTE	Reg_MVF_ENH_Y_SLOPE;
	WORD	Reg_MVF_ENH_Y_THRESH;
	BYTE	Reg_MVF_ENH_Y_HIGH_SLOPE_AGC;
	BYTE	Reg_MVF_ENH_Y_LOW_SLOPE_AGC;
	WORD	Reg_MVF_ENH_Y_HIGH_THRESH_AGC;
	WORD	Reg_MVF_ENH_Y_LOW_THRESH_AGC;
	WORD	Reg_MVF_ENH_UV_LSHOOT_TOL;
	WORD	Reg_MVF_ENH_UV_SSHOOT_TOL;
	WORD	Reg_MVF_ENH_UV_LGAIN;
	WORD	Reg_MVF_ENH_UV_SGAIN;
	WORD	Reg_MVF_ENH_UV_FINALSGAIN;
	WORD	Reg_MVF_ENH_UV_FINALLGAIN;
	WORD	Reg_MVF_ENH_UV_FINALGAIN;
	BYTE	Reg_MVF_ENH_UV_DELTA;
	BYTE	Reg_MVF_ENH_UV_SLOPE;
	WORD	Reg_MVF_ENH_UV_THRESH;
	BYTE	Reg_MVF_ENH_UV_HIGH_SLOPE_AGC;
	BYTE	Reg_MVF_ENH_UV_LOW_SLOPE_AGC;
	WORD	Reg_MVF_ENH_UV_HIGH_THRESH_AGC;
	WORD	Reg_MVF_ENH_UV_LOW_THRESH_AGC;
	BYTE	EnhancerEnable;
	BYTE	OldEnhancerEnable;
	BYTE	OldEnhancerRouting;
	BYTE	ColorResourceRouting;
	BYTE	ADCCalibrationMethod_SIF;
	SBYTE	ImpVlut;
	SBYTE	LineoutVariable;
	BYTE	UserPrefGameFlag;
	BYTE	UserPrefXvYcc;
	BYTE	UserPrefDCRFlag;
	BYTE	XNumber;
	BYTE	YNumber;
	BYTE	PublicDisplayNumber;
	BYTE	AudioDownMix;
	BYTE	ColorSpace;
	BYTE	VwdFlag;
	BYTE	VwdDemo;
	BYTE	AudioMainInput;
	BYTE	AudioMainOutput;
	BYTE	AudioPipInput;
	BYTE	AudioPipOutput;
	BYTE	OSD_G1_Blend;
	BYTE	OSD_G2_Blend;
	BYTE	OSD_G3_Blend;
	BYTE	CaptureM;
	BYTE	ImageRotation;
	BYTE	OSD_4Kx2K_Port;
	BYTE	DPSWitch;
	BYTE	BackLight;
	BYTE	OsdBlend;
	BYTE	FanStatus;
	BYTE	PIPHPos;
	BYTE	PIPVPos;
	BYTE	PipModeOnOff;
	BYTE	ScheduleOnOff;
	BYTE	OverScan;
	BYTE	AutoBLState;
	BYTE	MinBrightness;
	BYTE	AUTOADJUST;
	BYTE	DisplayPos;
} ModeIndependentUserPrefType;

#define ModeIndependentUserPrefSize		(sizeof(ModeIndependentUserPrefType))

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

typedef enum 
{
	TNR_offset = 0,
	MADI_offset = TNR_offset + BYTE_SIZE,
	CCS_offset = MADI_offset + BYTE_SIZE,
	SharpNoise_offset = CCS_offset + BYTE_SIZE,
	SplitScreen_offset = SharpNoise_offset + BYTE_SIZE,
	DCDiMain_offset = SplitScreen_offset + BYTE_SIZE,
	DCDiPip_offset = DCDiMain_offset + BYTE_SIZE,
	MPEGNRMode_offset = DCDiPip_offset + BYTE_SIZE,
	MPEGNRThresh0_offset = MPEGNRMode_offset + BYTE_SIZE,
	MPEGNRThresh1_offset = MPEGNRThresh0_offset + BYTE_SIZE,
	MPEGNRThresh2_offset = MPEGNRThresh1_offset + BYTE_SIZE,
	LCDOverdriveNoiseCoring_offset = MPEGNRThresh2_offset + BYTE_SIZE,
	ThreeTwoFilmDisplayMode_offset = LCDOverdriveNoiseCoring_offset + BYTE_SIZE,
	VBI_ServicePreferred_offset = ThreeTwoFilmDisplayMode_offset + BYTE_SIZE,
	SharpnessPip_offset = VBI_ServicePreferred_offset + BYTE_SIZE,
	BlueStretch_offset = SharpnessPip_offset + BYTE_SIZE,
	SharpnessRGB_offset = BlueStretch_offset + BYTE_SIZE,
	SharpnessRGBpip_offset = SharpnessRGB_offset + BYTE_SIZE,
	AVSDelay_offset = SharpnessRGBpip_offset + BYTE_SIZE,
	AudioVolume_offset = AVSDelay_offset + WORD_SIZE,
	ADCCalibrationMethod_Comp_offset = AudioVolume_offset + BYTE_SIZE,
	ADCCalibrationMethod_VGA_offset = ADCCalibrationMethod_Comp_offset + BYTE_SIZE,
	AspectRatioMain_offset = ADCCalibrationMethod_VGA_offset + BYTE_SIZE,
	AspectRatioPip_offset = AspectRatioMain_offset + BYTE_SIZE,
	CurrentInputMain_offset = AspectRatioPip_offset + BYTE_SIZE,
	CurrentInputPip_offset = CurrentInputMain_offset + BYTE_SIZE,
	DynamicContrast_offset = CurrentInputPip_offset + BYTE_SIZE,
	FilmMode_offset = DynamicContrast_offset + BYTE_SIZE,
	FleshToneComp_offset = FilmMode_offset + BYTE_SIZE,
	ImageScheme_offset = FleshToneComp_offset + BYTE_SIZE,
	LCDOverdrive_offset = ImageScheme_offset + BYTE_SIZE,
	LetterboxEnable_offset = LCDOverdrive_offset + BYTE_SIZE,
	MPEGNR_offset = LetterboxEnable_offset + BYTE_SIZE,
	OsdHPosition_offset = MPEGNR_offset + BYTE_SIZE,
	OsdLanguage_offset = OsdHPosition_offset + BYTE_SIZE,
	OsdRotation_offset = OsdLanguage_offset + BYTE_SIZE,
	OsdTimeout_offset = OsdRotation_offset + BYTE_SIZE,
	OsdVPosition_offset = OsdTimeout_offset + BYTE_SIZE,
	OverscanEnable_offset = OsdVPosition_offset + BYTE_SIZE,
	PanelSelect_offset = OverscanEnable_offset + BYTE_SIZE,
	PipMode_offset = PanelSelect_offset + BYTE_SIZE,
	PipPosition_offset = PipMode_offset + BYTE_SIZE,
	PowerState_offset = PipPosition_offset + BYTE_SIZE,
	Sharpness_offset = PowerState_offset + BYTE_SIZE,
	SleepAMPM_offset = Sharpness_offset + BYTE_SIZE,
	SleepDay_offset = SleepAMPM_offset + BYTE_SIZE,
	SleepHour_offset = SleepDay_offset + BYTE_SIZE,
	SleepMin_offset = SleepHour_offset + BYTE_SIZE,
	SleepMinsLeft_offset = SleepMin_offset + BYTE_SIZE,
	ThreeDNR_offset = SleepMinsLeft_offset + BYTE_SIZE,
	TVRating_offset = ThreeDNR_offset + BYTE_SIZE,
	TVUnrated_offset = TVRating_offset + WORD_SIZE,
	Version_offset = TVUnrated_offset + BYTE_SIZE,
	WakeAMPM_offset = Version_offset + WORD_SIZE,
	WakeDay_offset = WakeAMPM_offset + BYTE_SIZE,
	WakeHour_offset = WakeDay_offset + BYTE_SIZE,
	WakeMin_offset = WakeHour_offset + BYTE_SIZE,
	MPRating_offset = WakeMin_offset + BYTE_SIZE,
	AVSDelayTime_offset = MPRating_offset + WORD_SIZE,
	CC_On_offset = AVSDelayTime_offset + WORD_SIZE,
	AudioMute_offset = CC_On_offset + BYTE_SIZE,
	MPipConfig_offset = AudioMute_offset + BYTE_SIZE,
	OSDSplashScreen_offset = MPipConfig_offset + BYTE_SIZE,
	ParentalPassword_offset = OSDSplashScreen_offset + BYTE_SIZE,
	PipSize_offset = ParentalPassword_offset + WORD_SIZE,
	PreviousInputMain_offset = PipSize_offset + WORD_SIZE,
	ScrollMenuItem_offset = PreviousInputMain_offset + BYTE_SIZE,
	SplitLcdOverdrive_offset = ScrollMenuItem_offset + BYTE_SIZE,
	TTXLanguageGroup_offset = SplitLcdOverdrive_offset + BYTE_SIZE,
	MainRouteModeComponent_offset = TTXLanguageGroup_offset + BYTE_SIZE,
	MainRouteModeScartRGB_offset = MainRouteModeComponent_offset + BYTE_SIZE,
	PipRouteModeComponent_offset = MainRouteModeScartRGB_offset + BYTE_SIZE,
	PipRouteModeScartRGB_offset = PipRouteModeComponent_offset + BYTE_SIZE,
	Reg_MVF_SHARPNESS_LUMA_offset = PipRouteModeScartRGB_offset + BYTE_SIZE,
	Reg_MVF_SHARPNESS_CHROMA_offset = Reg_MVF_SHARPNESS_LUMA_offset + BYTE_SIZE,
	Reg_MVF_NOISE_CORING_THRESH_offset = Reg_MVF_SHARPNESS_CHROMA_offset + BYTE_SIZE,
	Reg_MVF_NONLINEAR_THRESH1_offset = Reg_MVF_NOISE_CORING_THRESH_offset + BYTE_SIZE,
	Reg_MVF_NONLINEAR_GAIN1_offset = Reg_MVF_NONLINEAR_THRESH1_offset + BYTE_SIZE,
	Reg_MVF_NONLINEAR_THRESH2_offset = Reg_MVF_NONLINEAR_GAIN1_offset + BYTE_SIZE,
	Reg_MVF_NONLINEAR_GAIN2_offset = Reg_MVF_NONLINEAR_THRESH2_offset + BYTE_SIZE,
	Reg_MHF_SHARPNESS_LUMA_offset = Reg_MVF_NONLINEAR_GAIN2_offset + BYTE_SIZE,
	Reg_MHF_SHARPNESS_CHROMA_offset = Reg_MHF_SHARPNESS_LUMA_offset + BYTE_SIZE,
	Reg_MHF_NOISE_CORING_THRESH_offset = Reg_MHF_SHARPNESS_CHROMA_offset + BYTE_SIZE,
	Reg_MHF_NONLINEAR_THRESH1_offset = Reg_MHF_NOISE_CORING_THRESH_offset + BYTE_SIZE,
	Reg_MHF_NONLINEAR_GAIN1_offset = Reg_MHF_NONLINEAR_THRESH1_offset + BYTE_SIZE,
	Reg_MHF_NONLINEAR_THRESH2_offset = Reg_MHF_NONLINEAR_GAIN1_offset + BYTE_SIZE,
	Reg_MHF_NONLINEAR_GAIN2_offset = Reg_MHF_NONLINEAR_THRESH2_offset + BYTE_SIZE,
	Reg_PVF_SHARPNESS_LUMA_offset = Reg_MHF_NONLINEAR_GAIN2_offset + BYTE_SIZE,
	Reg_PVF_SHARPNESS_CHROMA_offset = Reg_PVF_SHARPNESS_LUMA_offset + BYTE_SIZE,
	Reg_PVF_NOISE_CORING_THRESH_offset = Reg_PVF_SHARPNESS_CHROMA_offset + BYTE_SIZE,
	Reg_PVF_NONLINEAR_THRESH1_offset = Reg_PVF_NOISE_CORING_THRESH_offset + BYTE_SIZE,
	Reg_PVF_NONLINEAR_GAIN1_offset = Reg_PVF_NONLINEAR_THRESH1_offset + BYTE_SIZE,
	Reg_PVF_NONLINEAR_THRESH2_offset = Reg_PVF_NONLINEAR_GAIN1_offset + BYTE_SIZE,
	Reg_PVF_NONLINEAR_GAIN2_offset = Reg_PVF_NONLINEAR_THRESH2_offset + BYTE_SIZE,
	Reg_PHF_SHARPNESS_LUMA_offset = Reg_PVF_NONLINEAR_GAIN2_offset + BYTE_SIZE,
	Reg_PHF_SHARPNESS_CHROMA_offset = Reg_PHF_SHARPNESS_LUMA_offset + BYTE_SIZE,
	Reg_PHF_NOISE_CORING_THRESH_offset = Reg_PHF_SHARPNESS_CHROMA_offset + BYTE_SIZE,
	Reg_PHF_NONLINEAR_THRESH1_offset = Reg_PHF_NOISE_CORING_THRESH_offset + BYTE_SIZE,
	Reg_PHF_NONLINEAR_GAIN1_offset = Reg_PHF_NONLINEAR_THRESH1_offset + BYTE_SIZE,
	Reg_PHF_NONLINEAR_THRESH2_offset = Reg_PHF_NONLINEAR_GAIN1_offset + BYTE_SIZE,
	Reg_PHF_NONLINEAR_GAIN2_offset = Reg_PHF_NONLINEAR_THRESH2_offset + BYTE_SIZE,
	Reg_HEM_HLE_THR_offset = Reg_PHF_NONLINEAR_GAIN2_offset + BYTE_SIZE,
	Reg_HEM_HLE_GAIN_offset = Reg_HEM_HLE_THR_offset + BYTE_SIZE,
	Reg_HEM_HDP_THR_offset = Reg_HEM_HLE_GAIN_offset + BYTE_SIZE,
	Reg_HEM_HDP_GAIN_offset = Reg_HEM_HDP_THR_offset + BYTE_SIZE,
	Reg_HEM_CE_THR_offset = Reg_HEM_HDP_GAIN_offset + BYTE_SIZE,
	Reg_HEM_CE_GAIN_offset = Reg_HEM_CE_THR_offset + BYTE_SIZE,
	Reg_VDP_THRESHOLD_offset = Reg_HEM_CE_GAIN_offset + BYTE_SIZE,
	Reg_VDP_GAIN_offset = Reg_VDP_THRESHOLD_offset + BYTE_SIZE,
	NativeMode_offset = Reg_VDP_GAIN_offset + BYTE_SIZE,
	YUV2RGBExpansionMode_offset = NativeMode_offset + BYTE_SIZE,
	NonACMFleshtoneCorrection_offset = YUV2RGBExpansionMode_offset + BYTE_SIZE,
	NonACMFleshtoneBalance_offset = NonACMFleshtoneCorrection_offset + BYTE_SIZE,
	NonACMFleshtoneCorrectionLevel_offset = NonACMFleshtoneBalance_offset + BYTE_SIZE,
	TVYouth7Subcode_offset = NonACMFleshtoneCorrectionLevel_offset + BYTE_SIZE,
	TVPGSubcode_offset = TVYouth7Subcode_offset + BYTE_SIZE,
	TV14Subcode_offset = TVPGSubcode_offset + BYTE_SIZE,
	TVMASubcode_offset = TV14Subcode_offset + BYTE_SIZE,
	DecoderAGCMethod_offset = TVMASubcode_offset + BYTE_SIZE,
	CCSforHD_offset = DecoderAGCMethod_offset + BYTE_SIZE,
	TwoStageProcessing_offset = CCSforHD_offset + BYTE_SIZE,
	ManualTVMHzFreq_offset = TwoStageProcessing_offset + BYTE_SIZE,
	ManualTVkHzFreq_offset = ManualTVMHzFreq_offset + WORD_SIZE,
	TVFreqFineTune_offset = ManualTVkHzFreq_offset + WORD_SIZE,
	TVManualScanRequired_offset = TVFreqFineTune_offset + WORD_SIZE,
	ScartRgbViaOverlay_offset = TVManualScanRequired_offset + BYTE_SIZE,
	ADCCalibrationMethod_CVBS_offset = ScartRgbViaOverlay_offset + BYTE_SIZE,
	ADCCalibrationMethod_InternalDac_offset = ADCCalibrationMethod_CVBS_offset + BYTE_SIZE,
	AutoAspectRatio_offset = ADCCalibrationMethod_InternalDac_offset + BYTE_SIZE,
	ADCCalibrationMethod_SCART_offset = AutoAspectRatio_offset + BYTE_SIZE,
	Reg_MHF_ENH_Y_LSHOOT_TOL_offset = ADCCalibrationMethod_SCART_offset + BYTE_SIZE,
	Reg_MHF_ENH_Y_SSHOOT_TOL_offset = Reg_MHF_ENH_Y_LSHOOT_TOL_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_LGAIN_offset = Reg_MHF_ENH_Y_SSHOOT_TOL_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_SGAIN_offset = Reg_MHF_ENH_Y_LGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_FINALSGAIN_offset = Reg_MHF_ENH_Y_SGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_FINALLGAIN_offset = Reg_MHF_ENH_Y_FINALSGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_FINALGAIN_offset = Reg_MHF_ENH_Y_FINALLGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_DELTA_offset = Reg_MHF_ENH_Y_FINALGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_SLOPE_offset = Reg_MHF_ENH_Y_DELTA_offset + BYTE_SIZE,
	Reg_MHF_ENH_Y_THRESH_offset = Reg_MHF_ENH_Y_SLOPE_offset + BYTE_SIZE,
	Reg_MHF_ENH_Y_HIGH_SLOPE_AGC_offset = Reg_MHF_ENH_Y_THRESH_offset + WORD_SIZE,
	Reg_MHF_ENH_Y_LOW_SLOPE_AGC_offset = Reg_MHF_ENH_Y_HIGH_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MHF_ENH_Y_HIGH_THRESH_AGC_offset = Reg_MHF_ENH_Y_LOW_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MHF_ENH_Y_LOW_THRESH_AGC_offset = Reg_MHF_ENH_Y_HIGH_THRESH_AGC_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_LSHOOT_TOL_offset = Reg_MHF_ENH_Y_LOW_THRESH_AGC_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_SSHOOT_TOL_offset = Reg_MHF_ENH_UV_LSHOOT_TOL_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_LGAIN_offset = Reg_MHF_ENH_UV_SSHOOT_TOL_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_SGAIN_offset = Reg_MHF_ENH_UV_LGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_FINALSGAIN_offset = Reg_MHF_ENH_UV_SGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_FINALLGAIN_offset = Reg_MHF_ENH_UV_FINALSGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_FINALGAIN_offset = Reg_MHF_ENH_UV_FINALLGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_DELTA_offset = Reg_MHF_ENH_UV_FINALGAIN_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_SLOPE_offset = Reg_MHF_ENH_UV_DELTA_offset + BYTE_SIZE,
	Reg_MHF_ENH_UV_THRESH_offset = Reg_MHF_ENH_UV_SLOPE_offset + BYTE_SIZE,
	Reg_MHF_ENH_UV_HIGH_SLOPE_AGC_offset = Reg_MHF_ENH_UV_THRESH_offset + WORD_SIZE,
	Reg_MHF_ENH_UV_LOW_SLOPE_AGC_offset = Reg_MHF_ENH_UV_HIGH_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MHF_ENH_UV_HIGH_THRESH_AGC_offset = Reg_MHF_ENH_UV_LOW_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MHF_ENH_UV_LOW_THRESH_AGC_offset = Reg_MHF_ENH_UV_HIGH_THRESH_AGC_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_LSHOOT_TOL_offset = Reg_MHF_ENH_UV_LOW_THRESH_AGC_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_SSHOOT_TOL_offset = Reg_MVF_ENH_Y_LSHOOT_TOL_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_LGAIN_offset = Reg_MVF_ENH_Y_SSHOOT_TOL_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_SGAIN_offset = Reg_MVF_ENH_Y_LGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_FINALSGAIN_offset = Reg_MVF_ENH_Y_SGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_FINALLGAIN_offset = Reg_MVF_ENH_Y_FINALSGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_FINALGAIN_offset = Reg_MVF_ENH_Y_FINALLGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_DELTA_offset = Reg_MVF_ENH_Y_FINALGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_SLOPE_offset = Reg_MVF_ENH_Y_DELTA_offset + BYTE_SIZE,
	Reg_MVF_ENH_Y_THRESH_offset = Reg_MVF_ENH_Y_SLOPE_offset + BYTE_SIZE,
	Reg_MVF_ENH_Y_HIGH_SLOPE_AGC_offset = Reg_MVF_ENH_Y_THRESH_offset + WORD_SIZE,
	Reg_MVF_ENH_Y_LOW_SLOPE_AGC_offset = Reg_MVF_ENH_Y_HIGH_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MVF_ENH_Y_HIGH_THRESH_AGC_offset = Reg_MVF_ENH_Y_LOW_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MVF_ENH_Y_LOW_THRESH_AGC_offset = Reg_MVF_ENH_Y_HIGH_THRESH_AGC_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_LSHOOT_TOL_offset = Reg_MVF_ENH_Y_LOW_THRESH_AGC_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_SSHOOT_TOL_offset = Reg_MVF_ENH_UV_LSHOOT_TOL_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_LGAIN_offset = Reg_MVF_ENH_UV_SSHOOT_TOL_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_SGAIN_offset = Reg_MVF_ENH_UV_LGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_FINALSGAIN_offset = Reg_MVF_ENH_UV_SGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_FINALLGAIN_offset = Reg_MVF_ENH_UV_FINALSGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_FINALGAIN_offset = Reg_MVF_ENH_UV_FINALLGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_DELTA_offset = Reg_MVF_ENH_UV_FINALGAIN_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_SLOPE_offset = Reg_MVF_ENH_UV_DELTA_offset + BYTE_SIZE,
	Reg_MVF_ENH_UV_THRESH_offset = Reg_MVF_ENH_UV_SLOPE_offset + BYTE_SIZE,
	Reg_MVF_ENH_UV_HIGH_SLOPE_AGC_offset = Reg_MVF_ENH_UV_THRESH_offset + WORD_SIZE,
	Reg_MVF_ENH_UV_LOW_SLOPE_AGC_offset = Reg_MVF_ENH_UV_HIGH_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MVF_ENH_UV_HIGH_THRESH_AGC_offset = Reg_MVF_ENH_UV_LOW_SLOPE_AGC_offset + BYTE_SIZE,
	Reg_MVF_ENH_UV_LOW_THRESH_AGC_offset = Reg_MVF_ENH_UV_HIGH_THRESH_AGC_offset + WORD_SIZE,
	EnhancerEnable_offset = Reg_MVF_ENH_UV_LOW_THRESH_AGC_offset + WORD_SIZE,
	OldEnhancerEnable_offset = EnhancerEnable_offset + BYTE_SIZE,
	OldEnhancerRouting_offset = OldEnhancerEnable_offset + BYTE_SIZE,
	ColorResourceRouting_offset = OldEnhancerRouting_offset + BYTE_SIZE,
	ADCCalibrationMethod_SIF_offset = ColorResourceRouting_offset + BYTE_SIZE,
	ImpVlut_offset = ADCCalibrationMethod_SIF_offset + BYTE_SIZE,
	VariableForLineout_offset = ImpVlut_offset + BYTE_SIZE,
	GameMode_offset = VariableForLineout_offset + BYTE_SIZE,
	XvYcc_offset = GameMode_offset + BYTE_SIZE,
	DCR_offset = XvYcc_offset + BYTE_SIZE,
	XNumber_offset = DCR_offset + BYTE_SIZE,
	YNumber_offset = XNumber_offset + BYTE_SIZE,
	PublicDisplayNumber_offset = YNumber_offset + BYTE_SIZE,
	AudioDownMix_offset = PublicDisplayNumber_offset + BYTE_SIZE,
	ColorSpace_offset = AudioDownMix_offset + BYTE_SIZE,
	VwdFlag_offset = ColorSpace_offset + BYTE_SIZE,
	VwdDemo_offset = VwdFlag_offset + BYTE_SIZE,
	AudioMainInput_offset = VwdDemo_offset + BYTE_SIZE,
	AudioMainOutput_offset = AudioMainInput_offset + BYTE_SIZE,
	AudioPipInput_offset = AudioMainOutput_offset + BYTE_SIZE,
	AudioPipOutput_offset = AudioPipInput_offset + BYTE_SIZE,
	OSDG1Blend_offset = AudioPipOutput_offset + BYTE_SIZE,
	OSDG2Blend_offset = OSDG1Blend_offset + BYTE_SIZE,
	OSDG3Blend_offset = OSDG2Blend_offset + BYTE_SIZE,
	CaptureM_offset = OSDG3Blend_offset + BYTE_SIZE,
	ImageRotation_offset = CaptureM_offset + BYTE_SIZE,
	OSD_4Kx2K_Port_offset = ImageRotation_offset + BYTE_SIZE,
	DPSWitch_offset = OSD_4Kx2K_Port_offset + BYTE_SIZE,
	BackLight_offset = DPSWitch_offset + BYTE_SIZE,
	OsdBlend_offset = BackLight_offset + BYTE_SIZE,
	FanStatus_offset = OsdBlend_offset + BYTE_SIZE,
	PIPHPos_offset = FanStatus_offset + BYTE_SIZE,
	PIPVPos_offset = PIPHPos_offset + BYTE_SIZE,
	PipModeOnOff_offset = PIPVPos_offset + BYTE_SIZE,
	ScheduleOnOff_offset = PipModeOnOff_offset + BYTE_SIZE,
	OverScan_offset = ScheduleOnOff_offset + BYTE_SIZE,
	AutoBLState_offset = OverScan_offset + BYTE_SIZE,
	MinBrightness_offset = AutoBLState_offset + BYTE_SIZE,
	AUTOADJUST_offset = MinBrightness_offset + BYTE_SIZE,
	DisplayPos_offset = AUTOADJUST_offset + BYTE_SIZE
} ModeIndependentOffsets;

extern ModeIndependentUserPrefType  ModeIndependentUserPreferences;

extern ModeIndependentUserPrefType ROM FactoryDefaultInROM;
#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct ChannelNameGroupUserPrefTypeStruct
{
	BYTE	ChannelName;
} ChannelNameGroupUserPrefType;

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct BlockChannelListGroupUserPrefTypeStruct
{
	BYTE	BlockedChannelList;
} BlockChannelListGroupUserPrefType;

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct ADCOffsetGainGroupUserPrefTypeStruct
{
	SWORD	OffsetGain;
} ADCOffsetGainGroupUserPrefType;

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct GlobalInputPortListGroupUserPrefTypeStruct
{
	BYTE	InputPortList;
} GlobalInputPortListGroupUserPrefType;

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct GlobalUserPrefTypeStruct
{
	SBYTE	ParentalBlockStateFlagMain;
	SBYTE	ParentalBlockStateFlagPip;
	BYTE	ChannelBlockStateFlag;
	BYTE	ChannelBlockStateFlagPip;
	ChannelNameGroupUserPrefType	ChannelNameGroup[8];
	BYTE	Freeze;
	BYTE	MultiPipStateFlag;
	WORD	OsdMPipHPos;
	WORD	OsdMPipVPos;
	BYTE	OsdMPipChannel;
	BYTE	SideBySideFocus;
	WORD	OSDBottomPos;
	WORD	OSDCenterPos;
	SBYTE	ParentalMenuAccess;
	WORD	VChipPassword;
	BYTE	Month;
	BYTE	Date;
	BYTE	Year;
	BYTE	Hour;
	BYTE	Min;
	BYTE	AMPM;
	SBYTE	InfoDisplayOn;
	SBYTE	PrevPipSource;
	BYTE	ChannelFreqSlider;
	WORD	ChannelFreqValue;
	BYTE	FactoryState;
	WORD	TempVar;
	WORD	RegAddr;
	WORD	RegVal;
	SBYTE	PreviousPipMode;
	BYTE	ChannelNameEntry1;
	BYTE	ChannelNameEntry2;
	BYTE	ChannelNameEntry3;
	BYTE	ChannelNameEntry4;
	BYTE	ChannelNameEntry5;
	SWORD	PtrSegment;
	SWORD	PtrOffset;
	BlockChannelListGroupUserPrefType	BlockChannelListGroup[10];
	ADCOffsetGainGroupUserPrefType	ADCOffsetGainGroup[9];
	BYTE	ChannelNumDisplayFlag;
	BYTE	ChannelNumAppendDisplayFlag;
	BYTE	OsdScale100Percent;
	WORD	OsdFullScreenXPercent;
	WORD	OsdFullScreenYPercent;
	SBYTE	OsdState;
	BYTE	OsdBitFlags;
	BYTE	CurrentBlockedTVRatingSubcodeMain;
	BYTE	CurrentBlockedTVRatingSubcodePip;
	BYTE	MPipTileSet;
	BYTE	ChipIDdigit1;
	BYTE	ChipIDdigit2;
	BYTE	ChipIDdigit3;
	BYTE	ChipIDdigit4;
	BYTE	ColorSystem;
	BYTE	TtxNoSignalFlag;
	GlobalInputPortListGroupUserPrefType	InputPortListGroup[5];
	BYTE	InputPortCount;
	SBYTE	DisplayPortName;
	BYTE	OldOrNewPortChange;
	WORD	Str1_seg;
	WORD	Str2_seg;
	WORD	Str3_seg;
	WORD	Str4_seg;
	WORD	Str1_ofs;
	WORD	Str2_ofs;
	WORD	Str3_ofs;
	WORD	Str4_ofs;
	WORD	CecDeviceName_seg;
	WORD	CecDeviceName_ofs;
	BYTE	CecDeviceType;
	BYTE	DontRemoveOSD;
	BYTE	CecRecordOnExtPlugNumber;
	BYTE	CecDevicePowerStatus;
	WORD	CecStatusText1_seg;
	WORD	CecStatusText1_ofs;
	WORD	CecStatusText2_seg;
	WORD	CecStatusText2_ofs;
	WORD	CecStatusText3_seg;
	WORD	CecStatusText3_ofs;
	BYTE	CecStatusLineCounter;
	BYTE	CecRecordDateDay;
	BYTE	CecRecordDateMonth;
	BYTE	CecRecordTimeHours;
	BYTE	CecRecordTimeMinutes;
	BYTE	CecRecordDurationHours;
	BYTE	CecRecordDurationMinutes;
	BYTE	CecHDMITreeMode;
	BYTE	CecDeviceSelectedFromHDMITree;
	BYTE	CecSystemAudioStatus;
	BYTE	IspWrPercent;
	BYTE	InFwMajor;
	BYTE	InFwMinor;
	BYTE	InFwRc;
	BYTE	OSD_temp;
	BYTE	OSD_IR;
	BYTE	test1;
	BYTE	test2;
	BYTE	VIDEO_D;
	BYTE	BurnInMode;
	BYTE	BurnInModeV;
	BYTE	Test_Pattern;
	BYTE	LED_Setting;
	BYTE	OutputTiming;
} GlobalUserPrefType;

#define GlobalUserPrefSize		(sizeof(GlobalUserPrefType))

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

typedef enum 
{
	ParentalBlockStateFlagMain_offset = 0,
	ParentalBlockStateFlagPip_offset = ParentalBlockStateFlagMain_offset + BYTE_SIZE,
	ChannelBlockStateFlag_offset = ParentalBlockStateFlagPip_offset + BYTE_SIZE,
	ChannelBlockStateFlagPip_offset = ChannelBlockStateFlag_offset + BYTE_SIZE,
	Digit1ChannelName_offset = ChannelBlockStateFlagPip_offset + BYTE_SIZE,
	Digit2ChannelName_offset = Digit1ChannelName_offset + BYTE_SIZE,
	Digit3ChannelName_offset = Digit2ChannelName_offset + BYTE_SIZE,
	Digit4ChannelName_offset = Digit3ChannelName_offset + BYTE_SIZE,
	Digit5ChannelName_offset = Digit4ChannelName_offset + BYTE_SIZE,
	Digit6ChannelName_offset = Digit5ChannelName_offset + BYTE_SIZE,
	Digit7ChannelName_offset = Digit6ChannelName_offset + BYTE_SIZE,
	Digit8ChannelName_offset = Digit7ChannelName_offset + BYTE_SIZE,
	Freeze_offset = Digit8ChannelName_offset + BYTE_SIZE,
	MultiPipStateFlag_offset = Freeze_offset + BYTE_SIZE,
	OsdMPipHPos_offset = MultiPipStateFlag_offset + BYTE_SIZE,
	OsdMPipVPos_offset = OsdMPipHPos_offset + WORD_SIZE,
	OsdMPipChannel_offset = OsdMPipVPos_offset + WORD_SIZE,
	SideBySideFocus_offset = OsdMPipChannel_offset + BYTE_SIZE,
	OSDBottomPos_offset = SideBySideFocus_offset + BYTE_SIZE,
	OSDCenterPos_offset = OSDBottomPos_offset + WORD_SIZE,
	ParentalMenuAccess_offset = OSDCenterPos_offset + WORD_SIZE,
	VChipPassword_offset = ParentalMenuAccess_offset + BYTE_SIZE,
	Month_offset = VChipPassword_offset + WORD_SIZE,
	Date_offset = Month_offset + BYTE_SIZE,
	Year_offset = Date_offset + BYTE_SIZE,
	Hour_offset = Year_offset + BYTE_SIZE,
	Min_offset = Hour_offset + BYTE_SIZE,
	AMPM_offset = Min_offset + BYTE_SIZE,
	InfoDisplayOn_offset = AMPM_offset + BYTE_SIZE,
	PrevPipSource_offset = InfoDisplayOn_offset + BYTE_SIZE,
	ChannelFreqSlider_offset = PrevPipSource_offset + BYTE_SIZE,
	ChannelFreqValue_offset = ChannelFreqSlider_offset + BYTE_SIZE,
	FactoryState_offset = ChannelFreqValue_offset + WORD_SIZE,
	TempVar_offset = FactoryState_offset + BYTE_SIZE,
	RegAddr_offset = TempVar_offset + WORD_SIZE,
	RegVal_offset = RegAddr_offset + WORD_SIZE,
	PreviousPipMode_offset = RegVal_offset + WORD_SIZE,
	ChannelNameEntry1_offset = PreviousPipMode_offset + BYTE_SIZE,
	ChannelNameEntry2_offset = ChannelNameEntry1_offset + BYTE_SIZE,
	ChannelNameEntry3_offset = ChannelNameEntry2_offset + BYTE_SIZE,
	ChannelNameEntry4_offset = ChannelNameEntry3_offset + BYTE_SIZE,
	ChannelNameEntry5_offset = ChannelNameEntry4_offset + BYTE_SIZE,
	PtrSegment_offset = ChannelNameEntry5_offset + BYTE_SIZE,
	PtrOffset_offset = PtrSegment_offset + WORD_SIZE,
	BlockedChannel_1BlockedChannelList_offset = PtrOffset_offset + WORD_SIZE,
	BlockedChannel_2BlockedChannelList_offset = BlockedChannel_1BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_3BlockedChannelList_offset = BlockedChannel_2BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_4BlockedChannelList_offset = BlockedChannel_3BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_5BlockedChannelList_offset = BlockedChannel_4BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_6BlockedChannelList_offset = BlockedChannel_5BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_7BlockedChannelList_offset = BlockedChannel_6BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_8BlockedChannelList_offset = BlockedChannel_7BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_9BlockedChannelList_offset = BlockedChannel_8BlockedChannelList_offset + BYTE_SIZE,
	BlockedChannel_10BlockedChannelList_offset = BlockedChannel_9BlockedChannelList_offset + BYTE_SIZE,
	Offset1_1OffsetGain_offset = BlockedChannel_10BlockedChannelList_offset + BYTE_SIZE,
	Offset1_2OffsetGain_offset = Offset1_1OffsetGain_offset + WORD_SIZE,
	Offset1_3OffsetGain_offset = Offset1_2OffsetGain_offset + WORD_SIZE,
	Offset2_1OffsetGain_offset = Offset1_3OffsetGain_offset + WORD_SIZE,
	Offset2_2OffsetGain_offset = Offset2_1OffsetGain_offset + WORD_SIZE,
	Offset2_3OffsetGain_offset = Offset2_2OffsetGain_offset + WORD_SIZE,
	Gain_1OffsetGain_offset = Offset2_3OffsetGain_offset + WORD_SIZE,
	Gain_2OffsetGain_offset = Gain_1OffsetGain_offset + WORD_SIZE,
	Gain_3OffsetGain_offset = Gain_2OffsetGain_offset + WORD_SIZE,
	ChannelNumDisplayFlag_offset = Gain_3OffsetGain_offset + WORD_SIZE,
	ChannelNumAppendDisplayFlag_offset = ChannelNumDisplayFlag_offset + BYTE_SIZE,
	OsdScale100Percent_offset = ChannelNumAppendDisplayFlag_offset + BYTE_SIZE,
	OsdFullScreenXPercent_offset = OsdScale100Percent_offset + BYTE_SIZE,
	OsdFullScreenYPercent_offset = OsdFullScreenXPercent_offset + WORD_SIZE,
	OsdState_offset = OsdFullScreenYPercent_offset + WORD_SIZE,
	OsdBitFlags_offset = OsdState_offset + BYTE_SIZE,
	CurrentBlockedTVRatingSubcodeMain_offset = OsdBitFlags_offset + BYTE_SIZE,
	CurrentBlockedTVRatingSubcodePip_offset = CurrentBlockedTVRatingSubcodeMain_offset + BYTE_SIZE,
	MPipTileSet_offset = CurrentBlockedTVRatingSubcodePip_offset + BYTE_SIZE,
	ChipIDdigit1_offset = MPipTileSet_offset + BYTE_SIZE,
	ChipIDdigit2_offset = ChipIDdigit1_offset + BYTE_SIZE,
	ChipIDdigit3_offset = ChipIDdigit2_offset + BYTE_SIZE,
	ChipIDdigit4_offset = ChipIDdigit3_offset + BYTE_SIZE,
	ColorSystem_offset = ChipIDdigit4_offset + BYTE_SIZE,
	TtxNoSignalFlag_offset = ColorSystem_offset + BYTE_SIZE,
	GlobalInputPortListGroupInputPort_1InputPortList_offset = TtxNoSignalFlag_offset + BYTE_SIZE,
	GlobalInputPortListGroupInputPort_2InputPortList_offset = GlobalInputPortListGroupInputPort_1InputPortList_offset + BYTE_SIZE,
	GlobalInputPortListGroupInputPort_3InputPortList_offset = GlobalInputPortListGroupInputPort_2InputPortList_offset + BYTE_SIZE,
	GlobalInputPortListGroupInputPort_4InputPortList_offset = GlobalInputPortListGroupInputPort_3InputPortList_offset + BYTE_SIZE,
	GlobalInputPortListGroupInputPort_5InputPortList_offset = GlobalInputPortListGroupInputPort_4InputPortList_offset + BYTE_SIZE,
	InputPortCount_offset = GlobalInputPortListGroupInputPort_5InputPortList_offset + BYTE_SIZE,
	DisplayPortName_offset = InputPortCount_offset + BYTE_SIZE,
	OldOrNewPortChange_offset = DisplayPortName_offset + BYTE_SIZE,
	Str1_seg_offset = OldOrNewPortChange_offset + BYTE_SIZE,
	Str2_seg_offset = Str1_seg_offset + WORD_SIZE,
	Str3_seg_offset = Str2_seg_offset + WORD_SIZE,
	Str4_seg_offset = Str3_seg_offset + WORD_SIZE,
	Str1_ofs_offset = Str4_seg_offset + WORD_SIZE,
	Str2_ofs_offset = Str1_ofs_offset + WORD_SIZE,
	Str3_ofs_offset = Str2_ofs_offset + WORD_SIZE,
	Str4_ofs_offset = Str3_ofs_offset + WORD_SIZE,
	CecDeviceName_seg_offset = Str4_ofs_offset + WORD_SIZE,
	CecDeviceName_ofs_offset = CecDeviceName_seg_offset + WORD_SIZE,
	CecDeviceType_offset = CecDeviceName_ofs_offset + WORD_SIZE,
	DontRemoveOSD_offset = CecDeviceType_offset + BYTE_SIZE,
	CecRecordOnExtPlugNumber_offset = DontRemoveOSD_offset + BYTE_SIZE,
	CecDevicePowerStatus_offset = CecRecordOnExtPlugNumber_offset + BYTE_SIZE,
	CecStatusText1_seg_offset = CecDevicePowerStatus_offset + BYTE_SIZE,
	CecStatusText1_ofs_offset = CecStatusText1_seg_offset + WORD_SIZE,
	CecStatusText2_seg_offset = CecStatusText1_ofs_offset + WORD_SIZE,
	CecStatusText2_ofs_offset = CecStatusText2_seg_offset + WORD_SIZE,
	CecStatusText3_seg_offset = CecStatusText2_ofs_offset + WORD_SIZE,
	CecStatusText3_ofs_offset = CecStatusText3_seg_offset + WORD_SIZE,
	CecStatusLineCounter_offset = CecStatusText3_ofs_offset + WORD_SIZE,
	CecRecordDateDay_offset = CecStatusLineCounter_offset + BYTE_SIZE,
	CecRecordDateMonth_offset = CecRecordDateDay_offset + BYTE_SIZE,
	CecRecordTimeHours_offset = CecRecordDateMonth_offset + BYTE_SIZE,
	CecRecordTimeMinutes_offset = CecRecordTimeHours_offset + BYTE_SIZE,
	CecRecordDurationHours_offset = CecRecordTimeMinutes_offset + BYTE_SIZE,
	CecRecordDurationMinutes_offset = CecRecordDurationHours_offset + BYTE_SIZE,
	CecHDMITreeMode_offset = CecRecordDurationMinutes_offset + BYTE_SIZE,
	CecDeviceSelectedFromHDMITree_offset = CecHDMITreeMode_offset + BYTE_SIZE,
	CecSystemAudioStatus_offset = CecDeviceSelectedFromHDMITree_offset + BYTE_SIZE,
	IspFlashWrPercent_offset = CecSystemAudioStatus_offset + BYTE_SIZE,
	InFwMajor_offset = IspFlashWrPercent_offset + BYTE_SIZE,
	InFwMinor_offset = InFwMajor_offset + BYTE_SIZE,
	InFwRc_offset = InFwMinor_offset + BYTE_SIZE,
	GlobalOSD_temp_offset = InFwRc_offset + BYTE_SIZE,
	OSD_IR_offset = GlobalOSD_temp_offset + BYTE_SIZE,
	test1_offset = OSD_IR_offset + BYTE_SIZE,
	test2_offset = test1_offset + BYTE_SIZE,
	VIDEO_D_offset = test2_offset + BYTE_SIZE,
	BurnInMode_offset = VIDEO_D_offset + BYTE_SIZE,
	BurnInModeV_offset = BurnInMode_offset + BYTE_SIZE,
	GlobalTest_Pattern_offset = BurnInModeV_offset + BYTE_SIZE,
	LED_Setting_offset = GlobalTest_Pattern_offset + BYTE_SIZE,
	OutputTiming_offset = LED_Setting_offset + BYTE_SIZE
} GlobalOffsets;

extern GlobalUserPrefType  GlobalUserPreferences;

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct ModeDependentUserPrefTypeStruct
{
	WORD	HStart;
	WORD	VStart;
	WORD	HTotal;
	WORD	HSyncPhase;
	SWORD	HSyncDelay;
	SWORD	VSyncDelay;
} ModeDependentUserPrefType;

#define ModeDependentUserPrefSize		(sizeof(ModeDependentUserPrefType))

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

typedef enum 
{
	HStart_offset = 0,
	VStart_offset = HStart_offset + WORD_SIZE,
	HTotal_offset = VStart_offset + WORD_SIZE,
	HSyncPhase_offset = HTotal_offset + WORD_SIZE,
	HSyncDelay_offset = HSyncPhase_offset + WORD_SIZE,
	VSyncDelay_offset = HSyncDelay_offset + WORD_SIZE
} ModeDependentOffsets;

extern ModeDependentUserPrefType  ModeDependentUserPreferences;

#ifdef __PARADIGM__
#pragma pack(push)
#pragma pack(1)
#endif //__PARADIGM__

typedef struct PortSchemeDependentUserPrefTypeStruct
{
	SBYTE	Acm3BlueLuma;
	SBYTE	Acm3CyanLuma;
	SBYTE	Acm3GreenLuma;
	SBYTE	Acm3MagentaLuma;
	SBYTE	Acm3RedLuma;
	SBYTE	Acm3YellowLuma;
	SBYTE	Acm3BlackLuma;
	SBYTE	Acm3WhiteLuma;
	SBYTE	Acm3BlueHue;
	SBYTE	Acm3CyanHue;
	SBYTE	Acm3GreenHue;
	SBYTE	Acm3MagentaHue;
	SBYTE	Acm3RedHue;
	SBYTE	Acm3YellowHue;
	SBYTE	Acm3BlackHue;
	SBYTE	Acm3WhiteHue;
	SBYTE	Acm3BlueSat;
	SBYTE	Acm3CyanSat;
	SBYTE	Acm3GreenSat;
	SBYTE	Acm3MagentaSat;
	SBYTE	Acm3RedSat;
	SBYTE	Acm3YellowSat;
	SBYTE	Acm3BlackSat;
	SBYTE	Acm3WhiteSat;
	SBYTE	AcmBlueHue;
	SBYTE	AcmCyanHue;
	SBYTE	AcmGreenHue;
	SBYTE	AcmMagentaHue;
	SBYTE	AcmRedHue;
	SBYTE	AcmYellowHue;
	SBYTE	AcmBlueSat;
	SBYTE	AcmCyanSat;
	SBYTE	AcmGreenSat;
	SBYTE	AcmMagentaSat;
	SBYTE	AcmRedSat;
	SBYTE	AcmYellowSat;
	SBYTE	Brightness;
	WORD	Contrast;
	WORD	Saturation;
	SWORD	Hue;
	WORD	UserRedGain;
	WORD	UserGreenGain;
	WORD	UserBlueGain;
	SBYTE	UserRedOff;
	SBYTE	UserGreenOff;
	SBYTE	UserBlueOff;
	BYTE	ColorTemp;
	BYTE	GammaTable;
	BYTE	MFMImageScheme;
	BYTE	InputColorDomain;
	BYTE	OutputColorType;
	SBYTE	DUMSwitch;
} PortSchemeDependentUserPrefType;

#define PortSchemeDependentUserPrefSize		(sizeof(PortSchemeDependentUserPrefType))

#ifdef __PARADIGM__
#pragma pack(pop)
#endif //__PARADIGM__

typedef enum 
{
	Acm3BlueLuma_offset = 0,
	Acm3CyanLuma_offset = Acm3BlueLuma_offset + BYTE_SIZE,
	Acm3GreenLuma_offset = Acm3CyanLuma_offset + BYTE_SIZE,
	Acm3MagentaLuma_offset = Acm3GreenLuma_offset + BYTE_SIZE,
	Acm3RedLuma_offset = Acm3MagentaLuma_offset + BYTE_SIZE,
	Acm3YellowLuma_offset = Acm3RedLuma_offset + BYTE_SIZE,
	Acm3BlackLuma_offset = Acm3YellowLuma_offset + BYTE_SIZE,
	Acm3WhiteLuma_offset = Acm3BlackLuma_offset + BYTE_SIZE,
	Acm3BlueHue_offset = Acm3WhiteLuma_offset + BYTE_SIZE,
	Acm3CyanHue_offset = Acm3BlueHue_offset + BYTE_SIZE,
	Acm3GreenHue_offset = Acm3CyanHue_offset + BYTE_SIZE,
	Acm3MagentaHue_offset = Acm3GreenHue_offset + BYTE_SIZE,
	Acm3RedHue_offset = Acm3MagentaHue_offset + BYTE_SIZE,
	Acm3YellowHue_offset = Acm3RedHue_offset + BYTE_SIZE,
	Acm3BlackHue_offset = Acm3YellowHue_offset + BYTE_SIZE,
	Acm3WhiteHue_offset = Acm3BlackHue_offset + BYTE_SIZE,
	Acm3BlueSat_offset = Acm3WhiteHue_offset + BYTE_SIZE,
	Acm3CyanSat_offset = Acm3BlueSat_offset + BYTE_SIZE,
	Acm3GreenSat_offset = Acm3CyanSat_offset + BYTE_SIZE,
	Acm3MagentaSat_offset = Acm3GreenSat_offset + BYTE_SIZE,
	Acm3RedSat_offset = Acm3MagentaSat_offset + BYTE_SIZE,
	Acm3YellowSat_offset = Acm3RedSat_offset + BYTE_SIZE,
	Acm3BlackSat_offset = Acm3YellowSat_offset + BYTE_SIZE,
	Acm3WhiteSat_offset = Acm3BlackSat_offset + BYTE_SIZE,
	AcmBlueHue_offset = Acm3WhiteSat_offset + BYTE_SIZE,
	AcmCyanHue_offset = AcmBlueHue_offset + BYTE_SIZE,
	AcmGreenHue_offset = AcmCyanHue_offset + BYTE_SIZE,
	AcmMagentaHue_offset = AcmGreenHue_offset + BYTE_SIZE,
	AcmRedHue_offset = AcmMagentaHue_offset + BYTE_SIZE,
	AcmYellowHue_offset = AcmRedHue_offset + BYTE_SIZE,
	AcmBlueSat_offset = AcmYellowHue_offset + BYTE_SIZE,
	AcmCyanSat_offset = AcmBlueSat_offset + BYTE_SIZE,
	AcmGreenSat_offset = AcmCyanSat_offset + BYTE_SIZE,
	AcmMagentaSat_offset = AcmGreenSat_offset + BYTE_SIZE,
	AcmRedSat_offset = AcmMagentaSat_offset + BYTE_SIZE,
	AcmYellowSat_offset = AcmRedSat_offset + BYTE_SIZE,
	Brightness_offset = AcmYellowSat_offset + BYTE_SIZE,
	Contrast_offset = Brightness_offset + BYTE_SIZE,
	Saturation_offset = Contrast_offset + WORD_SIZE,
	Hue_offset = Saturation_offset + WORD_SIZE,
	UserRedGain_offset = Hue_offset + WORD_SIZE,
	UserGreenGain_offset = UserRedGain_offset + WORD_SIZE,
	UserBlueGain_offset = UserGreenGain_offset + WORD_SIZE,
	UserRedOff_offset = UserBlueGain_offset + WORD_SIZE,
	UserGreenOff_offset = UserRedOff_offset + BYTE_SIZE,
	UserBlueOff_offset = UserGreenOff_offset + BYTE_SIZE,
	ColorTemp_offset = UserBlueOff_offset + BYTE_SIZE,
	GammaTable_offset = ColorTemp_offset + BYTE_SIZE,
	MFMImageScheme_offset = GammaTable_offset + BYTE_SIZE,
	InputColorDomain_offset = MFMImageScheme_offset + BYTE_SIZE,
	OutputColorType_offset = InputColorDomain_offset + BYTE_SIZE,
	DUMSwitch_offset = OutputColorType_offset + BYTE_SIZE
} PortSchemeDependentOffsets;

extern PortSchemeDependentUserPrefType  PortSchemeDependentUserPreferences;

typedef enum 
{
	AGID_ModeIndependent = 0,
	AGID_Global = 1,
	AGID_ModeDependent = 2,
	AGID_PortSchemeDependent = 3
} AGID_Enum;


extern gmt_OSD_ADJUSTERS_MODE_SWITCHERS ROM gmv_OsdAdjusterModeSwitchers[];
extern gmt_OSD_ADJUSTERS_GROUP ROM gmv_OsdAdjustersGroupList[];

typedef enum 
{
	Digit1,
	Digit2,
	Digit3,
	Digit4,
	Digit5,
	Digit6,
	Digit7,
	Digit8
} CHANNELNAMEDIGIT;

typedef enum 
{
	BlockedChannel_1,
	BlockedChannel_2,
	BlockedChannel_3,
	BlockedChannel_4,
	BlockedChannel_5,
	BlockedChannel_6,
	BlockedChannel_7,
	BlockedChannel_8,
	BlockedChannel_9,
	BlockedChannel_10
} BLOCKEDCHANNELLIST;

typedef enum 
{
	Offset1_1,
	Offset1_2,
	Offset1_3,
	Offset2_1,
	Offset2_2,
	Offset2_3,
	Gain_1,
	Gain_2,
	Gain_3
} ADCOFFSETGAINLIST;

typedef enum 
{
	InputPort_1,
	InputPort_2,
	InputPort_3,
	InputPort_4,
	InputPort_5
} INPUTPORTLIST;

extern BYTE ChannelNameDigit;
extern BYTE BlockedChannelList;
extern BYTE ADCOffsetGainList;
extern BYTE InputPortList;

typedef enum 
{
	SWID_ChannelNameDigit,
	SWID_BlockedChannelList,
	SWID_ADCOffsetGainList,
	SWID_InputPortList
} ESwitchersEnum;

typedef enum 
{
	LANG_ID_0 = 0,
	LANG_English = 0,
	NUM_LANGUAGES = 1
} LangEnum;


#define UserPrefTNR ModeIndependentUserPreferences.TNR
#define UserPrefMADI ModeIndependentUserPreferences.MADI
#define UserPrefCCS ModeIndependentUserPreferences.CCS
#define UserPrefSharpNoise ModeIndependentUserPreferences.SharpNoise
#define UserPrefSplitScreen ModeIndependentUserPreferences.SplitScreen
#define UserPrefDCDiMain ModeIndependentUserPreferences.DCDiMain
#define UserPrefDCDiPip ModeIndependentUserPreferences.DCDiPip
#define UserPrefMPEGNRMode ModeIndependentUserPreferences.MPEGNRMode
#define UserPrefMPEGNRThresh0 ModeIndependentUserPreferences.MPEGNRThresh0
#define UserPrefMPEGNRThresh1 ModeIndependentUserPreferences.MPEGNRThresh1
#define UserPrefMPEGNRThresh2 ModeIndependentUserPreferences.MPEGNRThresh2
#define UserPrefLCDOverdriveNoiseCoring ModeIndependentUserPreferences.LCDOverdriveNoiseCoring
#define UserPrefThreeTwoFilmDisplayMode ModeIndependentUserPreferences.ThreeTwoFilmDisplayMode
#define UserPrefVBI_ServicePreferred ModeIndependentUserPreferences.VBI_ServicePreferred
#define UserPrefSharpnessPip ModeIndependentUserPreferences.SharpnessPip
#define UserPrefBlueStretch ModeIndependentUserPreferences.BlueStretch
#define UserPrefSharpnessRGB ModeIndependentUserPreferences.SharpnessRGB
#define UserPrefSharpnessRGBpip ModeIndependentUserPreferences.SharpnessRGBpip
#define UserPrefAVSDelay ModeIndependentUserPreferences.AVSDelay
#define UserPrefAudioVolume ModeIndependentUserPreferences.AudioVolume
#define UserPrefADCCalibrationMethod_Comp ModeIndependentUserPreferences.ADCCalibrationMethod_Comp
#define UserPrefADCCalibrationMethod_VGA ModeIndependentUserPreferences.ADCCalibrationMethod_VGA
#define UserPrefAspectRatioMain ModeIndependentUserPreferences.AspectRatioMain
#define UserPrefAspectRatioPip ModeIndependentUserPreferences.AspectRatioPip
#define UserPrefCurrentInputMain ModeIndependentUserPreferences.CurrentInputMain
#define UserPrefCurrentInputPip ModeIndependentUserPreferences.CurrentInputPip
#define UserPrefDynamicContrast ModeIndependentUserPreferences.DynamicContrast
#define UserPrefFilmMode ModeIndependentUserPreferences.FilmMode
#define UserPrefFleshToneComp ModeIndependentUserPreferences.FleshToneComp
#define UserPrefImageScheme ModeIndependentUserPreferences.ImageScheme
#define UserPrefLCDOverdrive ModeIndependentUserPreferences.LCDOverdrive
#define UserPrefLetterboxEnable ModeIndependentUserPreferences.LetterboxEnable
#define UserPrefMPEGNR ModeIndependentUserPreferences.MPEGNR
#define UserPrefOsdHPosition ModeIndependentUserPreferences.OsdHPosition
#define UserPrefOsdLanguage ModeIndependentUserPreferences.OsdLanguage
#define UserPrefOsdRotation ModeIndependentUserPreferences.OsdRotation
#define UserPrefOsdTimeout ModeIndependentUserPreferences.OsdTimeout
#define UserPrefOsdVPosition ModeIndependentUserPreferences.OsdVPosition
#define UserPrefOverscanEnable ModeIndependentUserPreferences.OverscanEnable
#define UserPrefPanelSelect ModeIndependentUserPreferences.PanelSelect
#define UserPrefPipMode ModeIndependentUserPreferences.PipMode
#define UserPrefPipPosition ModeIndependentUserPreferences.PipPosition
#define UserPrefPowerState ModeIndependentUserPreferences.PowerState
#define UserPrefSharpness ModeIndependentUserPreferences.Sharpness
#define UserPrefSleepAMPM ModeIndependentUserPreferences.SleepAMPM
#define UserPrefSleepDay ModeIndependentUserPreferences.SleepDay
#define UserPrefSleepHour ModeIndependentUserPreferences.SleepHour
#define UserPrefSleepMin ModeIndependentUserPreferences.SleepMin
#define UserPrefSleepMinsLeft ModeIndependentUserPreferences.SleepMinsLeft
#define UserPrefThreeDNR ModeIndependentUserPreferences.ThreeDNR
#define UserPrefTVRating ModeIndependentUserPreferences.TVRating
#define UserPrefTVUnrated ModeIndependentUserPreferences.TVUnrated
#define UserPrefVersion ModeIndependentUserPreferences.Version
#define UserPrefWakeAMPM ModeIndependentUserPreferences.WakeAMPM
#define UserPrefWakeDay ModeIndependentUserPreferences.WakeDay
#define UserPrefWakeHour ModeIndependentUserPreferences.WakeHour
#define UserPrefWakeMin ModeIndependentUserPreferences.WakeMin
#define UserPrefMPRating ModeIndependentUserPreferences.MPRating
#define UserPrefAVSDelayTime ModeIndependentUserPreferences.AVSDelayTime
#define UserPrefCC_On ModeIndependentUserPreferences.CC_On
#define UserPrefAudioMute ModeIndependentUserPreferences.AudioMute
#define UserPrefMPipConfig ModeIndependentUserPreferences.MPipConfig
#define UserPrefOSDSplashScreen ModeIndependentUserPreferences.OSDSplashScreen
#define UserPrefParentalPassword ModeIndependentUserPreferences.ParentalPassword
#define UserPrefPipSize ModeIndependentUserPreferences.PipSize
#define UserPrefPreviousInputMain ModeIndependentUserPreferences.PreviousInputMain
#define UserPrefScrollMenuItem ModeIndependentUserPreferences.ScrollMenuItem
#define UserPrefSplitLcdOverdrive ModeIndependentUserPreferences.SplitLcdOverdrive
#define UserPrefTTXLanguageGroup ModeIndependentUserPreferences.TTXLanguageGroup
#define UserPrefMainRouteModeComponent ModeIndependentUserPreferences.MainRouteModeComponent
#define UserPrefMainRouteModeScartRGB ModeIndependentUserPreferences.MainRouteModeScartRGB
#define UserPrefPipRouteModeComponent ModeIndependentUserPreferences.PipRouteModeComponent
#define UserPrefPipRouteModeScartRGB ModeIndependentUserPreferences.PipRouteModeScartRGB
#define UserPrefReg_MVF_SHARPNESS_LUMA ModeIndependentUserPreferences.Reg_MVF_SHARPNESS_LUMA
#define UserPrefReg_MVF_SHARPNESS_CHROMA ModeIndependentUserPreferences.Reg_MVF_SHARPNESS_CHROMA
#define UserPrefReg_MVF_NOISE_CORING_THRESH ModeIndependentUserPreferences.Reg_MVF_NOISE_CORING_THRESH
#define UserPrefReg_MVF_NONLINEAR_THRESH1 ModeIndependentUserPreferences.Reg_MVF_NONLINEAR_THRESH1
#define UserPrefReg_MVF_NONLINEAR_GAIN1 ModeIndependentUserPreferences.Reg_MVF_NONLINEAR_GAIN1
#define UserPrefReg_MVF_NONLINEAR_THRESH2 ModeIndependentUserPreferences.Reg_MVF_NONLINEAR_THRESH2
#define UserPrefReg_MVF_NONLINEAR_GAIN2 ModeIndependentUserPreferences.Reg_MVF_NONLINEAR_GAIN2
#define UserPrefReg_MHF_SHARPNESS_LUMA ModeIndependentUserPreferences.Reg_MHF_SHARPNESS_LUMA
#define UserPrefReg_MHF_SHARPNESS_CHROMA ModeIndependentUserPreferences.Reg_MHF_SHARPNESS_CHROMA
#define UserPrefReg_MHF_NOISE_CORING_THRESH ModeIndependentUserPreferences.Reg_MHF_NOISE_CORING_THRESH
#define UserPrefReg_MHF_NONLINEAR_THRESH1 ModeIndependentUserPreferences.Reg_MHF_NONLINEAR_THRESH1
#define UserPrefReg_MHF_NONLINEAR_GAIN1 ModeIndependentUserPreferences.Reg_MHF_NONLINEAR_GAIN1
#define UserPrefReg_MHF_NONLINEAR_THRESH2 ModeIndependentUserPreferences.Reg_MHF_NONLINEAR_THRESH2
#define UserPrefReg_MHF_NONLINEAR_GAIN2 ModeIndependentUserPreferences.Reg_MHF_NONLINEAR_GAIN2
#define UserPrefReg_PVF_SHARPNESS_LUMA ModeIndependentUserPreferences.Reg_PVF_SHARPNESS_LUMA
#define UserPrefReg_PVF_SHARPNESS_CHROMA ModeIndependentUserPreferences.Reg_PVF_SHARPNESS_CHROMA
#define UserPrefReg_PVF_NOISE_CORING_THRESH ModeIndependentUserPreferences.Reg_PVF_NOISE_CORING_THRESH
#define UserPrefReg_PVF_NONLINEAR_THRESH1 ModeIndependentUserPreferences.Reg_PVF_NONLINEAR_THRESH1
#define UserPrefReg_PVF_NONLINEAR_GAIN1 ModeIndependentUserPreferences.Reg_PVF_NONLINEAR_GAIN1
#define UserPrefReg_PVF_NONLINEAR_THRESH2 ModeIndependentUserPreferences.Reg_PVF_NONLINEAR_THRESH2
#define UserPrefReg_PVF_NONLINEAR_GAIN2 ModeIndependentUserPreferences.Reg_PVF_NONLINEAR_GAIN2
#define UserPrefReg_PHF_SHARPNESS_LUMA ModeIndependentUserPreferences.Reg_PHF_SHARPNESS_LUMA
#define UserPrefReg_PHF_SHARPNESS_CHROMA ModeIndependentUserPreferences.Reg_PHF_SHARPNESS_CHROMA
#define UserPrefReg_PHF_NOISE_CORING_THRESH ModeIndependentUserPreferences.Reg_PHF_NOISE_CORING_THRESH
#define UserPrefReg_PHF_NONLINEAR_THRESH1 ModeIndependentUserPreferences.Reg_PHF_NONLINEAR_THRESH1
#define UserPrefReg_PHF_NONLINEAR_GAIN1 ModeIndependentUserPreferences.Reg_PHF_NONLINEAR_GAIN1
#define UserPrefReg_PHF_NONLINEAR_THRESH2 ModeIndependentUserPreferences.Reg_PHF_NONLINEAR_THRESH2
#define UserPrefReg_PHF_NONLINEAR_GAIN2 ModeIndependentUserPreferences.Reg_PHF_NONLINEAR_GAIN2
#define UserPrefReg_HEM_HLE_THR ModeIndependentUserPreferences.Reg_HEM_HLE_THR
#define UserPrefReg_HEM_HLE_GAIN ModeIndependentUserPreferences.Reg_HEM_HLE_GAIN
#define UserPrefReg_HEM_HDP_THR ModeIndependentUserPreferences.Reg_HEM_HDP_THR
#define UserPrefReg_HEM_HDP_GAIN ModeIndependentUserPreferences.Reg_HEM_HDP_GAIN
#define UserPrefReg_HEM_CE_THR ModeIndependentUserPreferences.Reg_HEM_CE_THR
#define UserPrefReg_HEM_CE_GAIN ModeIndependentUserPreferences.Reg_HEM_CE_GAIN
#define UserPrefReg_VDP_THRESHOLD ModeIndependentUserPreferences.Reg_VDP_THRESHOLD
#define UserPrefReg_VDP_GAIN ModeIndependentUserPreferences.Reg_VDP_GAIN
#define UserPrefNativeMode ModeIndependentUserPreferences.NativeMode
#define UserPrefYUV2RGBExpansionMode ModeIndependentUserPreferences.YUV2RGBExpansionMode
#define UserPrefNonACMFleshtoneCorrection ModeIndependentUserPreferences.NonACMFleshtoneCorrection
#define UserPrefNonACMFleshtoneBalance ModeIndependentUserPreferences.NonACMFleshtoneBalance
#define UserPrefNonACMFleshtoneCorrectionLevel ModeIndependentUserPreferences.NonACMFleshtoneCorrectionLevel
#define UserPrefTVYouth7Subcode ModeIndependentUserPreferences.UserPrefTVYouth7Subcode
#define UserPrefTVPGSubcode ModeIndependentUserPreferences.UserPrefTVPGSubcode
#define UserPrefTV14Subcode ModeIndependentUserPreferences.UserPrefTV14Subcode
#define UserPrefTVMASubcode ModeIndependentUserPreferences.UserPrefTVMASubcode
#define UserPrefDecoderAGCMethod ModeIndependentUserPreferences.DecoderAGCMethod
#define UserPrefCCSforHD ModeIndependentUserPreferences.CCSforHD
#define UserPrefTwoStageProcessing ModeIndependentUserPreferences.TwoStageProcessing
#define UserPrefManualTVMHzFreq ModeIndependentUserPreferences.ManualTVMHzFreq
#define UserPrefManualTVkHzFreq ModeIndependentUserPreferences.ManualTVkHzFreq
#define UserPrefTVFreqFineTune ModeIndependentUserPreferences.TVFreqFineTune
#define UserPrefTVManualScanRequired ModeIndependentUserPreferences.TVManualScanRequired
#define UserPrefScartRgbViaOverlay ModeIndependentUserPreferences.UserPrefScartRgbViaOverlay
#define UserPrefADCCalibrationMethod_CVBS ModeIndependentUserPreferences.ADCCalibrationMethod_CVBS
#define UserPrefADCCalibrationMethod_InternalDac ModeIndependentUserPreferences.ADCCalibrationMethod_InternalDac
#define UserPrefAutoAspectRatio ModeIndependentUserPreferences.AutoAspectRatio
#define UserPrefADCCalibrationMethod_SCART ModeIndependentUserPreferences.ADCCalibrationMethod_SCART
#define UserPrefReg_MHF_ENH_Y_LSHOOT_TOL ModeIndependentUserPreferences.Reg_MHF_ENH_Y_LSHOOT_TOL
#define UserPrefReg_MHF_ENH_Y_SSHOOT_TOL ModeIndependentUserPreferences.Reg_MHF_ENH_Y_SSHOOT_TOL
#define UserPrefReg_MHF_ENH_Y_LGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_Y_LGAIN
#define UserPrefReg_MHF_ENH_Y_SGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_Y_SGAIN
#define UserPrefReg_MHF_ENH_Y_FINALSGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_Y_FINALSGAIN
#define UserPrefReg_MHF_ENH_Y_FINALLGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_Y_FINALLGAIN
#define UserPrefReg_MHF_ENH_Y_FINALGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_Y_FINALGAIN
#define UserPrefReg_MHF_ENH_Y_DELTA ModeIndependentUserPreferences.Reg_MHF_ENH_Y_DELTA
#define UserPrefReg_MHF_ENH_Y_SLOPE ModeIndependentUserPreferences.Reg_MHF_ENH_Y_SLOPE
#define UserPrefReg_MHF_ENH_Y_THRESH ModeIndependentUserPreferences.Reg_MHF_ENH_Y_THRESH
#define UserPrefReg_MHF_ENH_Y_HIGH_SLOPE_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_Y_HIGH_SLOPE_AGC
#define UserPrefReg_MHF_ENH_Y_LOW_SLOPE_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_Y_LOW_SLOPE_AGC
#define UserPrefReg_MHF_ENH_Y_HIGH_THRESH_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_Y_HIGH_THRESH_AGC
#define UserPrefReg_MHF_ENH_Y_LOW_THRESH_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_Y_LOW_THRESH_AGC
#define UserPrefReg_MHF_ENH_UV_LSHOOT_TOL ModeIndependentUserPreferences.Reg_MHF_ENH_UV_LSHOOT_TOL
#define UserPrefReg_MHF_ENH_UV_SSHOOT_TOL ModeIndependentUserPreferences.Reg_MHF_ENH_UV_SSHOOT_TOL
#define UserPrefReg_MHF_ENH_UV_LGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_UV_LGAIN
#define UserPrefReg_MHF_ENH_UV_SGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_UV_SGAIN
#define UserPrefReg_MHF_ENH_UV_FINALSGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_UV_FINALSGAIN
#define UserPrefReg_MHF_ENH_UV_FINALLGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_UV_FINALLGAIN
#define UserPrefReg_MHF_ENH_UV_FINALGAIN ModeIndependentUserPreferences.Reg_MHF_ENH_UV_FINALGAIN
#define UserPrefReg_MHF_ENH_UV_DELTA ModeIndependentUserPreferences.Reg_MHF_ENH_UV_DELTA
#define UserPrefReg_MHF_ENH_UV_SLOPE ModeIndependentUserPreferences.Reg_MHF_ENH_UV_SLOPE
#define UserPrefReg_MHF_ENH_UV_THRESH ModeIndependentUserPreferences.Reg_MHF_ENH_UV_THRESH
#define UserPrefReg_MHF_ENH_UV_HIGH_SLOPE_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_UV_HIGH_SLOPE_AGC
#define UserPrefReg_MHF_ENH_UV_LOW_SLOPE_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_UV_LOW_SLOPE_AGC
#define UserPrefReg_MHF_ENH_UV_HIGH_THRESH_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_UV_HIGH_THRESH_AGC
#define UserPrefReg_MHF_ENH_UV_LOW_THRESH_AGC ModeIndependentUserPreferences.Reg_MHF_ENH_UV_LOW_THRESH_AGC
#define UserPrefReg_MVF_ENH_Y_LSHOOT_TOL ModeIndependentUserPreferences.Reg_MVF_ENH_Y_LSHOOT_TOL
#define UserPrefReg_MVF_ENH_Y_SSHOOT_TOL ModeIndependentUserPreferences.Reg_MVF_ENH_Y_SSHOOT_TOL
#define UserPrefReg_MVF_ENH_Y_LGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_Y_LGAIN
#define UserPrefReg_MVF_ENH_Y_SGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_Y_SGAIN
#define UserPrefReg_MVF_ENH_Y_FINALSGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_Y_FINALSGAIN
#define UserPrefReg_MVF_ENH_Y_FINALLGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_Y_FINALLGAIN
#define UserPrefReg_MVF_ENH_Y_FINALGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_Y_FINALGAIN
#define UserPrefReg_MVF_ENH_Y_DELTA ModeIndependentUserPreferences.Reg_MVF_ENH_Y_DELTA
#define UserPrefReg_MVF_ENH_Y_SLOPE ModeIndependentUserPreferences.Reg_MVF_ENH_Y_SLOPE
#define UserPrefReg_MVF_ENH_Y_THRESH ModeIndependentUserPreferences.Reg_MVF_ENH_Y_THRESH
#define UserPrefReg_MVF_ENH_Y_HIGH_SLOPE_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_Y_HIGH_SLOPE_AGC
#define UserPrefReg_MVF_ENH_Y_LOW_SLOPE_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_Y_LOW_SLOPE_AGC
#define UserPrefReg_MVF_ENH_Y_HIGH_THRESH_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_Y_HIGH_THRESH_AGC
#define UserPrefReg_MVF_ENH_Y_LOW_THRESH_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_Y_LOW_THRESH_AGC
#define UserPrefReg_MVF_ENH_UV_LSHOOT_TOL ModeIndependentUserPreferences.Reg_MVF_ENH_UV_LSHOOT_TOL
#define UserPrefReg_MVF_ENH_UV_SSHOOT_TOL ModeIndependentUserPreferences.Reg_MVF_ENH_UV_SSHOOT_TOL
#define UserPrefReg_MVF_ENH_UV_LGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_UV_LGAIN
#define UserPrefReg_MVF_ENH_UV_SGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_UV_SGAIN
#define UserPrefReg_MVF_ENH_UV_FINALSGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_UV_FINALSGAIN
#define UserPrefReg_MVF_ENH_UV_FINALLGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_UV_FINALLGAIN
#define UserPrefReg_MVF_ENH_UV_FINALGAIN ModeIndependentUserPreferences.Reg_MVF_ENH_UV_FINALGAIN
#define UserPrefReg_MVF_ENH_UV_DELTA ModeIndependentUserPreferences.Reg_MVF_ENH_UV_DELTA
#define UserPrefReg_MVF_ENH_UV_SLOPE ModeIndependentUserPreferences.Reg_MVF_ENH_UV_SLOPE
#define UserPrefReg_MVF_ENH_UV_THRESH ModeIndependentUserPreferences.Reg_MVF_ENH_UV_THRESH
#define UserPrefReg_MVF_ENH_UV_HIGH_SLOPE_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_UV_HIGH_SLOPE_AGC
#define UserPrefReg_MVF_ENH_UV_LOW_SLOPE_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_UV_LOW_SLOPE_AGC
#define UserPrefReg_MVF_ENH_UV_HIGH_THRESH_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_UV_HIGH_THRESH_AGC
#define UserPrefReg_MVF_ENH_UV_LOW_THRESH_AGC ModeIndependentUserPreferences.Reg_MVF_ENH_UV_LOW_THRESH_AGC
#define UserPrefEnhancerEnable ModeIndependentUserPreferences.EnhancerEnable
#define UserPrefOldEnhancerEnable ModeIndependentUserPreferences.OldEnhancerEnable
#define UserPrefOldEnhancerRouting ModeIndependentUserPreferences.OldEnhancerRouting
#define UserPrefColorResourceRouting ModeIndependentUserPreferences.ColorResourceRouting
#define UserPrefADCCalibrationMethod_SIF ModeIndependentUserPreferences.ADCCalibrationMethod_SIF
#define UserPrefImpVlut ModeIndependentUserPreferences.ImpVlut
#define UserPrefVariableForLineout ModeIndependentUserPreferences.LineoutVariable
#define UserPrefGameMode ModeIndependentUserPreferences.UserPrefGameFlag
#define UserPrefXvYcc ModeIndependentUserPreferences.UserPrefXvYcc
#define UserPrefDCR ModeIndependentUserPreferences.UserPrefDCRFlag
#define UserPrefXNumber ModeIndependentUserPreferences.XNumber
#define UserPrefYNumber ModeIndependentUserPreferences.YNumber
#define UserPrefPublicDisplayNumber ModeIndependentUserPreferences.PublicDisplayNumber
#define UserPrefAudioDownMix ModeIndependentUserPreferences.AudioDownMix
#define UserPrefColorSpace ModeIndependentUserPreferences.ColorSpace
#define UserPrefVwdFlag ModeIndependentUserPreferences.VwdFlag
#define UserPrefVwdDemo ModeIndependentUserPreferences.VwdDemo
#define UserPrefAudioMainInput ModeIndependentUserPreferences.AudioMainInput
#define UserPrefAudioMainOutput ModeIndependentUserPreferences.AudioMainOutput
#define UserPrefAudioPipInput ModeIndependentUserPreferences.AudioPipInput
#define UserPrefAudioPipOutput ModeIndependentUserPreferences.AudioPipOutput
#define UserPrefOSDG1Blend ModeIndependentUserPreferences.OSD_G1_Blend
#define UserPrefOSDG2Blend ModeIndependentUserPreferences.OSD_G2_Blend
#define UserPrefOSDG3Blend ModeIndependentUserPreferences.OSD_G3_Blend
#define UserPrefCaptureM ModeIndependentUserPreferences.CaptureM
#define UserPrefImageRotation ModeIndependentUserPreferences.ImageRotation
#define UserPrefOSD_4Kx2K_Port ModeIndependentUserPreferences.OSD_4Kx2K_Port
#define UserPrefDPSWitch ModeIndependentUserPreferences.DPSWitch
#define UserPrefBackLight ModeIndependentUserPreferences.BackLight
#define UserPrefOsdBlend ModeIndependentUserPreferences.OsdBlend
#define UserPrefFanStatus ModeIndependentUserPreferences.FanStatus
#define UserPrefPIPHPos ModeIndependentUserPreferences.PIPHPos
#define UserPrefPIPVPos ModeIndependentUserPreferences.PIPVPos
#define UserPrefPipModeOnOff ModeIndependentUserPreferences.PipModeOnOff
#define UserPrefScheduleOnOff ModeIndependentUserPreferences.ScheduleOnOff
#define UserPrefOverScan ModeIndependentUserPreferences.OverScan
#define UserPrefAutoBLState ModeIndependentUserPreferences.AutoBLState
#define UserPrefMinBrightness ModeIndependentUserPreferences.MinBrightness
#define UserPrefAUTOADJUST ModeIndependentUserPreferences.AUTOADJUST
#define UserPrefDisplayPos ModeIndependentUserPreferences.DisplayPos
#define UserPrefModeIndependent ModeIndependentUserPreferences
#define UserPrefParentalBlockStateFlagMain GlobalUserPreferences.ParentalBlockStateFlagMain
#define UserPrefParentalBlockStateFlagPip GlobalUserPreferences.ParentalBlockStateFlagPip
#define UserPrefChannelBlockStateFlag GlobalUserPreferences.ChannelBlockStateFlag
#define UserPrefChannelBlockStateFlagPip GlobalUserPreferences.ChannelBlockStateFlagPip
#define UserPrefChannelName GlobalUserPreferences.ChannelNameGroup[ChannelNameDigit].ChannelName
#define UserPrefDigit1ChannelName GlobalUserPreferences.ChannelNameGroup[Digit1].ChannelName
#define UserPrefDigit2ChannelName GlobalUserPreferences.ChannelNameGroup[Digit2].ChannelName
#define UserPrefDigit3ChannelName GlobalUserPreferences.ChannelNameGroup[Digit3].ChannelName
#define UserPrefDigit4ChannelName GlobalUserPreferences.ChannelNameGroup[Digit4].ChannelName
#define UserPrefDigit5ChannelName GlobalUserPreferences.ChannelNameGroup[Digit5].ChannelName
#define UserPrefDigit6ChannelName GlobalUserPreferences.ChannelNameGroup[Digit6].ChannelName
#define UserPrefDigit7ChannelName GlobalUserPreferences.ChannelNameGroup[Digit7].ChannelName
#define UserPrefDigit8ChannelName GlobalUserPreferences.ChannelNameGroup[Digit8].ChannelName
#define UserPrefChannelNameGroup GlobalUserPreferences.ChannelNameGroup[ChannelNameDigit]
#define UserPrefFreeze GlobalUserPreferences.Freeze
#define UserPrefMultiPipStateFlag GlobalUserPreferences.MultiPipStateFlag
#define UserPrefOsdMPipHPos GlobalUserPreferences.OsdMPipHPos
#define UserPrefOsdMPipVPos GlobalUserPreferences.OsdMPipVPos
#define UserPrefOsdMPipChannel GlobalUserPreferences.OsdMPipChannel
#define UserPrefSideBySideFocus GlobalUserPreferences.SideBySideFocus
#define UserPrefOSDBottomPos GlobalUserPreferences.OSDBottomPos
#define UserPrefOSDCenterPos GlobalUserPreferences.OSDCenterPos
#define UserPrefParentalMenuAccess GlobalUserPreferences.ParentalMenuAccess
#define UserPrefVChipPassword GlobalUserPreferences.VChipPassword
#define UserPrefMonth GlobalUserPreferences.Month
#define UserPrefDate GlobalUserPreferences.Date
#define UserPrefYear GlobalUserPreferences.Year
#define UserPrefHour GlobalUserPreferences.Hour
#define UserPrefMin GlobalUserPreferences.Min
#define UserPrefAMPM GlobalUserPreferences.AMPM
#define UserPrefInfoDisplayOn GlobalUserPreferences.InfoDisplayOn
#define UserPrefPrevPipSource GlobalUserPreferences.PrevPipSource
#define UserPrefChannelFreqSlider GlobalUserPreferences.ChannelFreqSlider
#define UserPrefChannelFreqValue GlobalUserPreferences.ChannelFreqValue
#define UserPrefFactoryState GlobalUserPreferences.FactoryState
#define UserPrefTempVar GlobalUserPreferences.TempVar
#define UserPrefRegAddr GlobalUserPreferences.RegAddr
#define UserPrefRegVal GlobalUserPreferences.RegVal
#define UserPrefPreviousPipMode GlobalUserPreferences.PreviousPipMode
#define UserPrefChannelNameEntry1 GlobalUserPreferences.ChannelNameEntry1
#define UserPrefChannelNameEntry2 GlobalUserPreferences.ChannelNameEntry2
#define UserPrefChannelNameEntry3 GlobalUserPreferences.ChannelNameEntry3
#define UserPrefChannelNameEntry4 GlobalUserPreferences.ChannelNameEntry4
#define UserPrefChannelNameEntry5 GlobalUserPreferences.ChannelNameEntry5
#define UserPrefPtrSegment GlobalUserPreferences.PtrSegment
#define UserPrefPtrOffset GlobalUserPreferences.PtrOffset
#define UserPrefBlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannelList].BlockedChannelList
#define UserPrefBlockedChannel_1BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_1].BlockedChannelList
#define UserPrefBlockedChannel_2BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_2].BlockedChannelList
#define UserPrefBlockedChannel_3BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_3].BlockedChannelList
#define UserPrefBlockedChannel_4BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_4].BlockedChannelList
#define UserPrefBlockedChannel_5BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_5].BlockedChannelList
#define UserPrefBlockedChannel_6BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_6].BlockedChannelList
#define UserPrefBlockedChannel_7BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_7].BlockedChannelList
#define UserPrefBlockedChannel_8BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_8].BlockedChannelList
#define UserPrefBlockedChannel_9BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_9].BlockedChannelList
#define UserPrefBlockedChannel_10BlockedChannelList GlobalUserPreferences.BlockChannelListGroup[BlockedChannel_10].BlockedChannelList
#define UserPrefBlockChannelListGroup GlobalUserPreferences.BlockChannelListGroup[BlockedChannelList]
#define UserPrefOffsetGain GlobalUserPreferences.ADCOffsetGainGroup[ADCOffsetGainList].OffsetGain
#define UserPrefOffset1_1OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Offset1_1].OffsetGain
#define UserPrefOffset1_2OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Offset1_2].OffsetGain
#define UserPrefOffset1_3OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Offset1_3].OffsetGain
#define UserPrefOffset2_1OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Offset2_1].OffsetGain
#define UserPrefOffset2_2OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Offset2_2].OffsetGain
#define UserPrefOffset2_3OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Offset2_3].OffsetGain
#define UserPrefGain_1OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Gain_1].OffsetGain
#define UserPrefGain_2OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Gain_2].OffsetGain
#define UserPrefGain_3OffsetGain GlobalUserPreferences.ADCOffsetGainGroup[Gain_3].OffsetGain
#define UserPrefADCOffsetGainGroup GlobalUserPreferences.ADCOffsetGainGroup[ADCOffsetGainList]
#define UserPrefChannelNumDisplayFlag GlobalUserPreferences.ChannelNumDisplayFlag
#define UserPrefChannelNumAppendDisplayFlag GlobalUserPreferences.ChannelNumAppendDisplayFlag
#define UserPrefOsdScale100Percent GlobalUserPreferences.OsdScale100Percent
#define UserPrefOsdFullScreenXPercent GlobalUserPreferences.OsdFullScreenXPercent
#define UserPrefOsdFullScreenYPercent GlobalUserPreferences.OsdFullScreenYPercent
#define UserPrefOsdState GlobalUserPreferences.OsdState
#define UserPrefOsdBitFlags GlobalUserPreferences.OsdBitFlags
#define UserPrefCurrentBlockedTVRatingSubcodeMain GlobalUserPreferences.CurrentBlockedTVRatingSubcodeMain
#define UserPrefCurrentBlockedTVRatingSubcodePip GlobalUserPreferences.CurrentBlockedTVRatingSubcodePip
#define UserPrefMPipTileSet GlobalUserPreferences.MPipTileSet
#define UserPrefChipIDdigit1 GlobalUserPreferences.ChipIDdigit1
#define UserPrefChipIDdigit2 GlobalUserPreferences.ChipIDdigit2
#define UserPrefChipIDdigit3 GlobalUserPreferences.ChipIDdigit3
#define UserPrefChipIDdigit4 GlobalUserPreferences.ChipIDdigit4
#define UserPrefColorSystem GlobalUserPreferences.ColorSystem
#define UserPrefTtxNoSignalFlag GlobalUserPreferences.TtxNoSignalFlag
#define UserPrefInputPortList GlobalUserPreferences.InputPortListGroup[InputPortList].InputPortList
#define UserPrefGlobalInputPortListGroupInputPort_1InputPortList GlobalUserPreferences.InputPortListGroup[InputPort_1].InputPortList
#define UserPrefGlobalInputPortListGroupInputPort_2InputPortList GlobalUserPreferences.InputPortListGroup[InputPort_2].InputPortList
#define UserPrefGlobalInputPortListGroupInputPort_3InputPortList GlobalUserPreferences.InputPortListGroup[InputPort_3].InputPortList
#define UserPrefGlobalInputPortListGroupInputPort_4InputPortList GlobalUserPreferences.InputPortListGroup[InputPort_4].InputPortList
#define UserPrefGlobalInputPortListGroupInputPort_5InputPortList GlobalUserPreferences.InputPortListGroup[InputPort_5].InputPortList
#define UserPrefGlobalInputPortListGroup GlobalUserPreferences.InputPortListGroup[InputPortList]
#define UserPrefInputPortCount GlobalUserPreferences.InputPortCount
#define UserPrefDisplayPortName GlobalUserPreferences.DisplayPortName
#define UserPrefOldOrNewPortChange GlobalUserPreferences.OldOrNewPortChange
#define UserPrefStr1_seg GlobalUserPreferences.Str1_seg
#define UserPrefStr2_seg GlobalUserPreferences.Str2_seg
#define UserPrefStr3_seg GlobalUserPreferences.Str3_seg
#define UserPrefStr4_seg GlobalUserPreferences.Str4_seg
#define UserPrefStr1_ofs GlobalUserPreferences.Str1_ofs
#define UserPrefStr2_ofs GlobalUserPreferences.Str2_ofs
#define UserPrefStr3_ofs GlobalUserPreferences.Str3_ofs
#define UserPrefStr4_ofs GlobalUserPreferences.Str4_ofs
#define UserPrefCecDeviceName_seg GlobalUserPreferences.CecDeviceName_seg
#define UserPrefCecDeviceName_ofs GlobalUserPreferences.CecDeviceName_ofs
#define UserPrefCecDeviceType GlobalUserPreferences.CecDeviceType
#define UserPrefDontRemoveOSD GlobalUserPreferences.DontRemoveOSD
#define UserPrefCecRecordOnExtPlugNumber GlobalUserPreferences.CecRecordOnExtPlugNumber
#define UserPrefCecDevicePowerStatus GlobalUserPreferences.CecDevicePowerStatus
#define UserPrefCecStatusText1_seg GlobalUserPreferences.CecStatusText1_seg
#define UserPrefCecStatusText1_ofs GlobalUserPreferences.CecStatusText1_ofs
#define UserPrefCecStatusText2_seg GlobalUserPreferences.CecStatusText2_seg
#define UserPrefCecStatusText2_ofs GlobalUserPreferences.CecStatusText2_ofs
#define UserPrefCecStatusText3_seg GlobalUserPreferences.CecStatusText3_seg
#define UserPrefCecStatusText3_ofs GlobalUserPreferences.CecStatusText3_ofs
#define UserPrefCecStatusLineCounter GlobalUserPreferences.CecStatusLineCounter
#define UserPrefCecRecordDateDay GlobalUserPreferences.CecRecordDateDay
#define UserPrefCecRecordDateMonth GlobalUserPreferences.CecRecordDateMonth
#define UserPrefCecRecordTimeHours GlobalUserPreferences.CecRecordTimeHours
#define UserPrefCecRecordTimeMinutes GlobalUserPreferences.CecRecordTimeMinutes
#define UserPrefCecRecordDurationHours GlobalUserPreferences.CecRecordDurationHours
#define UserPrefCecRecordDurationMinutes GlobalUserPreferences.CecRecordDurationMinutes
#define UserPrefCecHDMITreeMode GlobalUserPreferences.CecHDMITreeMode
#define UserPrefCecDeviceSelectedFromHDMITree GlobalUserPreferences.CecDeviceSelectedFromHDMITree
#define UserPrefCecSystemAudioStatus GlobalUserPreferences.CecSystemAudioStatus
#define UserPrefIspFlashWrPercent GlobalUserPreferences.IspWrPercent
#define UserPrefInFwMajor GlobalUserPreferences.InFwMajor
#define UserPrefInFwMinor GlobalUserPreferences.InFwMinor
#define UserPrefInFwRc GlobalUserPreferences.InFwRc
#define UserPrefGlobalOSD_temp GlobalUserPreferences.OSD_temp
#define UserPrefOSD_IR GlobalUserPreferences.OSD_IR
#define UserPreftest1 GlobalUserPreferences.test1
#define UserPreftest2 GlobalUserPreferences.test2
#define UserPrefVIDEO_D GlobalUserPreferences.VIDEO_D
#define UserPrefBurnInMode GlobalUserPreferences.BurnInMode
#define UserPrefBurnInModeV GlobalUserPreferences.BurnInModeV
#define UserPrefGlobalTest_Pattern GlobalUserPreferences.Test_Pattern
#define UserPrefLED_Setting GlobalUserPreferences.LED_Setting
#define UserPrefOutputTiming GlobalUserPreferences.OutputTiming
#define UserPrefGlobal GlobalUserPreferences
#define UserPrefHStart ModeDependentUserPreferences.HStart
#define UserPrefVStart ModeDependentUserPreferences.VStart
#define UserPrefHTotal ModeDependentUserPreferences.HTotal
#define UserPrefHSyncPhase ModeDependentUserPreferences.HSyncPhase
#define UserPrefHSyncDelay ModeDependentUserPreferences.HSyncDelay
#define UserPrefVSyncDelay ModeDependentUserPreferences.VSyncDelay
#define UserPrefModeDependent ModeDependentUserPreferences
#define UserPrefAcm3BlueLuma PortSchemeDependentUserPreferences.Acm3BlueLuma
#define UserPrefAcm3CyanLuma PortSchemeDependentUserPreferences.Acm3CyanLuma
#define UserPrefAcm3GreenLuma PortSchemeDependentUserPreferences.Acm3GreenLuma
#define UserPrefAcm3MagentaLuma PortSchemeDependentUserPreferences.Acm3MagentaLuma
#define UserPrefAcm3RedLuma PortSchemeDependentUserPreferences.Acm3RedLuma
#define UserPrefAcm3YellowLuma PortSchemeDependentUserPreferences.Acm3YellowLuma
#define UserPrefAcm3BlackLuma PortSchemeDependentUserPreferences.Acm3BlackLuma
#define UserPrefAcm3WhiteLuma PortSchemeDependentUserPreferences.Acm3WhiteLuma
#define UserPrefAcm3BlueHue PortSchemeDependentUserPreferences.Acm3BlueHue
#define UserPrefAcm3CyanHue PortSchemeDependentUserPreferences.Acm3CyanHue
#define UserPrefAcm3GreenHue PortSchemeDependentUserPreferences.Acm3GreenHue
#define UserPrefAcm3MagentaHue PortSchemeDependentUserPreferences.Acm3MagentaHue
#define UserPrefAcm3RedHue PortSchemeDependentUserPreferences.Acm3RedHue
#define UserPrefAcm3YellowHue PortSchemeDependentUserPreferences.Acm3YellowHue
#define UserPrefAcm3BlackHue PortSchemeDependentUserPreferences.Acm3BlackHue
#define UserPrefAcm3WhiteHue PortSchemeDependentUserPreferences.Acm3WhiteHue
#define UserPrefAcm3BlueSat PortSchemeDependentUserPreferences.Acm3BlueSat
#define UserPrefAcm3CyanSat PortSchemeDependentUserPreferences.Acm3CyanSat
#define UserPrefAcm3GreenSat PortSchemeDependentUserPreferences.Acm3GreenSat
#define UserPrefAcm3MagentaSat PortSchemeDependentUserPreferences.Acm3MagentaSat
#define UserPrefAcm3RedSat PortSchemeDependentUserPreferences.Acm3RedSat
#define UserPrefAcm3YellowSat PortSchemeDependentUserPreferences.Acm3YellowSat
#define UserPrefAcm3BlackSat PortSchemeDependentUserPreferences.Acm3BlackSat
#define UserPrefAcm3WhiteSat PortSchemeDependentUserPreferences.Acm3WhiteSat
#define UserPrefAcmBlueHue PortSchemeDependentUserPreferences.AcmBlueHue
#define UserPrefAcmCyanHue PortSchemeDependentUserPreferences.AcmCyanHue
#define UserPrefAcmGreenHue PortSchemeDependentUserPreferences.AcmGreenHue
#define UserPrefAcmMagentaHue PortSchemeDependentUserPreferences.AcmMagentaHue
#define UserPrefAcmRedHue PortSchemeDependentUserPreferences.AcmRedHue
#define UserPrefAcmYellowHue PortSchemeDependentUserPreferences.AcmYellowHue
#define UserPrefAcmBlueSat PortSchemeDependentUserPreferences.AcmBlueSat
#define UserPrefAcmCyanSat PortSchemeDependentUserPreferences.AcmCyanSat
#define UserPrefAcmGreenSat PortSchemeDependentUserPreferences.AcmGreenSat
#define UserPrefAcmMagentaSat PortSchemeDependentUserPreferences.AcmMagentaSat
#define UserPrefAcmRedSat PortSchemeDependentUserPreferences.AcmRedSat
#define UserPrefAcmYellowSat PortSchemeDependentUserPreferences.AcmYellowSat
#define UserPrefBrightness PortSchemeDependentUserPreferences.Brightness
#define UserPrefContrast PortSchemeDependentUserPreferences.Contrast
#define UserPrefSaturation PortSchemeDependentUserPreferences.Saturation
#define UserPrefHue PortSchemeDependentUserPreferences.Hue
#define UserPrefUserRedGain PortSchemeDependentUserPreferences.UserRedGain
#define UserPrefUserGreenGain PortSchemeDependentUserPreferences.UserGreenGain
#define UserPrefUserBlueGain PortSchemeDependentUserPreferences.UserBlueGain
#define UserPrefUserRedOff PortSchemeDependentUserPreferences.UserRedOff
#define UserPrefUserGreenOff PortSchemeDependentUserPreferences.UserGreenOff
#define UserPrefUserBlueOff PortSchemeDependentUserPreferences.UserBlueOff
#define UserPrefColorTemp PortSchemeDependentUserPreferences.ColorTemp
#define UserPrefGammaTable PortSchemeDependentUserPreferences.GammaTable
#define UserPrefMFMImageScheme PortSchemeDependentUserPreferences.MFMImageScheme
#define UserPrefInputColorDomain PortSchemeDependentUserPreferences.InputColorDomain
#define UserPrefOutputColorType PortSchemeDependentUserPreferences.OutputColorType
#define UserPrefDUMSwitch PortSchemeDependentUserPreferences.DUMSwitch
#define UserPrefPortSchemeDependent PortSchemeDependentUserPreferences


#define ADJUSTER_TNR_DECLARED 
#define ADJUSTER_MADI_DECLARED 
#define ADJUSTER_CCS_DECLARED 
#define ADJUSTER_SHARPNOISE_DECLARED 
#define ADJUSTER_SPLITSCREEN_DECLARED 
#define ADJUSTER_DCDIMAIN_DECLARED 
#define ADJUSTER_DCDIPIP_DECLARED 
#define ADJUSTER_MPEGNRMODE_DECLARED 
#define ADJUSTER_MPEGNRTHRESH0_DECLARED 
#define ADJUSTER_MPEGNRTHRESH1_DECLARED 
#define ADJUSTER_MPEGNRTHRESH2_DECLARED 
#define ADJUSTER_LCDOVERDRIVENOISECORING_DECLARED 
#define ADJUSTER_THREETWOFILMDISPLAYMODE_DECLARED 
#define ADJUSTER_VBI_SERVICEPREFERRED_DECLARED 
#define ADJUSTER_SHARPNESSPIP_DECLARED 
#define ADJUSTER_BLUESTRETCH_DECLARED 
#define ADJUSTER_SHARPNESSRGB_DECLARED 
#define ADJUSTER_SHARPNESSRGBPIP_DECLARED 
#define ADJUSTER_AVSDELAY_DECLARED 
#define ADJUSTER_AUDIOVOLUME_DECLARED 
#define ADJUSTER_ADCCALIBRATIONMETHOD_COMP_DECLARED 
#define ADJUSTER_ADCCALIBRATIONMETHOD_VGA_DECLARED 
#define ADJUSTER_ASPECTRATIOMAIN_DECLARED 
#define ADJUSTER_ASPECTRATIOPIP_DECLARED 
#define ADJUSTER_CURRENTINPUTMAIN_DECLARED 
#define ADJUSTER_CURRENTINPUTPIP_DECLARED 
#define ADJUSTER_DYNAMICCONTRAST_DECLARED 
#define ADJUSTER_FILMMODE_DECLARED 
#define ADJUSTER_FLESHTONECOMP_DECLARED 
#define ADJUSTER_IMAGESCHEME_DECLARED 
#define ADJUSTER_LCDOVERDRIVE_DECLARED 
#define ADJUSTER_LETTERBOXENABLE_DECLARED 
#define ADJUSTER_MPEGNR_DECLARED 
#define ADJUSTER_OSDHPOSITION_DECLARED 
#define ADJUSTER_OSDLANGUAGE_DECLARED 
#define ADJUSTER_OSDROTATION_DECLARED 
#define ADJUSTER_OSDTIMEOUT_DECLARED 
#define ADJUSTER_OSDVPOSITION_DECLARED 
#define ADJUSTER_OVERSCANENABLE_DECLARED 
#define ADJUSTER_PANELSELECT_DECLARED 
#define ADJUSTER_PIPMODE_DECLARED 
#define ADJUSTER_PIPPOSITION_DECLARED 
#define ADJUSTER_POWERSTATE_DECLARED 
#define ADJUSTER_SHARPNESS_DECLARED 
#define ADJUSTER_SLEEPAMPM_DECLARED 
#define ADJUSTER_SLEEPDAY_DECLARED 
#define ADJUSTER_SLEEPHOUR_DECLARED 
#define ADJUSTER_SLEEPMIN_DECLARED 
#define ADJUSTER_SLEEPMINSLEFT_DECLARED 
#define ADJUSTER_THREEDNR_DECLARED 
#define ADJUSTER_TVRATING_DECLARED 
#define ADJUSTER_TVUNRATED_DECLARED 
#define ADJUSTER_VERSION_DECLARED 
#define ADJUSTER_WAKEAMPM_DECLARED 
#define ADJUSTER_WAKEDAY_DECLARED 
#define ADJUSTER_WAKEHOUR_DECLARED 
#define ADJUSTER_WAKEMIN_DECLARED 
#define ADJUSTER_MPRATING_DECLARED 
#define ADJUSTER_AVSDELAYTIME_DECLARED 
#define ADJUSTER_CC_ON_DECLARED 
#define ADJUSTER_AUDIOMUTE_DECLARED 
#define ADJUSTER_MPIPCONFIG_DECLARED 
#define ADJUSTER_OSDSPLASHSCREEN_DECLARED 
#define ADJUSTER_PARENTALPASSWORD_DECLARED 
#define ADJUSTER_PIPSIZE_DECLARED 
#define ADJUSTER_PREVIOUSINPUTMAIN_DECLARED 
#define ADJUSTER_SCROLLMENUITEM_DECLARED 
#define ADJUSTER_SPLITLCDOVERDRIVE_DECLARED 
#define ADJUSTER_TTXLANGUAGEGROUP_DECLARED 
#define ADJUSTER_MAINROUTEMODECOMPONENT_DECLARED 
#define ADJUSTER_MAINROUTEMODESCARTRGB_DECLARED 
#define ADJUSTER_PIPROUTEMODECOMPONENT_DECLARED 
#define ADJUSTER_PIPROUTEMODESCARTRGB_DECLARED 
#define ADJUSTER_REG_MVF_SHARPNESS_LUMA_DECLARED 
#define ADJUSTER_REG_MVF_SHARPNESS_CHROMA_DECLARED 
#define ADJUSTER_REG_MVF_NOISE_CORING_THRESH_DECLARED 
#define ADJUSTER_REG_MVF_NONLINEAR_THRESH1_DECLARED 
#define ADJUSTER_REG_MVF_NONLINEAR_GAIN1_DECLARED 
#define ADJUSTER_REG_MVF_NONLINEAR_THRESH2_DECLARED 
#define ADJUSTER_REG_MVF_NONLINEAR_GAIN2_DECLARED 
#define ADJUSTER_REG_MHF_SHARPNESS_LUMA_DECLARED 
#define ADJUSTER_REG_MHF_SHARPNESS_CHROMA_DECLARED 
#define ADJUSTER_REG_MHF_NOISE_CORING_THRESH_DECLARED 
#define ADJUSTER_REG_MHF_NONLINEAR_THRESH1_DECLARED 
#define ADJUSTER_REG_MHF_NONLINEAR_GAIN1_DECLARED 
#define ADJUSTER_REG_MHF_NONLINEAR_THRESH2_DECLARED 
#define ADJUSTER_REG_MHF_NONLINEAR_GAIN2_DECLARED 
#define ADJUSTER_REG_PVF_SHARPNESS_LUMA_DECLARED 
#define ADJUSTER_REG_PVF_SHARPNESS_CHROMA_DECLARED 
#define ADJUSTER_REG_PVF_NOISE_CORING_THRESH_DECLARED 
#define ADJUSTER_REG_PVF_NONLINEAR_THRESH1_DECLARED 
#define ADJUSTER_REG_PVF_NONLINEAR_GAIN1_DECLARED 
#define ADJUSTER_REG_PVF_NONLINEAR_THRESH2_DECLARED 
#define ADJUSTER_REG_PVF_NONLINEAR_GAIN2_DECLARED 
#define ADJUSTER_REG_PHF_SHARPNESS_LUMA_DECLARED 
#define ADJUSTER_REG_PHF_SHARPNESS_CHROMA_DECLARED 
#define ADJUSTER_REG_PHF_NOISE_CORING_THRESH_DECLARED 
#define ADJUSTER_REG_PHF_NONLINEAR_THRESH1_DECLARED 
#define ADJUSTER_REG_PHF_NONLINEAR_GAIN1_DECLARED 
#define ADJUSTER_REG_PHF_NONLINEAR_THRESH2_DECLARED 
#define ADJUSTER_REG_PHF_NONLINEAR_GAIN2_DECLARED 
#define ADJUSTER_REG_HEM_HLE_THR_DECLARED 
#define ADJUSTER_REG_HEM_HLE_GAIN_DECLARED 
#define ADJUSTER_REG_HEM_HDP_THR_DECLARED 
#define ADJUSTER_REG_HEM_HDP_GAIN_DECLARED 
#define ADJUSTER_REG_HEM_CE_THR_DECLARED 
#define ADJUSTER_REG_HEM_CE_GAIN_DECLARED 
#define ADJUSTER_REG_VDP_THRESHOLD_DECLARED 
#define ADJUSTER_REG_VDP_GAIN_DECLARED 
#define ADJUSTER_NATIVEMODE_DECLARED 
#define ADJUSTER_YUV2RGBEXPANSIONMODE_DECLARED 
#define ADJUSTER_NONACMFLESHTONECORRECTION_DECLARED 
#define ADJUSTER_NONACMFLESHTONEBALANCE_DECLARED 
#define ADJUSTER_NONACMFLESHTONECORRECTIONLEVEL_DECLARED 
#define ADJUSTER_TVYOUTH7SUBCODE_DECLARED 
#define ADJUSTER_TVPGSUBCODE_DECLARED 
#define ADJUSTER_TV14SUBCODE_DECLARED 
#define ADJUSTER_TVMASUBCODE_DECLARED 
#define ADJUSTER_DECODERAGCMETHOD_DECLARED 
#define ADJUSTER_CCSFORHD_DECLARED 
#define ADJUSTER_TWOSTAGEPROCESSING_DECLARED 
#define ADJUSTER_MANUALTVMHZFREQ_DECLARED 
#define ADJUSTER_MANUALTVKHZFREQ_DECLARED 
#define ADJUSTER_TVFREQFINETUNE_DECLARED 
#define ADJUSTER_TVMANUALSCANREQUIRED_DECLARED 
#define ADJUSTER_SCARTRGBVIAOVERLAY_DECLARED 
#define ADJUSTER_ADCCALIBRATIONMETHOD_CVBS_DECLARED 
#define ADJUSTER_ADCCALIBRATIONMETHOD_INTERNALDAC_DECLARED 
#define ADJUSTER_AUTOASPECTRATIO_DECLARED 
#define ADJUSTER_ADCCALIBRATIONMETHOD_SCART_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_LSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_SSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_LGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_SGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_FINALSGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_FINALLGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_FINALGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_DELTA_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_SLOPE_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_THRESH_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_HIGH_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_LOW_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_HIGH_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_Y_LOW_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_LSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_SSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_LGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_SGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_FINALSGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_FINALLGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_FINALGAIN_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_DELTA_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_SLOPE_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_THRESH_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_HIGH_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_LOW_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_HIGH_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MHF_ENH_UV_LOW_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_LSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_SSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_LGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_SGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_FINALSGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_FINALLGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_FINALGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_DELTA_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_SLOPE_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_THRESH_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_HIGH_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_LOW_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_HIGH_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_Y_LOW_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_LSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_SSHOOT_TOL_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_LGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_SGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_FINALSGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_FINALLGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_FINALGAIN_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_DELTA_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_SLOPE_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_THRESH_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_HIGH_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_LOW_SLOPE_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_HIGH_THRESH_AGC_DECLARED 
#define ADJUSTER_REG_MVF_ENH_UV_LOW_THRESH_AGC_DECLARED 
#define ADJUSTER_ENHANCERENABLE_DECLARED 
#define ADJUSTER_OLDENHANCERENABLE_DECLARED 
#define ADJUSTER_OLDENHANCERROUTING_DECLARED 
#define ADJUSTER_COLORRESOURCEROUTING_DECLARED 
#define ADJUSTER_ADCCALIBRATIONMETHOD_SIF_DECLARED 
#define ADJUSTER_IMPVLUT_DECLARED 
#define ADJUSTER_VARIABLEFORLINEOUT_DECLARED 
#define ADJUSTER_GAMEMODE_DECLARED 
#define ADJUSTER_XVYCC_DECLARED 
#define ADJUSTER_DCR_DECLARED 
#define ADJUSTER_XNUMBER_DECLARED 
#define ADJUSTER_YNUMBER_DECLARED 
#define ADJUSTER_PUBLICDISPLAYNUMBER_DECLARED 
#define ADJUSTER_AUDIODOWNMIX_DECLARED 
#define ADJUSTER_COLORSPACE_DECLARED 
#define ADJUSTER_VWDFLAG_DECLARED 
#define ADJUSTER_VWDDEMO_DECLARED 
#define ADJUSTER_AUDIOMAININPUT_DECLARED 
#define ADJUSTER_AUDIOMAINOUTPUT_DECLARED 
#define ADJUSTER_AUDIOPIPINPUT_DECLARED 
#define ADJUSTER_AUDIOPIPOUTPUT_DECLARED 
#define ADJUSTER_OSDG1BLEND_DECLARED 
#define ADJUSTER_OSDG2BLEND_DECLARED 
#define ADJUSTER_OSDG3BLEND_DECLARED 
#define ADJUSTER_CAPTUREM_DECLARED 
#define ADJUSTER_IMAGEROTATION_DECLARED 
#define ADJUSTER_OSD_4KX2K_PORT_DECLARED 
#define ADJUSTER_DPSWITCH_DECLARED 
#define ADJUSTER_BACKLIGHT_DECLARED 
#define ADJUSTER_OSDBLEND_DECLARED 
#define ADJUSTER_FANSTATUS_DECLARED 
#define ADJUSTER_PIPHPOS_DECLARED 
#define ADJUSTER_PIPVPOS_DECLARED 
#define ADJUSTER_PIPMODEONOFF_DECLARED 
#define ADJUSTER_SCHEDULEONOFF_DECLARED 
#define ADJUSTER_OVERSCAN_DECLARED 
#define ADJUSTER_AUTOBLSTATE_DECLARED 
#define ADJUSTER_MINBRIGHTNESS_DECLARED 
#define ADJUSTER_AUTOADJUST_DECLARED 
#define ADJUSTER_DISPLAYPOS_DECLARED 
#define ADJUSTER_PARENTALBLOCKSTATEFLAGMAIN_DECLARED 
#define ADJUSTER_PARENTALBLOCKSTATEFLAGPIP_DECLARED 
#define ADJUSTER_CHANNELBLOCKSTATEFLAG_DECLARED 
#define ADJUSTER_CHANNELBLOCKSTATEFLAGPIP_DECLARED 
#define ADJUSTER_CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT1CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT2CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT3CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT4CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT5CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT6CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT7CHANNELNAME_DECLARED 
#define ADJUSTER_DIGIT8CHANNELNAME_DECLARED 
#define ADJUSTER_CHANNELNAMEGROUP_DECLARED 
#define ADJUSTER_FREEZE_DECLARED 
#define ADJUSTER_MULTIPIPSTATEFLAG_DECLARED 
#define ADJUSTER_OSDMPIPHPOS_DECLARED 
#define ADJUSTER_OSDMPIPVPOS_DECLARED 
#define ADJUSTER_OSDMPIPCHANNEL_DECLARED 
#define ADJUSTER_SIDEBYSIDEFOCUS_DECLARED 
#define ADJUSTER_OSDBOTTOMPOS_DECLARED 
#define ADJUSTER_OSDCENTERPOS_DECLARED 
#define ADJUSTER_PARENTALMENUACCESS_DECLARED 
#define ADJUSTER_VCHIPPASSWORD_DECLARED 
#define ADJUSTER_MONTH_DECLARED 
#define ADJUSTER_DATE_DECLARED 
#define ADJUSTER_YEAR_DECLARED 
#define ADJUSTER_HOUR_DECLARED 
#define ADJUSTER_MIN_DECLARED 
#define ADJUSTER_AMPM_DECLARED 
#define ADJUSTER_INFODISPLAYON_DECLARED 
#define ADJUSTER_PREVPIPSOURCE_DECLARED 
#define ADJUSTER_CHANNELFREQSLIDER_DECLARED 
#define ADJUSTER_CHANNELFREQVALUE_DECLARED 
#define ADJUSTER_FACTORYSTATE_DECLARED 
#define ADJUSTER_TEMPVAR_DECLARED 
#define ADJUSTER_REGADDR_DECLARED 
#define ADJUSTER_REGVAL_DECLARED 
#define ADJUSTER_PREVIOUSPIPMODE_DECLARED 
#define ADJUSTER_CHANNELNAMEENTRY1_DECLARED 
#define ADJUSTER_CHANNELNAMEENTRY2_DECLARED 
#define ADJUSTER_CHANNELNAMEENTRY3_DECLARED 
#define ADJUSTER_CHANNELNAMEENTRY4_DECLARED 
#define ADJUSTER_CHANNELNAMEENTRY5_DECLARED 
#define ADJUSTER_PTRSEGMENT_DECLARED 
#define ADJUSTER_PTROFFSET_DECLARED 
#define ADJUSTER_BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_1BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_2BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_3BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_4BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_5BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_6BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_7BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_8BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_9BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKEDCHANNEL_10BLOCKEDCHANNELLIST_DECLARED 
#define ADJUSTER_BLOCKCHANNELLISTGROUP_DECLARED 
#define ADJUSTER_OFFSETGAIN_DECLARED 
#define ADJUSTER_OFFSET1_1OFFSETGAIN_DECLARED 
#define ADJUSTER_OFFSET1_2OFFSETGAIN_DECLARED 
#define ADJUSTER_OFFSET1_3OFFSETGAIN_DECLARED 
#define ADJUSTER_OFFSET2_1OFFSETGAIN_DECLARED 
#define ADJUSTER_OFFSET2_2OFFSETGAIN_DECLARED 
#define ADJUSTER_OFFSET2_3OFFSETGAIN_DECLARED 
#define ADJUSTER_GAIN_1OFFSETGAIN_DECLARED 
#define ADJUSTER_GAIN_2OFFSETGAIN_DECLARED 
#define ADJUSTER_GAIN_3OFFSETGAIN_DECLARED 
#define ADJUSTER_ADCOFFSETGAINGROUP_DECLARED 
#define ADJUSTER_CHANNELNUMDISPLAYFLAG_DECLARED 
#define ADJUSTER_CHANNELNUMAPPENDDISPLAYFLAG_DECLARED 
#define ADJUSTER_OSDSCALE100PERCENT_DECLARED 
#define ADJUSTER_OSDFULLSCREENXPERCENT_DECLARED 
#define ADJUSTER_OSDFULLSCREENYPERCENT_DECLARED 
#define ADJUSTER_OSDSTATE_DECLARED 
#define ADJUSTER_OSDBITFLAGS_DECLARED 
#define ADJUSTER_CURRENTBLOCKEDTVRATINGSUBCODEMAIN_DECLARED 
#define ADJUSTER_CURRENTBLOCKEDTVRATINGSUBCODEPIP_DECLARED 
#define ADJUSTER_MPIPTILESET_DECLARED 
#define ADJUSTER_CHIPIDDIGIT1_DECLARED 
#define ADJUSTER_CHIPIDDIGIT2_DECLARED 
#define ADJUSTER_CHIPIDDIGIT3_DECLARED 
#define ADJUSTER_CHIPIDDIGIT4_DECLARED 
#define ADJUSTER_COLORSYSTEM_DECLARED 
#define ADJUSTER_TTXNOSIGNALFLAG_DECLARED 
#define ADJUSTER_INPUTPORTLIST_DECLARED 
#define ADJUSTER_GLOBALINPUTPORTLISTGROUPINPUTPORT_1INPUTPORTLIST_DECLARED 
#define ADJUSTER_GLOBALINPUTPORTLISTGROUPINPUTPORT_2INPUTPORTLIST_DECLARED 
#define ADJUSTER_GLOBALINPUTPORTLISTGROUPINPUTPORT_3INPUTPORTLIST_DECLARED 
#define ADJUSTER_GLOBALINPUTPORTLISTGROUPINPUTPORT_4INPUTPORTLIST_DECLARED 
#define ADJUSTER_GLOBALINPUTPORTLISTGROUPINPUTPORT_5INPUTPORTLIST_DECLARED 
#define ADJUSTER_GLOBALINPUTPORTLISTGROUP_DECLARED 
#define ADJUSTER_INPUTPORTCOUNT_DECLARED 
#define ADJUSTER_DISPLAYPORTNAME_DECLARED 
#define ADJUSTER_OLDORNEWPORTCHANGE_DECLARED 
#define ADJUSTER_STR1_SEG_DECLARED 
#define ADJUSTER_STR2_SEG_DECLARED 
#define ADJUSTER_STR3_SEG_DECLARED 
#define ADJUSTER_STR4_SEG_DECLARED 
#define ADJUSTER_STR1_OFS_DECLARED 
#define ADJUSTER_STR2_OFS_DECLARED 
#define ADJUSTER_STR3_OFS_DECLARED 
#define ADJUSTER_STR4_OFS_DECLARED 
#define ADJUSTER_CECDEVICENAME_SEG_DECLARED 
#define ADJUSTER_CECDEVICENAME_OFS_DECLARED 
#define ADJUSTER_CECDEVICETYPE_DECLARED 
#define ADJUSTER_DONTREMOVEOSD_DECLARED 
#define ADJUSTER_CECRECORDONEXTPLUGNUMBER_DECLARED 
#define ADJUSTER_CECDEVICEPOWERSTATUS_DECLARED 
#define ADJUSTER_CECSTATUSTEXT1_SEG_DECLARED 
#define ADJUSTER_CECSTATUSTEXT1_OFS_DECLARED 
#define ADJUSTER_CECSTATUSTEXT2_SEG_DECLARED 
#define ADJUSTER_CECSTATUSTEXT2_OFS_DECLARED 
#define ADJUSTER_CECSTATUSTEXT3_SEG_DECLARED 
#define ADJUSTER_CECSTATUSTEXT3_OFS_DECLARED 
#define ADJUSTER_CECSTATUSLINECOUNTER_DECLARED 
#define ADJUSTER_CECRECORDDATEDAY_DECLARED 
#define ADJUSTER_CECRECORDDATEMONTH_DECLARED 
#define ADJUSTER_CECRECORDTIMEHOURS_DECLARED 
#define ADJUSTER_CECRECORDTIMEMINUTES_DECLARED 
#define ADJUSTER_CECRECORDDURATIONHOURS_DECLARED 
#define ADJUSTER_CECRECORDDURATIONMINUTES_DECLARED 
#define ADJUSTER_CECHDMITREEMODE_DECLARED 
#define ADJUSTER_CECDEVICESELECTEDFROMHDMITREE_DECLARED 
#define ADJUSTER_CECSYSTEMAUDIOSTATUS_DECLARED 
#define ADJUSTER_ISPFLASHWRPERCENT_DECLARED 
#define ADJUSTER_INFWMAJOR_DECLARED 
#define ADJUSTER_INFWMINOR_DECLARED 
#define ADJUSTER_INFWRC_DECLARED 
#define ADJUSTER_GLOBALOSD_TEMP_DECLARED 
#define ADJUSTER_OSD_IR_DECLARED 
#define ADJUSTER_TEST1_DECLARED 
#define ADJUSTER_TEST2_DECLARED 
#define ADJUSTER_VIDEO_D_DECLARED 
#define ADJUSTER_BURNINMODE_DECLARED 
#define ADJUSTER_BURNINMODEV_DECLARED 
#define ADJUSTER_GLOBALTEST_PATTERN_DECLARED 
#define ADJUSTER_LED_SETTING_DECLARED 
#define ADJUSTER_OUTPUTTIMING_DECLARED 
#define ADJUSTER_HSTART_DECLARED 
#define ADJUSTER_VSTART_DECLARED 
#define ADJUSTER_HTOTAL_DECLARED 
#define ADJUSTER_HSYNCPHASE_DECLARED 
#define ADJUSTER_HSYNCDELAY_DECLARED 
#define ADJUSTER_VSYNCDELAY_DECLARED 
#define ADJUSTER_ACM3BLUELUMA_DECLARED 
#define ADJUSTER_ACM3CYANLUMA_DECLARED 
#define ADJUSTER_ACM3GREENLUMA_DECLARED 
#define ADJUSTER_ACM3MAGENTALUMA_DECLARED 
#define ADJUSTER_ACM3REDLUMA_DECLARED 
#define ADJUSTER_ACM3YELLOWLUMA_DECLARED 
#define ADJUSTER_ACM3BLACKLUMA_DECLARED 
#define ADJUSTER_ACM3WHITELUMA_DECLARED 
#define ADJUSTER_ACM3BLUEHUE_DECLARED 
#define ADJUSTER_ACM3CYANHUE_DECLARED 
#define ADJUSTER_ACM3GREENHUE_DECLARED 
#define ADJUSTER_ACM3MAGENTAHUE_DECLARED 
#define ADJUSTER_ACM3REDHUE_DECLARED 
#define ADJUSTER_ACM3YELLOWHUE_DECLARED 
#define ADJUSTER_ACM3BLACKHUE_DECLARED 
#define ADJUSTER_ACM3WHITEHUE_DECLARED 
#define ADJUSTER_ACM3BLUESAT_DECLARED 
#define ADJUSTER_ACM3CYANSAT_DECLARED 
#define ADJUSTER_ACM3GREENSAT_DECLARED 
#define ADJUSTER_ACM3MAGENTASAT_DECLARED 
#define ADJUSTER_ACM3REDSAT_DECLARED 
#define ADJUSTER_ACM3YELLOWSAT_DECLARED 
#define ADJUSTER_ACM3BLACKSAT_DECLARED 
#define ADJUSTER_ACM3WHITESAT_DECLARED 
#define ADJUSTER_ACMBLUEHUE_DECLARED 
#define ADJUSTER_ACMCYANHUE_DECLARED 
#define ADJUSTER_ACMGREENHUE_DECLARED 
#define ADJUSTER_ACMMAGENTAHUE_DECLARED 
#define ADJUSTER_ACMREDHUE_DECLARED 
#define ADJUSTER_ACMYELLOWHUE_DECLARED 
#define ADJUSTER_ACMBLUESAT_DECLARED 
#define ADJUSTER_ACMCYANSAT_DECLARED 
#define ADJUSTER_ACMGREENSAT_DECLARED 
#define ADJUSTER_ACMMAGENTASAT_DECLARED 
#define ADJUSTER_ACMREDSAT_DECLARED 
#define ADJUSTER_ACMYELLOWSAT_DECLARED 
#define ADJUSTER_BRIGHTNESS_DECLARED 
#define ADJUSTER_CONTRAST_DECLARED 
#define ADJUSTER_SATURATION_DECLARED 
#define ADJUSTER_HUE_DECLARED 
#define ADJUSTER_USERREDGAIN_DECLARED 
#define ADJUSTER_USERGREENGAIN_DECLARED 
#define ADJUSTER_USERBLUEGAIN_DECLARED 
#define ADJUSTER_USERREDOFF_DECLARED 
#define ADJUSTER_USERGREENOFF_DECLARED 
#define ADJUSTER_USERBLUEOFF_DECLARED 
#define ADJUSTER_COLORTEMP_DECLARED 
#define ADJUSTER_GAMMATABLE_DECLARED 
#define ADJUSTER_MFMIMAGESCHEME_DECLARED 
#define ADJUSTER_INPUTCOLORDOMAIN_DECLARED 
#define ADJUSTER_OUTPUTCOLORTYPE_DECLARED 
#define ADJUSTER_DUMSWITCH_DECLARED 




#endif  // ifndef OSD_USET_H_DEFINED
