////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#include "System\all.h"

// gmv_OsdAdjusterFuncSet definition
BYTE ROM * ROM gmv_OsdAdjusterFuncSet[199] =
{
	(BYTE ROM *) NULL_PTR,
	(BYTE ROM *) Adjust3DNR,
	(BYTE ROM *) AdjustAVSDelayOnOff,
	(BYTE ROM *) AdjustAcmBlackHue,
	(BYTE ROM *) AdjustAcmBlackLuma,
	(BYTE ROM *) AdjustAcmBlackSat,
	(BYTE ROM *) AdjustAcmBlueHue,
	(BYTE ROM *) AdjustAcmBlueLuma,
	(BYTE ROM *) AdjustAcmBlueSat,
	(BYTE ROM *) AdjustAcmCyanHue,
	(BYTE ROM *) AdjustAcmCyanLuma,
	(BYTE ROM *) AdjustAcmCyanSat,
	(BYTE ROM *) AdjustAcmGreenHue,
	(BYTE ROM *) AdjustAcmGreenLuma,
	(BYTE ROM *) AdjustAcmGreenSat,
	(BYTE ROM *) AdjustAcmMagentaHue,
	(BYTE ROM *) AdjustAcmMagentaLuma,
	(BYTE ROM *) AdjustAcmMagentaSat,
	(BYTE ROM *) AdjustAcmRedHue,
	(BYTE ROM *) AdjustAcmRedLuma,
	(BYTE ROM *) AdjustAcmRedSat,
	(BYTE ROM *) AdjustAcmWhiteHue,
	(BYTE ROM *) AdjustAcmWhiteLuma,
	(BYTE ROM *) AdjustAcmWhiteSat,
	(BYTE ROM *) AdjustAcmYellowHue,
	(BYTE ROM *) AdjustAcmYellowLuma,
	(BYTE ROM *) AdjustAcmYellowSat,
	(BYTE ROM *) AdjustAspectRatioMain,
	(BYTE ROM *) AdjustAspectRatioPip,
	(BYTE ROM *) AdjustAudio,
	(BYTE ROM *) AdjustAudioVolume,
	(BYTE ROM *) AdjustAutoAspectRatio,
	(BYTE ROM *) AdjustBackLight,
	(BYTE ROM *) AdjustBlueGain,
	(BYTE ROM *) AdjustBlueOff,
	(BYTE ROM *) AdjustBlueStretch,
	(BYTE ROM *) AdjustBrightness,
	(BYTE ROM *) AdjustCCS,
	(BYTE ROM *) AdjustCCSforHD,
	(BYTE ROM *) AdjustCaptureMain,
	(BYTE ROM *) AdjustColorDomain,
	(BYTE ROM *) AdjustColorResourceRouting,
	(BYTE ROM *) AdjustColorSpace,
	(BYTE ROM *) AdjustColorTemp,
	(BYTE ROM *) AdjustContrast,
	(BYTE ROM *) AdjustCurrentInputMain,
	(BYTE ROM *) AdjustCurrentInputPip,
	(BYTE ROM *) AdjustDCDiMain,
	(BYTE ROM *) AdjustDCDiPip,
	(BYTE ROM *) AdjustDPSwitch,
	(BYTE ROM *) AdjustDUMSwitch,
	(BYTE ROM *) AdjustDecoderAGCMethod,
	(BYTE ROM *) AdjustDynamicContrast,
	(BYTE ROM *) AdjustEnhancerEnable,
	(BYTE ROM *) AdjustFilmMode,
	(BYTE ROM *) AdjustFleshToneLevel,
	(BYTE ROM *) AdjustGammaCorrection,
	(BYTE ROM *) AdjustGreenGain,
	(BYTE ROM *) AdjustGreenOff,
	(BYTE ROM *) AdjustHEM_CE_GAIN,
	(BYTE ROM *) AdjustHEM_CE_THR,
	(BYTE ROM *) AdjustHEM_HDP_GAIN,
	(BYTE ROM *) AdjustHEM_HDP_THR,
	(BYTE ROM *) AdjustHEM_HLE_GAIN,
	(BYTE ROM *) AdjustHEM_HLE_THR,
	(BYTE ROM *) AdjustHStart,
	(BYTE ROM *) AdjustHSyncPhase,
	(BYTE ROM *) AdjustHTotal,
	(BYTE ROM *) AdjustHue,
	(BYTE ROM *) AdjustImageRotation,
	(BYTE ROM *) AdjustImageScheme,
	(BYTE ROM *) AdjustImpVlut,
	(BYTE ROM *) AdjustLCDOverdrive,
	(BYTE ROM *) AdjustLCDOverdriveNoiseCoring,
	(BYTE ROM *) AdjustLcdOverdriveSplit,
	(BYTE ROM *) AdjustMADI,
	(BYTE ROM *) AdjustMHF_NOISE_CORING_THRESH,
	(BYTE ROM *) AdjustMHF_NONLINEAR_GAIN1,
	(BYTE ROM *) AdjustMHF_NONLINEAR_GAIN2,
	(BYTE ROM *) AdjustMHF_NONLINEAR_THRESH1,
	(BYTE ROM *) AdjustMHF_NONLINEAR_THRESH2,
	(BYTE ROM *) AdjustMHF_SHARPNESS_CHROMA,
	(BYTE ROM *) AdjustMHF_SHARPNESS_LUMA,
	(BYTE ROM *) AdjustMPEGNR,
	(BYTE ROM *) AdjustMPEGNRMode,
	(BYTE ROM *) AdjustMPEGNRThresh,
	(BYTE ROM *) AdjustMVF_NOISE_CORING_THRESH,
	(BYTE ROM *) AdjustMVF_NONLINEAR_GAIN1,
	(BYTE ROM *) AdjustMVF_NONLINEAR_GAIN2,
	(BYTE ROM *) AdjustMVF_NONLINEAR_THRESH1,
	(BYTE ROM *) AdjustMVF_NONLINEAR_THRESH2,
	(BYTE ROM *) AdjustMVF_SHARPNESS_CHROMA,
	(BYTE ROM *) AdjustMVF_SHARPNESS_LUMA,
	(BYTE ROM *) AdjustNativeMode,
	(BYTE ROM *) AdjustNonACMFleshtoneBalance,
	(BYTE ROM *) AdjustNonACMFleshtoneCorrection,
	(BYTE ROM *) AdjustNonACMFleshtoneCorrectionLevel,
	(BYTE ROM *) AdjustOSDBlending,
	(BYTE ROM *) AdjustOSDBlending1,
	(BYTE ROM *) AdjustOSDBlending2,
	(BYTE ROM *) AdjustOldEnhancerEnable,
	(BYTE ROM *) AdjustOldEnhancerRouting,
	(BYTE ROM *) AdjustOsdHPosition,
	(BYTE ROM *) AdjustOsdLanguage,
	(BYTE ROM *) AdjustOsdVPosition,
	(BYTE ROM *) AdjustPHF_NOISE_CORING_THRESH,
	(BYTE ROM *) AdjustPHF_NONLINEAR_GAIN1,
	(BYTE ROM *) AdjustPHF_NONLINEAR_GAIN2,
	(BYTE ROM *) AdjustPHF_NONLINEAR_THRESH1,
	(BYTE ROM *) AdjustPHF_NONLINEAR_THRESH2,
	(BYTE ROM *) AdjustPHF_SHARPNESS_CHROMA,
	(BYTE ROM *) AdjustPHF_SHARPNESS_LUMA,
	(BYTE ROM *) AdjustPVF_NOISE_CORING_THRESH,
	(BYTE ROM *) AdjustPVF_NONLINEAR_GAIN1,
	(BYTE ROM *) AdjustPVF_NONLINEAR_GAIN2,
	(BYTE ROM *) AdjustPVF_NONLINEAR_THRESH1,
	(BYTE ROM *) AdjustPVF_NONLINEAR_THRESH2,
	(BYTE ROM *) AdjustPVF_SHARPNESS_CHROMA,
	(BYTE ROM *) AdjustPVF_SHARPNESS_LUMA,
	(BYTE ROM *) AdjustPipMode,
	(BYTE ROM *) AdjustPipPosition,
	(BYTE ROM *) AdjustRedGain,
	(BYTE ROM *) AdjustRedOff,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_DELTA,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_FINALGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_FINALLGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_FINALSGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_HIGH_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_HIGH_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_LGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_LOW_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_LOW_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_LSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_SGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_SLOPE,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_SSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MHF_ENH_UV_THRESH,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_DELTA,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_FINALGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_FINALLGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_FINALSGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_HIGH_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_HIGH_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_LGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_LOW_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_LOW_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_LSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_SGAIN,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_SLOPE,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_SSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MHF_ENH_Y_THRESH,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_DELTA,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_FINALGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_FINALLGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_FINALSGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_HIGH_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_HIGH_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_LGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_LOW_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_LOW_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_LSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_SGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_SLOPE,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_SSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MVF_ENH_UV_THRESH,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_DELTA,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_FINALGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_FINALLGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_FINALSGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_HIGH_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_HIGH_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_LGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_LOW_SLOPE_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_LOW_THRESH_AGC,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_LSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_SGAIN,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_SLOPE,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_SSHOOT_TOL,
	(BYTE ROM *) AdjustReg_MVF_ENH_Y_THRESH,
	(BYTE ROM *) AdjustSaturation,
	(BYTE ROM *) AdjustScartRGBViaOverlay,
	(BYTE ROM *) AdjustSharpNoise,
	(BYTE ROM *) AdjustSharpness,
	(BYTE ROM *) AdjustSharpnessRGB,
	(BYTE ROM *) AdjustSplitScreen,
	(BYTE ROM *) AdjustTNR,
	(BYTE ROM *) AdjustTTXLanguageGroup,
	(BYTE ROM *) AdjustThreeTwoFilmDisplayMode,
	(BYTE ROM *) AdjustTwoStageProcessing,
	(BYTE ROM *) AdjustVBIService,
	(BYTE ROM *) AdjustVDP_GAIN,
	(BYTE ROM *) AdjustVDP_THRESHOLD,
	(BYTE ROM *) AdjustVStart,
	(BYTE ROM *) AdjustYUV2RGBExpansionMode,
	(BYTE ROM *) FactoryAdjustADCValues,
	(BYTE ROM *) OsdBlend,
	(BYTE ROM *) SetOsdTimeout,
	(BYTE ROM *) VWD_ApplyHighLightWindow,
	(BYTE ROM *) VWD_Switch
};

// gmv_OsdMinMaxFuncSet definition
BYTE ROM * ROM gmv_OsdMinMaxFuncSet[7] =
{
	(BYTE ROM *) MaxDisplayNumber,
	(BYTE ROM *) MaxHStart,
	(BYTE ROM *) MaxHTotal,
	(BYTE ROM *) MaxVStart,
	(BYTE ROM *) MinHStart,
	(BYTE ROM *) MinHTotal,
	(BYTE ROM *) MinVStart
};

// gmv_OsdStepFuncSet definition
BYTE ROM * ROM gmv_OsdStepFuncSet[1] =
{
	(BYTE ROM *) BallisticAcceleration
};

////////////////////////////////////////////////////////////////////////////////
//    Each entry of the UserDefAdjusterProperty defined as shown bellow:
//		Control Byte, Offset, Step, AdjusterFunc, Min, Max
////////////////////////////////////////////////////////////////////////////////

typedef enum 
{
	SwitcherOffsetChannelName = 2301,
	SwitcherOffsetBlockedChannelList = 2703,
	SwitcherOffsetOffsetGain = 2805,
	SwitcherOffsetInputPortList = 3057
} AdjValEnumInternal;

BYTE ROM gmv_UserDefAdjusterProperty[4158] =
{

	// ADJV_TNR
	// offset = 0
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(TNR_offset),
	1,
	ADJID_AdjustTNR,
	EXTRACT_2B(TNR_OFF),
	EXTRACT_2B(TNR_SUPER_HIGH),

	// ADJV_MADI
	// offset = 10
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(MADI_offset),
	1,
	ADJID_AdjustMADI,
	EXTRACT_2B(MADI_OFF),
	EXTRACT_2B(MADI_STANDARD),

	// ADJV_CCS
	// offset = 20
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(CCS_offset),
	1,
	ADJID_AdjustCCS,
	EXTRACT_2B(CCS_OFF),
	EXTRACT_2B(CCS_STANDARD),

	// ADJV_SharpNoise
	// offset = 30
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(SharpNoise_offset),
	1,
	ADJID_AdjustSharpNoise,
	EXTRACT_2B(SHARPNOISE_OFF),
	EXTRACT_2B(SHARPNOISE_HIGH),

	// ADJV_SplitScreen
	// offset = 40
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(SplitScreen_offset),
	1,
	ADJID_AdjustSplitScreen,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_DCDiMain
	// offset = 50
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(DCDiMain_offset),
	1,
	ADJID_AdjustDCDiMain,
	EXTRACT_2B(DISABLE),
	EXTRACT_2B(ENABLE),

	// ADJV_DCDiPip
	// offset = 60
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(DCDiPip_offset),
	1,
	ADJID_AdjustDCDiPip,
	EXTRACT_2B(DISABLE),
	EXTRACT_2B(ENABLE),

	// ADJV_MPEGNRMode
	// offset = 70
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(MPEGNRMode_offset),
	1,
	ADJID_AdjustMPEGNRMode,
	EXTRACT_2B(MPEG_NR_OFF),
	EXTRACT_2B(MPEG_NR_GAUSS),

	// ADJV_MPEGNRThresh0
	// offset = 80
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MPEGNRThresh0_offset),
	1,
	ADJID_AdjustMPEGNRThresh,
	EXTRACT_2B(0x0),
	EXTRACT_2B(MPEG_NR_THRESHOLD_0_MAX),

	// ADJV_MPEGNRThresh1
	// offset = 90
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MPEGNRThresh1_offset),
	1,
	ADJID_AdjustMPEGNRThresh,
	EXTRACT_2B(0x0),
	EXTRACT_2B(MPEG_NR_THRESHOLD_1_MAX),

	// ADJV_MPEGNRThresh2
	// offset = 100
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MPEGNRThresh2_offset),
	1,
	ADJID_AdjustMPEGNRThresh,
	EXTRACT_2B(0x0),
	EXTRACT_2B(MPEG_NR_THRESHOLD_2_MAX),

	// ADJV_LCDOverdriveNoiseCoring
	// offset = 110
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(LCDOverdriveNoiseCoring_offset),
	1,
	ADJID_AdjustLCDOverdriveNoiseCoring,
	EXTRACT_2B(OD_NOISE_CORING_OFF),
	EXTRACT_2B(OD_NOISE_CORING_ADAPTIVE),

	// ADJV_ThreeTwoFilmDisplayMode
	// offset = 120
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(ThreeTwoFilmDisplayMode_offset),
	1,
	ADJID_AdjustThreeTwoFilmDisplayMode,
	EXTRACT_2B(NORMAL_32_DISPLAY_MODE),
	EXTRACT_2B(FORCE_22_DISPLAY_MODE),

	// ADJV_VBI_ServicePreferred
	// offset = 130
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(VBI_ServicePreferred_offset),
	1,
	ADJID_AdjustVBIService,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_SharpnessPip
	// offset = 140
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SharpnessPip_offset),
	1,
	ADJID_AdjustSharpness,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x18),

	// ADJV_BlueStretch
	// offset = 150
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(BlueStretch_offset),
	1,
	ADJID_AdjustBlueStretch,
	EXTRACT_2B(BLUE_STRETCH_OFF),
	EXTRACT_2B(BLUE_STRETCH_HIGH),

	// ADJV_SharpnessRGB
	// offset = 160
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SharpnessRGB_offset),
	1,
	ADJID_AdjustSharpnessRGB,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x18),

	// ADJV_SharpnessRGBpip
	// offset = 170
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SharpnessRGBpip_offset),
	1,
	ADJID_AdjustSharpnessRGB,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x18),

	// ADJV_AVSDelay
	// offset = 180
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(AVSDelay_offset),
	1,
	ADJID_AdjustAVSDelayOnOff,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_AudioVolume
	// offset = 190
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioVolume_offset),
	2,
	ADJID_AdjustAudioVolume,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3E),

	// ADJV_ADCCalibrationMethod_Comp
	// offset = 200
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ADCCalibrationMethod_Comp_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ADC_METHODS_COMP-1),

	// ADJV_ADCCalibrationMethod_VGA
	// offset = 210
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ADCCalibrationMethod_VGA_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ADC_METHODS_VGA-1),

	// ADJV_AspectRatioMain
	// offset = 220
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AspectRatioMain_offset),
	1,
	ADJID_AdjustAspectRatioMain,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ASPECT_RATIOS),

	// ADJV_AspectRatioPip
	// offset = 230
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AspectRatioPip_offset),
	1,
	ADJID_AdjustAspectRatioPip,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ASPECT_RATIOS),

	// ADJV_CurrentInputMain
	// offset = 240
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(CurrentInputMain_offset),
	1,
	ADJID_AdjustCurrentInputMain,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_OF_CONNECTORS - 1),

	// ADJV_CurrentInputPip
	// offset = 250
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(CurrentInputPip_offset),
	1,
	ADJID_AdjustCurrentInputPip,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_OF_CONNECTORS - 1),

	// ADJV_DynamicContrast
	// offset = 260
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(DynamicContrast_offset),
	1,
	ADJID_AdjustDynamicContrast,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xA),

	// ADJV_FilmMode
	// offset = 270
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(FilmMode_offset),
	1,
	ADJID_AdjustFilmMode,
	EXTRACT_2B(FM_DISABLED),
	EXTRACT_2B(FM_VIDEO_22),

	// ADJV_FleshToneComp
	// offset = 280
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(FleshToneComp_offset),
	1,
	ADJID_AdjustFleshToneLevel,
	EXTRACT_2B(FT_OFF),
	EXTRACT_2B(FT_HIGH),

	// ADJV_ImageScheme
	// offset = 290
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(ImageScheme_offset),
	1,
	ADJID_AdjustImageScheme,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_IMAGE_SCHEMES-1),

	// ADJV_LCDOverdrive
	// offset = 300
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(LCDOverdrive_offset),
	1,
	ADJID_AdjustLCDOverdrive,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_LetterboxEnable
	// offset = 310
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(LetterboxEnable_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_MPEGNR
	// offset = 320
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MPEGNR_offset),
	SFID_BallisticAcceleration | BIT7,
	ADJID_AdjustMPEGNR,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x40),

	// ADJV_OsdHPosition
	// offset = 330
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OsdHPosition_offset),
	1,
	ADJID_AdjustOsdHPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFE),

	// ADJV_OsdLanguage
	// offset = 340
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OsdLanguage_offset),
	1,
	ADJID_AdjustOsdLanguage,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x4),

	// ADJV_OsdRotation
	// offset = 350
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OsdRotation_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(OSD_NON_ROTATED),
	EXTRACT_2B(OSD_ROTATED_270),

	// ADJV_OsdTimeout
	// offset = 360
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OsdTimeout_offset),
	5,
	ADJID_SetOsdTimeout,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3C),

	// ADJV_OsdVPosition
	// offset = 370
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OsdVPosition_offset),
	1,
	ADJID_AdjustOsdVPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFE),

	// ADJV_OverscanEnable
	// offset = 380
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OverscanEnable_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_PanelSelect
	// offset = 390
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PanelSelect_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_PipMode
	// offset = 400
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PipMode_offset),
	1,
	ADJID_AdjustPipMode,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_PIP_MODES),

	// ADJV_PipPosition
	// offset = 410
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PipPosition_offset),
	1,
	ADJID_AdjustPipPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_PIP_POSITIONS),

	// ADJV_PowerState
	// offset = 420
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PowerState_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_Sharpness
	// offset = 430
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Sharpness_offset),
	1,
	ADJID_AdjustSharpness,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x18),

	// ADJV_SleepAMPM
	// offset = 440
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SleepAMPM_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_SleepDay
	// offset = 450
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SleepDay_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x7),

	// ADJV_SleepHour
	// offset = 460
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SleepHour_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xC),

	// ADJV_SleepMin
	// offset = 470
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SleepMin_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3B),

	// ADJV_SleepMinsLeft
	// offset = 480
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(SleepMinsLeft_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ThreeDNR
	// offset = 490
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ThreeDNR_offset),
	SFID_BallisticAcceleration | BIT7,
	ADJID_Adjust3DNR,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x10),

	// ADJV_TVRating
	// offset = 500
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(TVRating_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0x7),

	// ADJV_TVUnrated
	// offset = 510
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TVUnrated_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_Version
	// offset = 520
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Version_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(65535L),

	// ADJV_WakeAMPM
	// offset = 530
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(WakeAMPM_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_WakeDay
	// offset = 540
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(WakeDay_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x7),

	// ADJV_WakeHour
	// offset = 550
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(WakeHour_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xC),

	// ADJV_WakeMin
	// offset = 560
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(WakeMin_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3B),

	// ADJV_MPRating
	// offset = 570
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(MPRating_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0x7),

	// ADJV_AVSDelayTime
	// offset = 580
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(AVSDelayTime_offset),
	1,
	ADJID_AdjustAudio,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3E7),

	// ADJV_CC_On
	// offset = 590
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(CC_On_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_AudioMute
	// offset = 600
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioMute_offset),
	1,
	ADJID_AdjustAudio,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_MPipConfig
	// offset = 610
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MPipConfig_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_MPIP_CONFIGS-1),

	// ADJV_OSDSplashScreen
	// offset = 620
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OSDSplashScreen_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x2),

	// ADJV_ParentalPassword
	// offset = 630
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(ParentalPassword_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_PipSize
	// offset = 640
	(VT_SWORD),
	AGID_ModeIndependent,
	EXTRACT_2B(PipSize_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(LARGE_PIP),
	EXTRACT_2B(SMALL_PIP),

	// ADJV_PreviousInputMain
	// offset = 650
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PreviousInputMain_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_OF_CONNECTORS - 1),

	// ADJV_ScrollMenuItem
	// offset = 660
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ScrollMenuItem_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_SplitLcdOverdrive
	// offset = 670
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(SplitLcdOverdrive_offset),
	1,
	ADJID_AdjustLcdOverdriveSplit,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_TTXLanguageGroup
	// offset = 680
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TTXLanguageGroup_offset),
	1,
	ADJID_AdjustTTXLanguageGroup,
	EXTRACT_2B(TTX_LANGUAGE_GROUP_WESTERN_EUROPE),
	EXTRACT_2B(TTX_LANGUAGE_GROUP_FARSI + 1),

	// ADJV_MainRouteModeComponent
	// offset = 690
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MainRouteModeComponent_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_MainRouteModeScartRGB
	// offset = 700
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MainRouteModeScartRGB_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_PipRouteModeComponent
	// offset = 710
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PipRouteModeComponent_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_PipRouteModeScartRGB
	// offset = 720
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PipRouteModeScartRGB_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MVF_SHARPNESS_LUMA
	// offset = 730
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_SHARPNESS_LUMA_offset),
	1,
	ADJID_AdjustMVF_SHARPNESS_LUMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MVF_SHARPNESS_CHROMA
	// offset = 740
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_SHARPNESS_CHROMA_offset),
	1,
	ADJID_AdjustMVF_SHARPNESS_CHROMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MVF_NOISE_CORING_THRESH
	// offset = 750
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_NOISE_CORING_THRESH_offset),
	1,
	ADJID_AdjustMVF_NOISE_CORING_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MVF_NONLINEAR_THRESH1
	// offset = 760
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_NONLINEAR_THRESH1_offset),
	1,
	ADJID_AdjustMVF_NONLINEAR_THRESH1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MVF_NONLINEAR_GAIN1
	// offset = 770
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_NONLINEAR_GAIN1_offset),
	1,
	ADJID_AdjustMVF_NONLINEAR_GAIN1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_MVF_NONLINEAR_THRESH2
	// offset = 780
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_NONLINEAR_THRESH2_offset),
	1,
	ADJID_AdjustMVF_NONLINEAR_THRESH2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MVF_NONLINEAR_GAIN2
	// offset = 790
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_NONLINEAR_GAIN2_offset),
	1,
	ADJID_AdjustMVF_NONLINEAR_GAIN2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_MHF_SHARPNESS_LUMA
	// offset = 800
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_SHARPNESS_LUMA_offset),
	1,
	ADJID_AdjustMHF_SHARPNESS_LUMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MHF_SHARPNESS_CHROMA
	// offset = 810
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_SHARPNESS_CHROMA_offset),
	1,
	ADJID_AdjustMHF_SHARPNESS_CHROMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MHF_NOISE_CORING_THRESH
	// offset = 820
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_NOISE_CORING_THRESH_offset),
	1,
	ADJID_AdjustMHF_NOISE_CORING_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MHF_NONLINEAR_THRESH1
	// offset = 830
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_NONLINEAR_THRESH1_offset),
	1,
	ADJID_AdjustMHF_NONLINEAR_THRESH1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MHF_NONLINEAR_GAIN1
	// offset = 840
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_NONLINEAR_GAIN1_offset),
	1,
	ADJID_AdjustMHF_NONLINEAR_GAIN1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_MHF_NONLINEAR_THRESH2
	// offset = 850
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_NONLINEAR_THRESH2_offset),
	1,
	ADJID_AdjustMHF_NONLINEAR_THRESH2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_MHF_NONLINEAR_GAIN2
	// offset = 860
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_NONLINEAR_GAIN2_offset),
	1,
	ADJID_AdjustMHF_NONLINEAR_GAIN2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_PVF_SHARPNESS_LUMA
	// offset = 870
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_SHARPNESS_LUMA_offset),
	1,
	ADJID_AdjustPVF_SHARPNESS_LUMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PVF_SHARPNESS_CHROMA
	// offset = 880
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_SHARPNESS_CHROMA_offset),
	1,
	ADJID_AdjustPVF_SHARPNESS_CHROMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PVF_NOISE_CORING_THRESH
	// offset = 890
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_NOISE_CORING_THRESH_offset),
	1,
	ADJID_AdjustPVF_NOISE_CORING_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PVF_NONLINEAR_THRESH1
	// offset = 900
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_NONLINEAR_THRESH1_offset),
	1,
	ADJID_AdjustPVF_NONLINEAR_THRESH1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PVF_NONLINEAR_GAIN1
	// offset = 910
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_NONLINEAR_GAIN1_offset),
	1,
	ADJID_AdjustPVF_NONLINEAR_GAIN1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_PVF_NONLINEAR_THRESH2
	// offset = 920
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_NONLINEAR_THRESH2_offset),
	1,
	ADJID_AdjustPVF_NONLINEAR_THRESH2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PVF_NONLINEAR_GAIN2
	// offset = 930
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PVF_NONLINEAR_GAIN2_offset),
	1,
	ADJID_AdjustPVF_NONLINEAR_GAIN2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_PHF_SHARPNESS_LUMA
	// offset = 940
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_SHARPNESS_LUMA_offset),
	1,
	ADJID_AdjustPHF_SHARPNESS_LUMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PHF_SHARPNESS_CHROMA
	// offset = 950
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_SHARPNESS_CHROMA_offset),
	1,
	ADJID_AdjustPHF_SHARPNESS_CHROMA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PHF_NOISE_CORING_THRESH
	// offset = 960
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_NOISE_CORING_THRESH_offset),
	1,
	ADJID_AdjustPHF_NOISE_CORING_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PHF_NONLINEAR_THRESH1
	// offset = 970
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_NONLINEAR_THRESH1_offset),
	1,
	ADJID_AdjustPHF_NONLINEAR_THRESH1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PHF_NONLINEAR_GAIN1
	// offset = 980
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_NONLINEAR_GAIN1_offset),
	1,
	ADJID_AdjustPHF_NONLINEAR_GAIN1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_PHF_NONLINEAR_THRESH2
	// offset = 990
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_NONLINEAR_THRESH2_offset),
	1,
	ADJID_AdjustPHF_NONLINEAR_THRESH2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_PHF_NONLINEAR_GAIN2
	// offset = 1000
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_PHF_NONLINEAR_GAIN2_offset),
	1,
	ADJID_AdjustPHF_NONLINEAR_GAIN2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_Reg_HEM_HLE_THR
	// offset = 1010
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_HEM_HLE_THR_offset),
	1,
	ADJID_AdjustHEM_HLE_THR,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_HEM_HLE_GAIN
	// offset = 1020
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_HEM_HLE_GAIN_offset),
	1,
	ADJID_AdjustHEM_HLE_GAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_HEM_HDP_THR
	// offset = 1030
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_HEM_HDP_THR_offset),
	1,
	ADJID_AdjustHEM_HDP_THR,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_HEM_HDP_GAIN
	// offset = 1040
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_HEM_HDP_GAIN_offset),
	1,
	ADJID_AdjustHEM_HDP_GAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_HEM_CE_THR
	// offset = 1050
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_HEM_CE_THR_offset),
	1,
	ADJID_AdjustHEM_CE_THR,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_HEM_CE_GAIN
	// offset = 1060
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_HEM_CE_GAIN_offset),
	1,
	ADJID_AdjustHEM_CE_GAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Reg_VDP_THRESHOLD
	// offset = 1070
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_VDP_THRESHOLD_offset),
	1,
	ADJID_AdjustVDP_THRESHOLD,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_Reg_VDP_GAIN
	// offset = 1080
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_VDP_GAIN_offset),
	1,
	ADJID_AdjustVDP_GAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_NativeMode
	// offset = 1090
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(NativeMode_offset),
	1,
	ADJID_AdjustNativeMode,
	EXTRACT_2B(NATIVE_MODE_OFF),
	EXTRACT_2B(NATIVE_MODE_WITH_FILTERS),

	// ADJV_YUV2RGBExpansionMode
	// offset = 1100
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(YUV2RGBExpansionMode_offset),
	1,
	ADJID_AdjustYUV2RGBExpansionMode,
	EXTRACT_2B(YUV2RGB_EXPANSION_LINEAR),
	EXTRACT_2B(YUV2RGB_EXPANSION_FULL),

	// ADJV_NonACMFleshtoneCorrection
	// offset = 1110
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(NonACMFleshtoneCorrection_offset),
	1,
	ADJID_AdjustNonACMFleshtoneCorrection,
	EXTRACT_2B(DISABLE),
	EXTRACT_2B(ENABLE),

	// ADJV_NonACMFleshtoneBalance
	// offset = 1120
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(NonACMFleshtoneBalance_offset),
	1,
	ADJID_AdjustNonACMFleshtoneBalance,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x7),

	// ADJV_NonACMFleshtoneCorrectionLevel
	// offset = 1130
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(NonACMFleshtoneCorrectionLevel_offset),
	1,
	ADJID_AdjustNonACMFleshtoneCorrectionLevel,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_TVYouth7Subcode
	// offset = 1140
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TVYouth7Subcode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_TVPGSubcode
	// offset = 1150
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TVPGSubcode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_TV14Subcode
	// offset = 1160
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TV14Subcode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_TVMASubcode
	// offset = 1170
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TVMASubcode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_DecoderAGCMethod
	// offset = 1180
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(DecoderAGCMethod_offset),
	1,
	ADJID_AdjustDecoderAGCMethod,
	EXTRACT_2B(SWAGC),
	EXTRACT_2B(DAGC + 1),

	// ADJV_CCSforHD
	// offset = 1190
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(CCSforHD_offset),
	1,
	ADJID_AdjustCCSforHD,
	EXTRACT_2B(Off),
	EXTRACT_2B(On),

	// ADJV_TwoStageProcessing
	// offset = 1200
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(TwoStageProcessing_offset),
	1,
	ADJID_AdjustTwoStageProcessing,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ManualTVMHzFreq
	// offset = 1210
	(VT_SWORD),
	AGID_ModeIndependent,
	EXTRACT_2B(ManualTVMHzFreq_offset),
	0,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3E7),

	// ADJV_ManualTVkHzFreq
	// offset = 1220
	(VT_SWORD),
	AGID_ModeIndependent,
	EXTRACT_2B(ManualTVkHzFreq_offset),
	0,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3E7),

	// ADJV_TVFreqFineTune
	// offset = 1230
	(VT_SWORD),
	AGID_ModeIndependent,
	EXTRACT_2B(TVFreqFineTune_offset),
	10,
	ADJID_NULL,
	EXTRACT_2B(-10000),
	EXTRACT_2B(0x2710),

	// ADJV_TVManualScanRequired
	// offset = 1240
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(TVManualScanRequired_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ScartRgbViaOverlay
	// offset = 1250
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(ScartRgbViaOverlay_offset),
	1,
	ADJID_AdjustScartRGBViaOverlay,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ADCCalibrationMethod_CVBS
	// offset = 1260
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ADCCalibrationMethod_CVBS_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ADC_METHODS_CVBS-1),

	// ADJV_ADCCalibrationMethod_InternalDac
	// offset = 1270
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ADCCalibrationMethod_InternalDac_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ADC_METHODS_INTERNAL_DAC-1),

	// ADJV_AutoAspectRatio
	// offset = 1280
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(AutoAspectRatio_offset),
	1,
	ADJID_AdjustAutoAspectRatio,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ADCCalibrationMethod_SCART
	// offset = 1290
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ADCCalibrationMethod_SCART_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ADC_METHODS_SCART-1),

	// ADJV_Reg_MHF_ENH_Y_LSHOOT_TOL
	// offset = 1300
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_LSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_LSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_SSHOOT_TOL
	// offset = 1310
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_SSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_SSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_LGAIN
	// offset = 1320
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_LGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_LGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_SGAIN
	// offset = 1330
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_SGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_SGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_FINALSGAIN
	// offset = 1340
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_FINALSGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_FINALSGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_FINALLGAIN
	// offset = 1350
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_FINALLGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_FINALLGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_FINALGAIN
	// offset = 1360
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_FINALGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_FINALGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_DELTA
	// offset = 1370
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_DELTA_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_DELTA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_Y_SLOPE
	// offset = 1380
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_SLOPE_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_SLOPE,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_Y_THRESH
	// offset = 1390
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_THRESH_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFF),

	// ADJV_Reg_MHF_ENH_Y_HIGH_SLOPE_AGC
	// offset = 1400
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_HIGH_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_HIGH_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_Y_LOW_SLOPE_AGC
	// offset = 1410
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_LOW_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_LOW_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_Y_HIGH_THRESH_AGC
	// offset = 1420
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_HIGH_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_HIGH_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_Y_LOW_THRESH_AGC
	// offset = 1430
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_Y_LOW_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_Y_LOW_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_LSHOOT_TOL
	// offset = 1440
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_LSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_LSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_SSHOOT_TOL
	// offset = 1450
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_SSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_SSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_LGAIN
	// offset = 1460
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_LGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_LGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_SGAIN
	// offset = 1470
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_SGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_SGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_FINALSGAIN
	// offset = 1480
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_FINALSGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_FINALSGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_FINALLGAIN
	// offset = 1490
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_FINALLGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_FINALLGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_FINALGAIN
	// offset = 1500
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_FINALGAIN_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_FINALGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_DELTA
	// offset = 1510
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_DELTA_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_DELTA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_UV_SLOPE
	// offset = 1520
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_SLOPE_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_SLOPE,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_UV_THRESH
	// offset = 1530
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_THRESH_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFF),

	// ADJV_Reg_MHF_ENH_UV_HIGH_SLOPE_AGC
	// offset = 1540
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_HIGH_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_HIGH_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_UV_LOW_SLOPE_AGC
	// offset = 1550
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_LOW_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_LOW_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MHF_ENH_UV_HIGH_THRESH_AGC
	// offset = 1560
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_HIGH_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_HIGH_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MHF_ENH_UV_LOW_THRESH_AGC
	// offset = 1570
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MHF_ENH_UV_LOW_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MHF_ENH_UV_LOW_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_LSHOOT_TOL
	// offset = 1580
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_LSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_LSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_SSHOOT_TOL
	// offset = 1590
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_SSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_SSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_LGAIN
	// offset = 1600
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_LGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_LGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_SGAIN
	// offset = 1610
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_SGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_SGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_FINALSGAIN
	// offset = 1620
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_FINALSGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_FINALSGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_FINALLGAIN
	// offset = 1630
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_FINALLGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_FINALLGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_FINALGAIN
	// offset = 1640
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_FINALGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_FINALGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_DELTA
	// offset = 1650
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_DELTA_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_DELTA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_Y_SLOPE
	// offset = 1660
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_SLOPE_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_SLOPE,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_Y_THRESH
	// offset = 1670
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_THRESH_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFF),

	// ADJV_Reg_MVF_ENH_Y_HIGH_SLOPE_AGC
	// offset = 1680
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_HIGH_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_HIGH_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_Y_LOW_SLOPE_AGC
	// offset = 1690
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_LOW_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_LOW_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_Y_HIGH_THRESH_AGC
	// offset = 1700
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_HIGH_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_HIGH_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_Y_LOW_THRESH_AGC
	// offset = 1710
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_Y_LOW_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_Y_LOW_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_LSHOOT_TOL
	// offset = 1720
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_LSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_LSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_SSHOOT_TOL
	// offset = 1730
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_SSHOOT_TOL_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_SSHOOT_TOL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_LGAIN
	// offset = 1740
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_LGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_LGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_SGAIN
	// offset = 1750
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_SGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_SGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_FINALSGAIN
	// offset = 1760
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_FINALSGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_FINALSGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_FINALLGAIN
	// offset = 1770
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_FINALLGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_FINALLGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_FINALGAIN
	// offset = 1780
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_FINALGAIN_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_FINALGAIN,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_DELTA
	// offset = 1790
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_DELTA_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_DELTA,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_UV_SLOPE
	// offset = 1800
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_SLOPE_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_SLOPE,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_UV_THRESH
	// offset = 1810
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_THRESH_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_THRESH,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFF),

	// ADJV_Reg_MVF_ENH_UV_HIGH_SLOPE_AGC
	// offset = 1820
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_HIGH_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_HIGH_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_UV_LOW_SLOPE_AGC
	// offset = 1830
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_LOW_SLOPE_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_LOW_SLOPE_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_Reg_MVF_ENH_UV_HIGH_THRESH_AGC
	// offset = 1840
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_HIGH_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_HIGH_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_Reg_MVF_ENH_UV_LOW_THRESH_AGC
	// offset = 1850
	(VT_WORD),
	AGID_ModeIndependent,
	EXTRACT_2B(Reg_MVF_ENH_UV_LOW_THRESH_AGC_offset),
	1,
	ADJID_AdjustReg_MVF_ENH_UV_LOW_THRESH_AGC,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3FF),

	// ADJV_EnhancerEnable
	// offset = 1860
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(EnhancerEnable_offset),
	1,
	ADJID_AdjustEnhancerEnable,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OldEnhancerEnable
	// offset = 1870
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(OldEnhancerEnable_offset),
	1,
	ADJID_AdjustOldEnhancerEnable,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OldEnhancerRouting
	// offset = 1880
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(OldEnhancerRouting_offset),
	1,
	ADJID_AdjustOldEnhancerRouting,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ColorResourceRouting
	// offset = 1890
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(ColorResourceRouting_offset),
	1,
	ADJID_AdjustColorResourceRouting,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ADCCalibrationMethod_SIF
	// offset = 1900
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ADCCalibrationMethod_SIF_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_ADC_METHODS_SIF-1),

	// ADJV_ImpVlut
	// offset = 1910
	(VT_SBYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(ImpVlut_offset),
	1,
	ADJID_AdjustImpVlut,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_VariableForLineout
	// offset = 1920
	(VT_SBYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(VariableForLineout_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_GameMode
	// offset = 1930
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(GameMode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_XvYcc
	// offset = 1940
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(XvYcc_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x2),

	// ADJV_DCR
	// offset = 1950
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(DCR_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_XNumber
	// offset = 1960
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(XNumber_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0x4),

	// ADJV_YNumber
	// offset = 1970
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(YNumber_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0x4),

	// ADJV_PublicDisplayNumber
	// offset = 1980
	(VT_BYTE | VT_FuncMax),
	AGID_ModeIndependent,
	EXTRACT_2B(PublicDisplayNumber_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(EXTRID_MaxDisplayNumber),

	// ADJV_AudioDownMix
	// offset = 1990
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioDownMix_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ColorSpace
	// offset = 2000
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ColorSpace_offset),
	1,
	ADJID_AdjustColorSpace,
	EXTRACT_2B(0x0),
	EXTRACT_2B(MAX_COLOR_SPACE),

	// ADJV_VwdFlag
	// offset = 2010
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(VwdFlag_offset),
	1,
	ADJID_VWD_Switch,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_VwdDemo
	// offset = 2020
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(VwdDemo_offset),
	1,
	ADJID_VWD_ApplyHighLightWindow,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_AudioMainInput
	// offset = 2030
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioMainInput_offset),
	1,
	ADJID_AdjustAudio,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_AudioMainOutput
	// offset = 2040
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioMainOutput_offset),
	1,
	ADJID_AdjustAudio,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x4),

	// ADJV_AudioPipInput
	// offset = 2050
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioPipInput_offset),
	1,
	ADJID_AdjustAudio,
	EXTRACT_2B(gmd_AUDIO_SRC_SPDIF_IN),
	EXTRACT_2B(0x3),

	// ADJV_AudioPipOutput
	// offset = 2060
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(AudioPipOutput_offset),
	1,
	ADJID_AdjustAudio,
	EXTRACT_2B(gmd_AUDIO_TAR_HeadPhone_OUT),
	EXTRACT_2B(0x4),

	// ADJV_OSDG1Blend
	// offset = 2070
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OSDG1Blend_offset),
	1,
	ADJID_AdjustOSDBlending,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_OSDG2Blend
	// offset = 2080
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OSDG2Blend_offset),
	1,
	ADJID_AdjustOSDBlending1,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_OSDG3Blend
	// offset = 2090
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OSDG3Blend_offset),
	1,
	ADJID_AdjustOSDBlending2,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xF),

	// ADJV_CaptureM
	// offset = 2100
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(CaptureM_offset),
	1,
	ADJID_AdjustCaptureMain,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x2),

	// ADJV_ImageRotation
	// offset = 2110
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(ImageRotation_offset),
	1,
	ADJID_AdjustImageRotation,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_OSD_4Kx2K_Port
	// offset = 2120
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OSD_4Kx2K_Port_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x4),

	// ADJV_DPSWitch
	// offset = 2130
	(VT_BYTE | VT_Cyclic),
	AGID_ModeIndependent,
	EXTRACT_2B(DPSWitch_offset),
	1,
	ADJID_AdjustDPSwitch,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_BackLight
	// offset = 2140
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(BackLight_offset),
	1,
	ADJID_AdjustBackLight,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_OsdBlend
	// offset = 2150
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OsdBlend_offset),
	1,
	ADJID_OsdBlend,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x2),

	// ADJV_FanStatus
	// offset = 2160
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(FanStatus_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x2),

	// ADJV_PIPHPos
	// offset = 2170
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PIPHPos_offset),
	1,
	ADJID_AdjustPipPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_PIPVPos
	// offset = 2180
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PIPVPos_offset),
	1,
	ADJID_AdjustPipPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_PipModeOnOff
	// offset = 2190
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(PipModeOnOff_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ScheduleOnOff
	// offset = 2200
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(ScheduleOnOff_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OverScan
	// offset = 2210
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(OverScan_offset),
	1,
	ADJID_AdjustAspectRatioMain,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_AutoBLState
	// offset = 2220
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AutoBLState_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_MinBrightness
	// offset = 2230
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(MinBrightness_offset),
	1,
	ADJID_AdjustBackLight,
	EXTRACT_2B(0x5),
	EXTRACT_2B(0x23),

	// ADJV_AUTOADJUST
	// offset = 2240
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(AUTOADJUST_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_DisplayPos
	// offset = 2250
	(VT_BYTE),
	AGID_ModeIndependent,
	EXTRACT_2B(DisplayPos_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_ParentalBlockStateFlagMain
	// offset = 2260
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(ParentalBlockStateFlagMain_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(-128),
	EXTRACT_2B(0x7F),

	// ADJV_ParentalBlockStateFlagPip
	// offset = 2270
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(ParentalBlockStateFlagPip_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(-128),
	EXTRACT_2B(0x7F),

	// ADJV_ChannelBlockStateFlag
	// offset = 2280
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelBlockStateFlag_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ChannelBlockStateFlagPip
	// offset = 2290
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelBlockStateFlagPip_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ChannelName
	// offset = 2300
	(VT_Calculate | 1),

	// Switchers for ChannelName
	SWID_ChannelNameDigit,

	// ADJV_Digit1ChannelName
	// offset = 2302
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit1ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit2ChannelName
	// offset = 2312
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit2ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit3ChannelName
	// offset = 2322
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit3ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit4ChannelName
	// offset = 2332
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit4ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit5ChannelName
	// offset = 2342
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit5ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit6ChannelName
	// offset = 2352
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit6ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit7ChannelName
	// offset = 2362
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit7ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Digit8ChannelName
	// offset = 2372
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Digit8ChannelName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Freeze
	// offset = 2382
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Freeze_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_MultiPipStateFlag
	// offset = 2392
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(MultiPipStateFlag_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_OsdMPipHPos
	// offset = 2402
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(OsdMPipHPos_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_OsdMPipVPos
	// offset = 2412
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(OsdMPipVPos_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_OsdMPipChannel
	// offset = 2422
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(OsdMPipChannel_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_SideBySideFocus
	// offset = 2432
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(SideBySideFocus_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OSDBottomPos
	// offset = 2442
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(OSDBottomPos_offset),
	1,
	ADJID_AdjustOsdVPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_OSDCenterPos
	// offset = 2452
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(OSDCenterPos_offset),
	1,
	ADJID_AdjustOsdHPosition,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x32),

	// ADJV_ParentalMenuAccess
	// offset = 2462
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(ParentalMenuAccess_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(-128),
	EXTRACT_2B(0x7F),

	// ADJV_VChipPassword
	// offset = 2472
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(VChipPassword_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x270F),

	// ADJV_Month
	// offset = 2482
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Month_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0xC),

	// ADJV_Date
	// offset = 2492
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Date_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0x1F),

	// ADJV_Year
	// offset = 2502
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Year_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Hour
	// offset = 2512
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Hour_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0xC),

	// ADJV_Min
	// offset = 2522
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(Min_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3B),

	// ADJV_AMPM
	// offset = 2532
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(AMPM_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_InfoDisplayOn
	// offset = 2542
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(InfoDisplayOn_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_PrevPipSource
	// offset = 2552
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(PrevPipSource_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_OF_CONNECTORS),

	// ADJV_ChannelFreqSlider
	// offset = 2562
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelFreqSlider_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(MINCHANNELFREQSLIDER),
	EXTRACT_2B(MAXCHANNELFREQSLIDER),

	// ADJV_ChannelFreqValue
	// offset = 2572
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(ChannelFreqValue_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(MINCHANNELFREQVALUE),
	EXTRACT_2B(MAXCHANNELFREQVALUE),

	// ADJV_FactoryState
	// offset = 2582
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(FactoryState_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_TempVar
	// offset = 2592
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(TempVar_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_RegAddr
	// offset = 2602
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(RegAddr_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_RegVal
	// offset = 2612
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(RegVal_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_PreviousPipMode
	// offset = 2622
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(PreviousPipMode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(-128),
	EXTRACT_2B(0x7F),

	// ADJV_ChannelNameEntry1
	// offset = 2632
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNameEntry1_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChannelNameEntry2
	// offset = 2642
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNameEntry2_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChannelNameEntry3
	// offset = 2652
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNameEntry3_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChannelNameEntry4
	// offset = 2662
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNameEntry4_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChannelNameEntry5
	// offset = 2672
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNameEntry5_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_PtrSegment
	// offset = 2682
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(PtrSegment_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(-32768),
	EXTRACT_2B(0x7FFF),

	// ADJV_PtrOffset
	// offset = 2692
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(PtrOffset_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(-32768),
	EXTRACT_2B(0x7FFF),

	// ADJV_BlockedChannelList
	// offset = 2702
	(VT_Calculate | 1),

	// Switchers for BlockedChannelList
	SWID_BlockedChannelList,

	// ADJV_BlockedChannel_1BlockedChannelList
	// offset = 2704
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_1BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_2BlockedChannelList
	// offset = 2714
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_2BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_3BlockedChannelList
	// offset = 2724
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_3BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_4BlockedChannelList
	// offset = 2734
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_4BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_5BlockedChannelList
	// offset = 2744
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_5BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_6BlockedChannelList
	// offset = 2754
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_6BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_7BlockedChannelList
	// offset = 2764
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_7BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_8BlockedChannelList
	// offset = 2774
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_8BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_9BlockedChannelList
	// offset = 2784
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_9BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BlockedChannel_10BlockedChannelList
	// offset = 2794
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BlockedChannel_10BlockedChannelList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_OffsetGain
	// offset = 2804
	(VT_Calculate | 1),

	// Switchers for OffsetGain
	SWID_ADCOffsetGainList,

	// ADJV_Offset1_1OffsetGain
	// offset = 2806
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Offset1_1OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1FF),

	// ADJV_Offset1_2OffsetGain
	// offset = 2816
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Offset1_2OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1FF),

	// ADJV_Offset1_3OffsetGain
	// offset = 2826
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Offset1_3OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1FF),

	// ADJV_Offset2_1OffsetGain
	// offset = 2836
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Offset2_1OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x7F),

	// ADJV_Offset2_2OffsetGain
	// offset = 2846
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Offset2_2OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x7F),

	// ADJV_Offset2_3OffsetGain
	// offset = 2856
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Offset2_3OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x7F),

	// ADJV_Gain_1OffsetGain
	// offset = 2866
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Gain_1OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1FF),

	// ADJV_Gain_2OffsetGain
	// offset = 2876
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Gain_2OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1FF),

	// ADJV_Gain_3OffsetGain
	// offset = 2886
	(VT_SWORD),
	AGID_Global,
	EXTRACT_2B(Gain_3OffsetGain_offset),
	1,
	ADJID_FactoryAdjustADCValues,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1FF),

	// ADJV_ChannelNumDisplayFlag
	// offset = 2896
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNumDisplayFlag_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_ChannelNumAppendDisplayFlag
	// offset = 2906
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChannelNumAppendDisplayFlag_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OsdScale100Percent
	// offset = 2916
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(OsdScale100Percent_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_OsdFullScreenXPercent
	// offset = 2926
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(OsdFullScreenXPercent_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_OsdFullScreenYPercent
	// offset = 2936
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(OsdFullScreenYPercent_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_OsdState
	// offset = 2946
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(OsdState_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OsdBitFlags
	// offset = 2956
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(OsdBitFlags_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CurrentBlockedTVRatingSubcodeMain
	// offset = 2966
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CurrentBlockedTVRatingSubcodeMain_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_CurrentBlockedTVRatingSubcodePip
	// offset = 2976
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CurrentBlockedTVRatingSubcodePip_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1F),

	// ADJV_MPipTileSet
	// offset = 2986
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(MPipTileSet_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(Column_One),
	EXTRACT_2B(Column_Four),

	// ADJV_ChipIDdigit1
	// offset = 2996
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChipIDdigit1_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChipIDdigit2
	// offset = 3006
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChipIDdigit2_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChipIDdigit3
	// offset = 3016
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChipIDdigit3_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ChipIDdigit4
	// offset = 3026
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ChipIDdigit4_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_ColorSystem
	// offset = 3036
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(ColorSystem_offset),
	0,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x0),

	// ADJV_TtxNoSignalFlag
	// offset = 3046
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(TtxNoSignalFlag_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_InputPortList
	// offset = 3056
	(VT_Calculate | 1),

	// Switchers for InputPortList
	SWID_InputPortList,

	// ADJV_GlobalInputPortListGroupInputPort_1InputPortList
	// offset = 3058
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalInputPortListGroupInputPort_1InputPortList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_GlobalInputPortListGroupInputPort_2InputPortList
	// offset = 3068
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalInputPortListGroupInputPort_2InputPortList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_GlobalInputPortListGroupInputPort_3InputPortList
	// offset = 3078
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalInputPortListGroupInputPort_3InputPortList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_GlobalInputPortListGroupInputPort_4InputPortList
	// offset = 3088
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalInputPortListGroupInputPort_4InputPortList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_GlobalInputPortListGroupInputPort_5InputPortList
	// offset = 3098
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalInputPortListGroupInputPort_5InputPortList_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_InputPortCount
	// offset = 3108
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(InputPortCount_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_DisplayPortName
	// offset = 3118
	(VT_SBYTE),
	AGID_Global,
	EXTRACT_2B(DisplayPortName_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_OldOrNewPortChange
	// offset = 3128
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(OldOrNewPortChange_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),

	// ADJV_Str1_seg
	// offset = 3138
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str1_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str2_seg
	// offset = 3148
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str2_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str3_seg
	// offset = 3158
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str3_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str4_seg
	// offset = 3168
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str4_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str1_ofs
	// offset = 3178
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str1_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str2_ofs
	// offset = 3188
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str2_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str3_ofs
	// offset = 3198
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str3_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_Str4_ofs
	// offset = 3208
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(Str4_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecDeviceName_seg
	// offset = 3218
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecDeviceName_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecDeviceName_ofs
	// offset = 3228
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecDeviceName_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecDeviceType
	// offset = 3238
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecDeviceType_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_DontRemoveOSD
	// offset = 3248
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(DontRemoveOSD_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecRecordOnExtPlugNumber
	// offset = 3258
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordOnExtPlugNumber_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x5),

	// ADJV_CecDevicePowerStatus
	// offset = 3268
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecDevicePowerStatus_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusText1_seg
	// offset = 3278
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecStatusText1_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusText1_ofs
	// offset = 3288
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecStatusText1_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusText2_seg
	// offset = 3298
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecStatusText2_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusText2_ofs
	// offset = 3308
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecStatusText2_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusText3_seg
	// offset = 3318
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecStatusText3_seg_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusText3_ofs
	// offset = 3328
	(VT_WORD),
	AGID_Global,
	EXTRACT_2B(CecStatusText3_ofs_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecStatusLineCounter
	// offset = 3338
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecStatusLineCounter_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecRecordDateDay
	// offset = 3348
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordDateDay_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0x1F),

	// ADJV_CecRecordDateMonth
	// offset = 3358
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordDateMonth_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x1),
	EXTRACT_2B(0xC),

	// ADJV_CecRecordTimeHours
	// offset = 3368
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordTimeHours_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x17),

	// ADJV_CecRecordTimeMinutes
	// offset = 3378
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordTimeMinutes_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3B),

	// ADJV_CecRecordDurationHours
	// offset = 3388
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordDurationHours_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x63),

	// ADJV_CecRecordDurationMinutes
	// offset = 3398
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecRecordDurationMinutes_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3B),

	// ADJV_CecHDMITreeMode
	// offset = 3408
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecHDMITreeMode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_CecDeviceSelectedFromHDMITree
	// offset = 3418
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecDeviceSelectedFromHDMITree_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xE),

	// ADJV_CecSystemAudioStatus
	// offset = 3428
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(CecSystemAudioStatus_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_IspFlashWrPercent
	// offset = 3438
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(IspFlashWrPercent_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_InFwMajor
	// offset = 3448
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(InFwMajor_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_InFwMinor
	// offset = 3458
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(InFwMinor_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_InFwRc
	// offset = 3468
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(InFwRc_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_GlobalOSD_temp
	// offset = 3478
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalOSD_temp_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_OSD_IR
	// offset = 3488
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(OSD_IR_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_test1
	// offset = 3498
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(test1_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_test2
	// offset = 3508
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(test2_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_VIDEO_D
	// offset = 3518
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(VIDEO_D_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BurnInMode
	// offset = 3528
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BurnInMode_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_BurnInModeV
	// offset = 3538
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(BurnInModeV_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_GlobalTest_Pattern
	// offset = 3548
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(GlobalTest_Pattern_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_LED_Setting
	// offset = 3558
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(LED_Setting_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_OutputTiming
	// offset = 3568
	(VT_BYTE),
	AGID_Global,
	EXTRACT_2B(OutputTiming_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFF),

	// ADJV_HStart
	// offset = 3578
	(VT_WORD),
	AGID_ModeDependent,
	EXTRACT_2B(HStart_offset),
	1,
	ADJID_AdjustHStart,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_VStart
	// offset = 3588
	(VT_WORD),
	AGID_ModeDependent,
	EXTRACT_2B(VStart_offset),
	1,
	ADJID_AdjustVStart,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0xFFFF),

	// ADJV_HTotal
	// offset = 3598
	(VT_WORD | VT_FuncMin | VT_FuncMax),
	AGID_ModeDependent,
	EXTRACT_2B(HTotal_offset),
	1,
	ADJID_AdjustHTotal,
	EXTRACT_2B(EXTRID_MinHTotal),
	EXTRACT_2B(EXTRID_MaxHTotal),

	// ADJV_HSyncPhase
	// offset = 3608
	(VT_WORD),
	AGID_ModeDependent,
	EXTRACT_2B(HSyncPhase_offset),
	1,
	ADJID_AdjustHSyncPhase,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3F),

	// ADJV_HSyncDelay
	// offset = 3618
	(VT_SWORD | VT_FuncMin | VT_FuncMax),
	AGID_ModeDependent,
	EXTRACT_2B(HSyncDelay_offset),
	1,
	ADJID_AdjustHStart,
	EXTRACT_2B(EXTRID_MinHStart),
	EXTRACT_2B(EXTRID_MaxHStart),

	// ADJV_VSyncDelay
	// offset = 3628
	(VT_SWORD | VT_FuncMin | VT_FuncMax),
	AGID_ModeDependent,
	EXTRACT_2B(VSyncDelay_offset),
	1,
	ADJID_AdjustVStart,
	EXTRACT_2B(EXTRID_MinVStart),
	EXTRACT_2B(EXTRID_MaxVStart),

	// ADJV_Acm3BlueLuma
	// offset = 3638
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3BlueLuma_offset),
	1,
	ADJID_AdjustAcmBlueLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3CyanLuma
	// offset = 3648
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3CyanLuma_offset),
	1,
	ADJID_AdjustAcmCyanLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3GreenLuma
	// offset = 3658
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3GreenLuma_offset),
	1,
	ADJID_AdjustAcmGreenLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3MagentaLuma
	// offset = 3668
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3MagentaLuma_offset),
	1,
	ADJID_AdjustAcmMagentaLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3RedLuma
	// offset = 3678
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3RedLuma_offset),
	1,
	ADJID_AdjustAcmRedLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3YellowLuma
	// offset = 3688
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3YellowLuma_offset),
	1,
	ADJID_AdjustAcmYellowLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3BlackLuma
	// offset = 3698
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3BlackLuma_offset),
	1,
	ADJID_AdjustAcmBlackLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3WhiteLuma
	// offset = 3708
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3WhiteLuma_offset),
	1,
	ADJID_AdjustAcmWhiteLuma,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3BlueHue
	// offset = 3718
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3BlueHue_offset),
	1,
	ADJID_AdjustAcmBlueHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3CyanHue
	// offset = 3728
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3CyanHue_offset),
	1,
	ADJID_AdjustAcmCyanHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3GreenHue
	// offset = 3738
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3GreenHue_offset),
	1,
	ADJID_AdjustAcmGreenHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3MagentaHue
	// offset = 3748
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3MagentaHue_offset),
	1,
	ADJID_AdjustAcmMagentaHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3RedHue
	// offset = 3758
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3RedHue_offset),
	1,
	ADJID_AdjustAcmRedHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3YellowHue
	// offset = 3768
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3YellowHue_offset),
	1,
	ADJID_AdjustAcmYellowHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3BlackHue
	// offset = 3778
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3BlackHue_offset),
	1,
	ADJID_AdjustAcmBlackHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3WhiteHue
	// offset = 3788
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3WhiteHue_offset),
	1,
	ADJID_AdjustAcmWhiteHue,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_Acm3BlueSat
	// offset = 3798
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3BlueSat_offset),
	1,
	ADJID_AdjustAcmBlueSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3CyanSat
	// offset = 3808
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3CyanSat_offset),
	1,
	ADJID_AdjustAcmCyanSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3GreenSat
	// offset = 3818
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3GreenSat_offset),
	1,
	ADJID_AdjustAcmGreenSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3MagentaSat
	// offset = 3828
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3MagentaSat_offset),
	1,
	ADJID_AdjustAcmMagentaSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3RedSat
	// offset = 3838
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3RedSat_offset),
	1,
	ADJID_AdjustAcmRedSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3YellowSat
	// offset = 3848
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3YellowSat_offset),
	1,
	ADJID_AdjustAcmYellowSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3BlackSat
	// offset = 3858
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3BlackSat_offset),
	1,
	ADJID_AdjustAcmBlackSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_Acm3WhiteSat
	// offset = 3868
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Acm3WhiteSat_offset),
	1,
	ADJID_AdjustAcmWhiteSat,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x64),

	// ADJV_AcmBlueHue
	// offset = 3878
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmBlueHue_offset),
	1,
	ADJID_AdjustAcmBlueHue,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmCyanHue
	// offset = 3888
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmCyanHue_offset),
	1,
	ADJID_AdjustAcmCyanHue,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmGreenHue
	// offset = 3898
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmGreenHue_offset),
	1,
	ADJID_AdjustAcmGreenHue,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmMagentaHue
	// offset = 3908
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmMagentaHue_offset),
	1,
	ADJID_AdjustAcmMagentaHue,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmRedHue
	// offset = 3918
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmRedHue_offset),
	1,
	ADJID_AdjustAcmRedHue,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmYellowHue
	// offset = 3928
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmYellowHue_offset),
	1,
	ADJID_AdjustAcmYellowHue,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmBlueSat
	// offset = 3938
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmBlueSat_offset),
	1,
	ADJID_AdjustAcmBlueSat,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmCyanSat
	// offset = 3948
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmCyanSat_offset),
	1,
	ADJID_AdjustAcmCyanSat,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmGreenSat
	// offset = 3958
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmGreenSat_offset),
	1,
	ADJID_AdjustAcmGreenSat,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmMagentaSat
	// offset = 3968
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmMagentaSat_offset),
	1,
	ADJID_AdjustAcmMagentaSat,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmRedSat
	// offset = 3978
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmRedSat_offset),
	1,
	ADJID_AdjustAcmRedSat,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_AcmYellowSat
	// offset = 3988
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(AcmYellowSat_offset),
	1,
	ADJID_AdjustAcmYellowSat,
	EXTRACT_2B(-16),
	EXTRACT_2B(0xF),

	// ADJV_Brightness
	// offset = 3998
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Brightness_offset),
	2,
	ADJID_AdjustBrightness,
	EXTRACT_2B(-100),
	EXTRACT_2B(0x64),

	// ADJV_Contrast
	// offset = 4008
	(VT_WORD),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Contrast_offset),
	2,
	ADJID_AdjustContrast,
	EXTRACT_2B(0x9C),
	EXTRACT_2B(0x164),

	// ADJV_Saturation
	// offset = 4018
	(VT_WORD),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Saturation_offset),
	2,
	ADJID_AdjustSaturation,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x200),

	// ADJV_Hue
	// offset = 4028
	(VT_SWORD),
	AGID_PortSchemeDependent,
	EXTRACT_2B(Hue_offset),
	2,
	ADJID_AdjustHue,
	EXTRACT_2B(-180),
	EXTRACT_2B(0xB4),

	// ADJV_UserRedGain
	// offset = 4038
	(VT_WORD),
	AGID_PortSchemeDependent,
	EXTRACT_2B(UserRedGain_offset),
	2,
	ADJID_AdjustRedGain,
	EXTRACT_2B(0x9C),
	EXTRACT_2B(0x164),

	// ADJV_UserGreenGain
	// offset = 4048
	(VT_WORD),
	AGID_PortSchemeDependent,
	EXTRACT_2B(UserGreenGain_offset),
	2,
	ADJID_AdjustGreenGain,
	EXTRACT_2B(0x9C),
	EXTRACT_2B(0x164),

	// ADJV_UserBlueGain
	// offset = 4058
	(VT_WORD),
	AGID_PortSchemeDependent,
	EXTRACT_2B(UserBlueGain_offset),
	2,
	ADJID_AdjustBlueGain,
	EXTRACT_2B(0x9C),
	EXTRACT_2B(0x164),

	// ADJV_UserRedOff
	// offset = 4068
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(UserRedOff_offset),
	1,
	ADJID_AdjustRedOff,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_UserGreenOff
	// offset = 4078
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(UserGreenOff_offset),
	1,
	ADJID_AdjustGreenOff,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_UserBlueOff
	// offset = 4088
	(VT_SBYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(UserBlueOff_offset),
	1,
	ADJID_AdjustBlueOff,
	EXTRACT_2B(-50),
	EXTRACT_2B(0x32),

	// ADJV_ColorTemp
	// offset = 4098
	(VT_BYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(ColorTemp_offset),
	1,
	ADJID_AdjustColorTemp,
	EXTRACT_2B(0x0),
	EXTRACT_2B(MAX_COLOR_TEMP),

	// ADJV_GammaTable
	// offset = 4108
	(VT_BYTE | VT_Cyclic),
	AGID_PortSchemeDependent,
	EXTRACT_2B(GammaTable_offset),
	1,
	ADJID_AdjustGammaCorrection,
	EXTRACT_2B(GAMMA_TABLE_OFF),
	EXTRACT_2B(GAMMA_TABLE_28),

	// ADJV_MFMImageScheme
	// offset = 4118
	(VT_BYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(MFMImageScheme_offset),
	1,
	ADJID_NULL,
	EXTRACT_2B(0x0),
	EXTRACT_2B(NUM_IMAGE_SCHEMES-1),

	// ADJV_InputColorDomain
	// offset = 4128
	(VT_BYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(InputColorDomain_offset),
	1,
	ADJID_AdjustColorDomain,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_OutputColorType
	// offset = 4138
	(VT_BYTE),
	AGID_PortSchemeDependent,
	EXTRACT_2B(OutputColorType_offset),
	1,
	ADJID_AdjustColorDomain,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x3),

	// ADJV_DUMSwitch
	// offset = 4148
	(VT_SBYTE | VT_Cyclic),
	AGID_PortSchemeDependent,
	EXTRACT_2B(DUMSwitch_offset),
	1,
	ADJID_AdjustDUMSwitch,
	EXTRACT_2B(0x0),
	EXTRACT_2B(0x1),
};

WORD ROM gmc_AdjvNullValue = ADJV_NULL;

