////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_TRTBL_H_DEFINED
#define OSD_TRTBL_H_DEFINED

typedef enum 
{
	Key_None,
	Key_KEY_PHYSICAL_RIGHT,
	Key_KEY_PHYSICAL_SOURCE,
	Key_IR_SWAP,
	Key_KEY_PHYSICAL_SWAP,
	Key_KEY_PHYSICAL_MENU,
	Key_IR_MENU,
	Key_KEY_PHYSICAL_EXIT,
	Key_KEY_PHYSICAL_PIP,
	Key_KEY_PHYSICAL_SPLIT,
	Key_KEY_PHYSICAL_SUB,
	Key_KEY_PHYSICAL_POWER,
	Key_KEY_PHYSICAL_MUTE,
	Key_IR_AUTO,
	Key_KEY_PHYSICAL_RESET,
	Key_KEY_PHYSICAL_ADCCalibration_IR,
	Key_KEY_PHYSICAL_ASPECT,
	Key_KEY_PHYSICAL_Flip_IR,
	Key_KEY_PHYSICAL_DOWN,
	Key_KEY_PHYSICAL_UP,
	Key_KEY_PHYSICAL_LEFT,
	Key_KEY_PHYSICAL_OK,
	Key_KEY_PHYSICAL_VOLUME_DOWN,
	Key_KEY_PHYSICAL_FREEZE,
	Key_Key_PHYSICAL_BurnInMode,
	Key_KEY_PHYSICAL_SCAN,
	Key_KEY_PHYSICAL_SLEEP,
	Key_KEY_PHYSICAL_TTX_CC,
	Key_KEY_PHYSICAL_ENTER_JUMP,
	Key_KEY_PHYSICAL_INFO,
	Key_KEY_PHYSICAL_ONE,
	Key_KEY_PHYSICAL_TWO,
	Key_KEY_PHYSICAL_THREE,
	Key_KEY_PHYSICAL_CHANNEL_DOWN,
	Key_KEY_PHYSICAL_CHANNEL_UP,
	Key_KEY_PHYSICAL_VOLUME_UP,
	WBK_NUMBER_OF_KEYS = 35
} WBK_Keys;


//Translation Table ID defenition

extern ST_TRANSLATION_TABLE_ENTRY ROM * ROM GlobalTranslTableSet [];

typedef enum 
{
	TTID_DefaultState,
	TTID_SchemeButton,
	TTID_MpegNrSlider,
	TTID_ADC_Offset1LV1,
	TTID_BrightnessButton
} TranslTblID;

extern BYTE ROM TrtblMaxEntries[];

extern WORD ROM KEYPAD_DEBOUNCE_PERIOD;

#define WBK_FUNCTION_GETIRVALUE_USED		
#define WBK_FUNCTION_INITIRDRIVER_USED		
#define WBK_FUNCTION_GETADCVALUE_USED		
#define WBK_FUNCTION_INITADCDRIVER_USED		

extern WBK_KEYPAD_DEFINITION ROM* ROM WBK_Keypads[];
#define WB_NUMBER_OF_INPUT_SOURCE		3
extern BYTE ROM WBK_NumberOfKeypads;


extern BYTE ROM WBK_MultiplePortsValuesTranslation[];
#define WBK_NUMBER_OF_MULTIPLE_PORTS_VALUES		0
extern BYTE ROM WBK_NumberMultiplePortsValues;


#endif  // ifndef OSD_TRTBL_H_DEFINED
