////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#include "System\all.h"

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_DefaultState[35] =
{
	{
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_IR_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP_IR,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_IR_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU_IR,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SUB, 0x00 },
		OEK_KEY_LOGICAL_SUB,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_IR_AUTO, 0x00 },
		OEK_KEY_LOGICAL_AUTO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RESET, 0x00 },
		OEK_KEY_LOGICAL_RESET,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ADCCalibration_IR, 0x00 },
		OEK_KEY_LOGICAL_ADCCalibration_IR,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ASPECT, 0x00 },
		OEK_KEY_LOGICAL_ASPECT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_Flip_IR, 0x00 },
		OEK_KEY_LOGICAL_Flip_IR,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_ZOOM_OUT,
		17,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_ZOOM_IN,
		17,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		{ Key_Key_PHYSICAL_BurnInMode, 0x00 },
		OEK_KEY_LOGICAL_BurnInMode,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SCAN, 0x00 },
		OEK_KEY_LOGICAL_SCAN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SLEEP, 0x00 },
		OEK_KEY_LOGICAL_SLEEP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_TTX_CC, 0x00 },
		OEK_KEY_LOGICAL_TTX_ON,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ENTER_JUMP, 0x00 },
		OEK_KEY_LOGICAL_RECALL,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_INFO, 0x00 },
		OEK_KEY_LOGICAL_DISPLAY,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_ONE, 0x00 },
		OEK_KEY_LOGICAL_ONE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_TWO, 0x00 },
		OEK_KEY_LOGICAL_TWO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_THREE, 0x00 },
		OEK_KEY_LOGICAL_THREE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_UP, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_SchemeButton[19] =
{
	{
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP_RELEASED,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_IR_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP_IR,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_IR_AUTO, 0x00 },
		OEK_KEY_LOGICAL_AUTO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_CHANNEL_UP, 0x00 },
		OEK_KEY_LOGICAL_CHANNEL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_MpegNrSlider[14] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_IR_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP_IR,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_ADC_Offset1LV1[7] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_BrightnessButton[9] =
{
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x05 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT_AR1,
		12,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

////////////////////////////////////////////////////////////////////////////////
//    Translation tables
////////////////////////////////////////////////////////////////////////////////

ST_TRANSLATION_TABLE_ENTRY ROM * ROM GlobalTranslTableSet[5] =
{
	TrTable_DefaultState,
	TrTable_SchemeButton,
	TrTable_MpegNrSlider,
	TrTable_ADC_Offset1LV1,
	TrTable_BrightnessButton
};

BYTE ROM TrtblMaxEntries[5] =
{
	0x23,
	0x13,
	0x0e,
	0x07,
	0x09
};

WORD ROM KEYPAD_DEBOUNCE_PERIOD = 20;

BYTE ROM IR_Values[66] =
{
	WBK_EXTRACT_CODE_BYTE(72), Key_IR_AUTO,
	WBK_EXTRACT_CODE_BYTE(26), Key_IR_MENU,
	WBK_EXTRACT_CODE_BYTE(90), Key_IR_SWAP,
	WBK_EXTRACT_CODE_BYTE(232), Key_KEY_PHYSICAL_ADCCalibration_IR,
	WBK_EXTRACT_CODE_BYTE(170), Key_KEY_PHYSICAL_ASPECT,
	WBK_EXTRACT_CODE_BYTE(209), Key_KEY_PHYSICAL_CHANNEL_DOWN,
	WBK_EXTRACT_CODE_BYTE(208), Key_KEY_PHYSICAL_CHANNEL_UP,
	WBK_EXTRACT_CODE_BYTE(18), Key_KEY_PHYSICAL_DOWN,
	WBK_EXTRACT_CODE_BYTE(206), Key_KEY_PHYSICAL_ENTER_JUMP,
	WBK_EXTRACT_CODE_BYTE(42), Key_KEY_PHYSICAL_EXIT,
	WBK_EXTRACT_CODE_BYTE(204), Key_KEY_PHYSICAL_FREEZE,
	WBK_EXTRACT_CODE_BYTE(106), Key_KEY_PHYSICAL_Flip_IR,
	WBK_EXTRACT_CODE_BYTE(15), Key_KEY_PHYSICAL_INFO,
	WBK_EXTRACT_CODE_BYTE(48), Key_KEY_PHYSICAL_LEFT,
	WBK_EXTRACT_CODE_BYTE(50), Key_KEY_PHYSICAL_MENU,
	WBK_EXTRACT_CODE_BYTE(168), Key_KEY_PHYSICAL_MUTE,
	WBK_EXTRACT_CODE_BYTE(200), Key_KEY_PHYSICAL_OK,
	WBK_EXTRACT_CODE_BYTE(1), Key_KEY_PHYSICAL_ONE,
	WBK_EXTRACT_CODE_BYTE(40), Key_KEY_PHYSICAL_PIP,
	WBK_EXTRACT_CODE_BYTE(136), Key_KEY_PHYSICAL_POWER,
	WBK_EXTRACT_CODE_BYTE(234), Key_KEY_PHYSICAL_RESET,
	WBK_EXTRACT_CODE_BYTE(112), Key_KEY_PHYSICAL_RIGHT,
	WBK_EXTRACT_CODE_BYTE(31), Key_KEY_PHYSICAL_SCAN,
	WBK_EXTRACT_CODE_BYTE(38), Key_KEY_PHYSICAL_SLEEP,
	WBK_EXTRACT_CODE_BYTE(24), Key_KEY_PHYSICAL_SOURCE,
	WBK_EXTRACT_CODE_BYTE(36), Key_KEY_PHYSICAL_SPLIT,
	WBK_EXTRACT_CODE_BYTE(60), Key_KEY_PHYSICAL_SUB,
	WBK_EXTRACT_CODE_BYTE(3), Key_KEY_PHYSICAL_THREE,
	WBK_EXTRACT_CODE_BYTE(205), Key_KEY_PHYSICAL_TTX_CC,
	WBK_EXTRACT_CODE_BYTE(2), Key_KEY_PHYSICAL_TWO,
	WBK_EXTRACT_CODE_BYTE(178), Key_KEY_PHYSICAL_UP,
	WBK_EXTRACT_CODE_BYTE(152), Key_KEY_PHYSICAL_VOLUME_DOWN,
	WBK_EXTRACT_CODE_BYTE(88), Key_KEY_PHYSICAL_VOLUME_UP
};

WBK_KEYPAD_DEFINITION ROM Keypad_IR =
{
	0x00,
	IR_Values,
	0x21,
	GetIRValue,
	InitIRDriver,
	0x01,
	0x00
};

BYTE ROM ADC_2_Values[12] =
{
	WBK_EXTRACT_CODE_BYTE(192), Key_KEY_PHYSICAL_DOWN,
	WBK_EXTRACT_CODE_BYTE(122), Key_KEY_PHYSICAL_LEFT,
	WBK_EXTRACT_CODE_BYTE(151), Key_KEY_PHYSICAL_MENU,
	WBK_EXTRACT_CODE_BYTE(69), Key_KEY_PHYSICAL_RIGHT,
	WBK_EXTRACT_CODE_BYTE(99), Key_KEY_PHYSICAL_UP,
	WBK_EXTRACT_CODE_BYTE(142), Key_Key_PHYSICAL_BurnInMode
};

WBK_KEYPAD_DEFINITION ROM Keypad_ADC_2 =
{
	0x01,
	ADC_2_Values,
	0x06,
	GetADCValue,
	InitADCDriver,
	0x01,
	0x08
};

BYTE ROM ADC_1_Values[6] =
{
	WBK_EXTRACT_CODE_BYTE(171), Key_KEY_PHYSICAL_EXIT,
	WBK_EXTRACT_CODE_BYTE(36), Key_KEY_PHYSICAL_POWER,
	WBK_EXTRACT_CODE_BYTE(192), Key_KEY_PHYSICAL_SWAP
};

WBK_KEYPAD_DEFINITION ROM Keypad_ADC_1 =
{
	0x00,
	ADC_1_Values,
	0x03,
	GetADCValue,
	InitADCDriver,
	0x01,
	0x08
};

WBK_KEYPAD_DEFINITION ROM* ROM WBK_Keypads[3] =
{
	&Keypad_IR,
	&Keypad_ADC_2,
	&Keypad_ADC_1
};

BYTE ROM WBK_NumberOfKeypads = WB_NUMBER_OF_INPUT_SOURCE;

BYTE ROM WBK_MultiplePortsValuesTranslation[1] =
{
	0
};

BYTE ROM WBK_NumberMultiplePortsValues = WBK_NUMBER_OF_MULTIPLE_PORTS_VALUES;

